-- name: UpsertPlayEventBatch :batchexec
INSERT INTO play_events (
    game_id, event_id, period, period_type, time_in_period, time_remaining,
    situation_code, home_team_defending_side, type_code, type_desc_key, sort_order,
    x_coord, y_coord, zone_code, event_owner_team_id,
    shot_type, shooting_player_id, goalie_in_net_id,
    blocking_player_id,
    scoring_player_id, scoring_player_total,
    assist1_player_id, assist1_player_total,
    assist2_player_id, assist2_player_total,
    away_score, home_score,
    highlight_clip_id, highlight_clip_url, discrete_clip_id,
    penalty_type_code, penalty_desc_key, penalty_duration,
    committed_by_player_id, drawn_by_player_id,
    hitting_player_id, hittee_player_id,
    winning_player_id, losing_player_id,
    player_id, reason, away_sog, home_sog
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18,
    $19,
    $20, $21,
    $22, $23,
    $24, $25,
    $26, $27,
    $28, $29, $30,
    $31, $32, $33,
    $34, $35,
    $36, $37,
    $38, $39,
    $40, $41, $42, $43
)
ON CONFLICT (game_id, event_id) DO UPDATE SET
    period = EXCLUDED.period,
    period_type = EXCLUDED.period_type,
    time_in_period = EXCLUDED.time_in_period,
    time_remaining = EXCLUDED.time_remaining,
    situation_code = EXCLUDED.situation_code,
    home_team_defending_side = EXCLUDED.home_team_defending_side,
    type_code = EXCLUDED.type_code,
    type_desc_key = EXCLUDED.type_desc_key,
    sort_order = EXCLUDED.sort_order,
    x_coord = EXCLUDED.x_coord,
    y_coord = EXCLUDED.y_coord,
    zone_code = EXCLUDED.zone_code,
    event_owner_team_id = EXCLUDED.event_owner_team_id,
    shot_type = EXCLUDED.shot_type,
    shooting_player_id = EXCLUDED.shooting_player_id,
    goalie_in_net_id = EXCLUDED.goalie_in_net_id,
    blocking_player_id = EXCLUDED.blocking_player_id,
    scoring_player_id = EXCLUDED.scoring_player_id,
    scoring_player_total = EXCLUDED.scoring_player_total,
    assist1_player_id = EXCLUDED.assist1_player_id,
    assist1_player_total = EXCLUDED.assist1_player_total,
    assist2_player_id = EXCLUDED.assist2_player_id,
    assist2_player_total = EXCLUDED.assist2_player_total,
    away_score = EXCLUDED.away_score,
    home_score = EXCLUDED.home_score,
    highlight_clip_id = EXCLUDED.highlight_clip_id,
    highlight_clip_url = EXCLUDED.highlight_clip_url,
    discrete_clip_id = EXCLUDED.discrete_clip_id,
    penalty_type_code = EXCLUDED.penalty_type_code,
    penalty_desc_key = EXCLUDED.penalty_desc_key,
    penalty_duration = EXCLUDED.penalty_duration,
    committed_by_player_id = EXCLUDED.committed_by_player_id,
    drawn_by_player_id = EXCLUDED.drawn_by_player_id,
    hitting_player_id = EXCLUDED.hitting_player_id,
    hittee_player_id = EXCLUDED.hittee_player_id,
    winning_player_id = EXCLUDED.winning_player_id,
    losing_player_id = EXCLUDED.losing_player_id,
    player_id = EXCLUDED.player_id,
    reason = EXCLUDED.reason,
    away_sog = EXCLUDED.away_sog,
    home_sog = EXCLUDED.home_sog;
