package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"time"

	"github.com/sperano/puckdb/graph/model"
	"github.com/sperano/puckdb/sqlcdb"
)

var errDatabaseNotConfigured = fmt.Errorf("database not configured")

// Seasons is the resolver for the seasons field.
func (r *queryResolver) Seasons(ctx context.Context) ([]*model.Season, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetAllSeasons(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Season, len(rows))
	for i, s := range rows {
		out[i] = convertSeason(s)
	}
	return out, nil
}

// Season is the resolver for the season field.
func (r *queryResolver) Season(ctx context.Context, id int) (*model.Season, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	s, err := r.Resolver.Queries.GetSeason(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return convertSeason(s), nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, season int) ([]*model.Team, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetSeasonTeams(ctx, int32(season))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Team, len(rows))
	for i, t := range rows {
		out[i] = convertSeasonTeam(t)
	}
	return out, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, season int, teamID int64) (*model.Team, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	t, err := r.Resolver.Queries.GetSeasonTeam(ctx, sqlcdb.GetSeasonTeamParams{
		Season: int32(season),
		TeamID: teamID,
	})
	if err != nil {
		return nil, err
	}
	return convertSeasonTeam(t), nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id int64) (*model.Player, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	p, err := r.Resolver.Queries.GetPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	return convertPlayer(p), nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context, filter *model.PlayerFilter) ([]*model.Player, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	var params sqlcdb.ListPlayersParams
	if filter != nil {
		params.Name = optionalText(filter.Name)
		params.TeamID = optionalInt8(filter.TeamID)
		params.Position = optionalText(filter.Position)
		params.IsActive = optionalBool(filter.IsActive)
	}
	rows, err := r.Resolver.Queries.ListPlayers(ctx, params)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Player, len(rows))
	for i, p := range rows {
		out[i] = convertPlayer(p)
	}
	return out, nil
}

// SearchPlayers is the resolver for the searchPlayers field.
func (r *queryResolver) SearchPlayers(ctx context.Context, query string) ([]*model.Player, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	// SearchPlayersByName expects a LIKE pattern
	pattern := "%" + query + "%"
	rows, err := r.Resolver.Queries.SearchPlayersByName(ctx, pattern)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Player, len(rows))
	for i, p := range rows {
		out[i] = convertPlayer(p)
	}
	return out, nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id int64) (*model.Game, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	g, err := r.Resolver.Queries.GetGame(ctx, id)
	if err != nil {
		return nil, err
	}
	return convertGetGameRow(g), nil
}

// GamesByDate is the resolver for the gamesByDate field.
func (r *queryResolver) GamesByDate(ctx context.Context, date string) ([]*model.Game, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	d := parseDate(date)
	rows, err := r.Resolver.Queries.GetGamesByDate(ctx, d)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Game, len(rows))
	for i, g := range rows {
		out[i] = convertGamesByDateRow(g)
	}
	return out, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, filter *model.GameFilter) ([]*model.Game, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	var params sqlcdb.ListGamesParams
	if filter != nil {
		params.Season = optionalInt4(filter.Season)
		params.GameType = optionalGameType(filter.GameType)
		params.GameState = optionalGameState(filter.GameState)
		params.TeamID = optionalInt8(filter.TeamID)
		params.StartDate = optionalDate(filter.StartDate)
		params.EndDate = optionalDate(filter.EndDate)
		params.Limit = optionalInt4(filter.Limit)
	}
	rows, err := r.Resolver.Queries.ListGames(ctx, params)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Game, len(rows))
	for i, g := range rows {
		out[i] = convertListGamesRow(g)
	}
	return out, nil
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, season int, date string) ([]*model.StandingsEntry, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetStandingsSnapshotsBySeasonAndDate(ctx, sqlcdb.GetStandingsSnapshotsBySeasonAndDateParams{
		Season: int32(season),
		Date:   parseDate(date),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.StandingsEntry, len(rows))
	for i, s := range rows {
		out[i] = convertStandingsSnapshot(s)
	}
	return out, nil
}

// Boxscore is the resolver for the boxscore field.
func (r *queryResolver) Boxscore(ctx context.Context, gameID int64) (*model.Boxscore, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	game, err := r.Resolver.Queries.GetGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("game %d: %w", gameID, err)
	}
	skaters, err := r.Resolver.Queries.GetGameSkaterStatsByGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("skater stats for game %d: %w", gameID, err)
	}
	goalies, err := r.Resolver.Queries.GetGameGoalieStatsByGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("goalie stats for game %d: %w", gameID, err)
	}

	gqlSkaters := make([]*model.GameSkaterStats, len(skaters))
	for i, s := range skaters {
		gqlSkaters[i] = convertGameSkaterStats(s)
	}
	gqlGoalies := make([]*model.GameGoalieStats, len(goalies))
	for i, g := range goalies {
		gqlGoalies[i] = convertGameGoalieStats(g)
	}

	return &model.Boxscore{
		Game:    convertGetGameRow(game),
		Skaters: gqlSkaters,
		Goalies: gqlGoalies,
	}, nil
}

// SkaterGameLog is the resolver for the skaterGameLog field.
func (r *queryResolver) SkaterGameLog(ctx context.Context, playerID int64, season int) ([]*model.SkaterGameLogEntry, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetSkaterStatsByPlayerAndSeason(ctx, sqlcdb.GetSkaterStatsByPlayerAndSeasonParams{
		PlayerID: playerID,
		Season:   int32(season),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.SkaterGameLogEntry, len(rows))
	for i, s := range rows {
		out[i] = convertSkaterGameLogEntry(s)
	}
	return out, nil
}

// GoalieGameLog is the resolver for the goalieGameLog field.
func (r *queryResolver) GoalieGameLog(ctx context.Context, playerID int64, season int) ([]*model.GoalieGameLogEntry, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetGoalieStatsByPlayerAndSeason(ctx, sqlcdb.GetGoalieStatsByPlayerAndSeasonParams{
		PlayerID: playerID,
		Season:   int32(season),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.GoalieGameLogEntry, len(rows))
	for i, g := range rows {
		out[i] = convertGoalieGameLogEntry(g)
	}
	return out, nil
}

// PlayerSeasonTotals is the resolver for the playerSeasonTotals field.
func (r *queryResolver) PlayerSeasonTotals(ctx context.Context, playerID int64) ([]*model.PlayerSeasonTotal, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	rows, err := r.Resolver.Queries.GetPlayerSeasonTotals(ctx, playerID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PlayerSeasonTotal, len(rows))
	for i, t := range rows {
		out[i] = convertPlayerSeasonTotal(t)
	}
	return out, nil
}

// EdgeSkaterStats is the resolver for the edgeSkaterStats field.
func (r *queryResolver) EdgeSkaterStats(ctx context.Context, playerID int, season int, gameType *int) (*model.EdgeSkaterStats, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	gt := resolveGameType(gameType)
	params := sqlcdb.GetEdgeSkaterStatsParams{
		PlayerID: int64(playerID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := r.Resolver.Queries.GetEdgeSkaterStats(ctx, params)
	if err != nil {
		return nil, err
	}

	shotLocs, err := r.Resolver.Queries.GetEdgeSkaterShotLocations(ctx, sqlcdb.GetEdgeSkaterShotLocationsParams(params))
	if err != nil {
		return nil, err
	}
	sogSummary, err := r.Resolver.Queries.GetEdgeSkaterSogSummary(ctx, sqlcdb.GetEdgeSkaterSogSummaryParams(params))
	if err != nil {
		return nil, err
	}

	return convertEdgeSkaterStats(stats, shotLocs, sogSummary), nil
}

// EdgeGoalieStats is the resolver for the edgeGoalieStats field.
func (r *queryResolver) EdgeGoalieStats(ctx context.Context, playerID int, season int, gameType *int) (*model.EdgeGoalieStats, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	gt := resolveGameType(gameType)
	params := sqlcdb.GetEdgeGoalieStatsParams{
		PlayerID: int64(playerID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := r.Resolver.Queries.GetEdgeGoalieStats(ctx, params)
	if err != nil {
		return nil, err
	}

	locSummary, err := r.Resolver.Queries.GetEdgeGoalieShotLocationSummary(ctx, sqlcdb.GetEdgeGoalieShotLocationSummaryParams(params))
	if err != nil {
		return nil, err
	}
	shotLocs, err := r.Resolver.Queries.GetEdgeGoalieShotLocations(ctx, sqlcdb.GetEdgeGoalieShotLocationsParams(params))
	if err != nil {
		return nil, err
	}

	return convertEdgeGoalieStats(stats, locSummary, shotLocs), nil
}

// EdgeTeamStats is the resolver for the edgeTeamStats field.
func (r *queryResolver) EdgeTeamStats(ctx context.Context, teamID int, season int, gameType *int) (*model.EdgeTeamStats, error) {
	if r.Resolver.Queries == nil {
		return nil, errDatabaseNotConfigured
	}
	gt := resolveGameType(gameType)
	teamParams := sqlcdb.GetEdgeTeamStatsParams{
		TeamID:   int64(teamID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := r.Resolver.Queries.GetEdgeTeamStats(ctx, teamParams)
	if err != nil {
		return nil, err
	}

	sogSummary, err := r.Resolver.Queries.GetEdgeTeamSogSummary(ctx, sqlcdb.GetEdgeTeamSogSummaryParams(teamParams))
	if err != nil {
		return nil, err
	}
	shotLocs, err := r.Resolver.Queries.GetEdgeTeamShotLocations(ctx, sqlcdb.GetEdgeTeamShotLocationsParams(teamParams))
	if err != nil {
		return nil, err
	}
	zoneTime, err := r.Resolver.Queries.GetEdgeTeamZoneTimeByStrength(ctx, sqlcdb.GetEdgeTeamZoneTimeByStrengthParams(teamParams))
	if err != nil {
		return nil, err
	}
	shotDiff, err := r.Resolver.Queries.GetEdgeTeamShotDifferential(ctx, sqlcdb.GetEdgeTeamShotDifferentialParams(teamParams))
	if err != nil {
		return nil, err
	}

	return convertEdgeTeamStats(stats, sogSummary, shotLocs, zoneTime, shotDiff), nil
}

// --- Conversion functions ---

func convertSeason(s sqlcdb.Season) *model.Season {
	return &model.Season{
		ID:             int(s.ID),
		StandingsStart: dateStringPtr(s.StandingsStart),
		StandingsEnd:   dateStringPtr(s.StandingsEnd),
	}
}

func convertSeasonTeam(t sqlcdb.SeasonTeam) *model.Team {
	return &model.Team{
		TeamID:           t.TeamID,
		Season:           int(t.Season),
		FranchiseID:      int8Ptr(t.FranchiseID),
		FullName:         t.FullName,
		Abbrev:           t.Abbrev,
		LogoURL:          textPtr(t.LogoUrl),
		DivisionName:     t.DivisionName,
		DivisionAbbrev:   t.DivisionAbbrev,
		ConferenceName:   textPtr(t.ConferenceName),
		ConferenceAbbrev: textPtr(t.ConferenceAbbrev),
	}
}

func convertPlayer(p sqlcdb.Player) *model.Player {
	return &model.Player{
		ID:                 p.ID,
		FirstName:          p.FirstName,
		LastName:           p.LastName,
		TeamID:             int8Ptr(p.TeamID),
		Position:           nullPositionPtr(p.Position),
		ShootsCatches:      nullHandSidePtr(p.ShootsCatches),
		HeightInches:       int4Ptr(p.HeightInches),
		WeightPounds:       int4Ptr(p.WeightPounds),
		BirthDate:          dateStringPtr(p.BirthDate),
		BirthCity:          textPtr(p.BirthCity),
		BirthStateProvince: textPtr(p.BirthStateProvince),
		BirthCountry:       textPtr(p.BirthCountry),
		SweaterNumber:      int4Ptr(p.SweaterNumber),
		IsActive:           p.IsActive,
		HeadshotURL:        p.HeadshotURL,
		HeroImageURL:       textPtr(p.HeroImageURL),
		PlayerSlug:         textPtr(p.PlayerSlug),
		DraftYear:          int4Ptr(p.DraftYear),
		DraftTeamAbbrev:    textPtr(p.DraftTeamAbbrev),
		DraftRound:         int4Ptr(p.DraftRound),
		DraftPickInRound:   int4Ptr(p.DraftPickInRound),
		DraftOverallPick:   int4Ptr(p.DraftOverallPick),
	}
}

func convertGetGameRow(g sqlcdb.GetGameRow) *model.Game {
	return &model.Game{
		ID:                g.ID,
		Season:            int(g.Season),
		GameType:          string(g.GameType),
		GameDate:          dateString(g.GameDate),
		Venue:             g.Venue,
		VenueLocation:     g.VenueLocation,
		StartTimeUtc:      timestampPtr(g.StartTimeUTC),
		GameState:         string(g.GameState),
		GameScheduleState: string(g.GameScheduleState),
		PeriodNumber:      int(g.PeriodNumber),
		PeriodType:        string(g.PeriodType),
		HomeTeamID:        g.HomeTeamID,
		HomeTeamScore:     int(g.HomeTeamScore),
		HomeTeamSog:       int(g.HomeTeamSog),
		HomeTeamName:      g.HomeTeamName,
		HomeTeamAbbrev:    g.HomeTeamAbbrev,
		AwayTeamID:        g.AwayTeamID,
		AwayTeamScore:     int(g.AwayTeamScore),
		AwayTeamSog:       int(g.AwayTeamSog),
		AwayTeamName:      g.AwayTeamName,
		AwayTeamAbbrev:    g.AwayTeamAbbrev,
	}
}

func convertGamesByDateRow(g sqlcdb.GetGamesByDateRow) *model.Game {
	return &model.Game{
		ID:                g.ID,
		Season:            int(g.Season),
		GameType:          string(g.GameType),
		GameDate:          dateString(g.GameDate),
		Venue:             g.Venue,
		VenueLocation:     g.VenueLocation,
		StartTimeUtc:      timestampPtr(g.StartTimeUTC),
		GameState:         string(g.GameState),
		GameScheduleState: string(g.GameScheduleState),
		PeriodNumber:      int(g.PeriodNumber),
		PeriodType:        string(g.PeriodType),
		HomeTeamID:        g.HomeTeamID,
		HomeTeamScore:     int(g.HomeTeamScore),
		HomeTeamSog:       int(g.HomeTeamSog),
		HomeTeamName:      g.HomeTeamName,
		HomeTeamAbbrev:    g.HomeTeamAbbrev,
		AwayTeamID:        g.AwayTeamID,
		AwayTeamScore:     int(g.AwayTeamScore),
		AwayTeamSog:       int(g.AwayTeamSog),
		AwayTeamName:      g.AwayTeamName,
		AwayTeamAbbrev:    g.AwayTeamAbbrev,
	}
}

func convertListGamesRow(g sqlcdb.ListGamesRow) *model.Game {
	return &model.Game{
		ID:                g.ID,
		Season:            int(g.Season),
		GameType:          string(g.GameType),
		GameDate:          dateString(g.GameDate),
		Venue:             g.Venue,
		VenueLocation:     g.VenueLocation,
		StartTimeUtc:      timestampPtr(g.StartTimeUTC),
		GameState:         string(g.GameState),
		GameScheduleState: string(g.GameScheduleState),
		PeriodNumber:      int(g.PeriodNumber),
		PeriodType:        string(g.PeriodType),
		HomeTeamID:        g.HomeTeamID,
		HomeTeamScore:     int(g.HomeTeamScore),
		HomeTeamSog:       int(g.HomeTeamSog),
		HomeTeamName:      g.HomeTeamName,
		HomeTeamAbbrev:    g.HomeTeamAbbrev,
		AwayTeamID:        g.AwayTeamID,
		AwayTeamScore:     int(g.AwayTeamScore),
		AwayTeamSog:       int(g.AwayTeamSog),
		AwayTeamName:      g.AwayTeamName,
		AwayTeamAbbrev:    g.AwayTeamAbbrev,
	}
}

func convertStandingsSnapshot(s sqlcdb.StandingsSnapshot) *model.StandingsEntry {
	return &model.StandingsEntry{
		Season:           int(s.Season),
		Date:             dateString(s.Date),
		TeamID:           s.TeamID,
		TeamAbbrev:       s.TeamAbbrev,
		Wins:             int(s.Wins),
		Losses:           int(s.Losses),
		OtLosses:         int(s.OtLosses),
		Points:           int(s.Points),
		DivisionAbbrev:   s.DivisionAbbrev,
		DivisionName:     s.DivisionName,
		ConferenceAbbrev: textPtr(s.ConferenceAbbrev),
		ConferenceName:   textPtr(s.ConferenceName),
	}
}

func convertGameSkaterStats(s sqlcdb.GetGameSkaterStatsByGameRow) *model.GameSkaterStats {
	return &model.GameSkaterStats{
		GameID:             s.GameID,
		PlayerID:           s.PlayerID,
		TeamID:             s.TeamID,
		IsHome:             s.IsHome,
		SweaterNumber:      int(s.SweaterNumber),
		Position:           string(s.Position),
		FirstName:          s.FirstName,
		LastName:           s.LastName,
		TeamName:           s.TeamName,
		TeamAbbrev:         s.TeamAbbrev,
		Goals:              int(s.Goals),
		Assists:            int(s.Assists),
		Points:             int(s.Points),
		PlusMinus:          int(s.PlusMinus),
		ShotsOnGoal:        int(s.ShotsOnGoal),
		ToiSeconds:         int(s.TOISeconds),
		Shifts:             int(s.Shifts),
		FaceoffWinningPctg: float4Ptr(s.FaceoffWinningPctg),
		Hits:               int(s.Hits),
		BlockedShots:       int(s.BlockedShots),
		PenaltyMinutes:     int(s.PenaltyMinutes),
		Giveaways:          int(s.Giveaways),
		Takeaways:          int(s.Takeaways),
		PowerPlayGoals:     int(s.PowerPlayGoals),
	}
}

func convertGameGoalieStats(g sqlcdb.GetGameGoalieStatsByGameRow) *model.GameGoalieStats {
	return &model.GameGoalieStats{
		GameID:        g.GameID,
		PlayerID:      g.PlayerID,
		TeamID:        g.TeamID,
		IsHome:        g.IsHome,
		SweaterNumber: int(g.SweaterNumber),
		FirstName:     g.FirstName,
		LastName:      g.LastName,
		TeamName:      g.TeamName,
		TeamAbbrev:    g.TeamAbbrev,
		Decision:      nullGoalieDecisionPtr(g.Decision),
		Starter:       boolPtr(g.Starter),
		ShotsAgainst:  int(g.ShotsAgainst),
		Saves:         int(g.Saves),
		SavePctg:      float4Ptr(g.SavePctg),
		GoalsAgainst:  int(g.GoalsAgainst),
		ToiSeconds:    int(g.TOISeconds),
	}
}

func convertSkaterGameLogEntry(s sqlcdb.GetSkaterStatsByPlayerAndSeasonRow) *model.SkaterGameLogEntry {
	return &model.SkaterGameLogEntry{
		GameID:             s.GameID,
		GameDate:           dateString(s.GameDate),
		GameType:           string(s.GameType),
		TeamAbbrev:         s.TeamAbbrev,
		Goals:              int(s.Goals),
		Assists:            int(s.Assists),
		Points:             int(s.Points),
		PlusMinus:          int(s.PlusMinus),
		ShotsOnGoal:        int(s.ShotsOnGoal),
		ToiSeconds:         int(s.TOISeconds),
		Shifts:             int(s.Shifts),
		FaceoffWinningPctg: float4Ptr(s.FaceoffWinningPctg),
		Hits:               int(s.Hits),
		BlockedShots:       int(s.BlockedShots),
		PenaltyMinutes:     int(s.PenaltyMinutes),
		PowerPlayGoals:     int(s.PowerPlayGoals),
	}
}

func convertGoalieGameLogEntry(g sqlcdb.GetGoalieStatsByPlayerAndSeasonRow) *model.GoalieGameLogEntry {
	return &model.GoalieGameLogEntry{
		GameID:       g.GameID,
		GameDate:     dateString(g.GameDate),
		GameType:     string(g.GameType),
		TeamAbbrev:   g.TeamAbbrev,
		Decision:     nullGoalieDecisionPtr(g.Decision),
		Starter:      boolPtr(g.Starter),
		ShotsAgainst: int(g.ShotsAgainst),
		Saves:        int(g.Saves),
		SavePctg:     float4Ptr(g.SavePctg),
		GoalsAgainst: int(g.GoalsAgainst),
		ToiSeconds:   int(g.TOISeconds),
	}
}

func convertPlayerSeasonTotal(t sqlcdb.PlayerSeasonTotal) *model.PlayerSeasonTotal {
	return &model.PlayerSeasonTotal{
		PlayerID:     t.PlayerID,
		Season:       int(t.Season),
		GameType:     string(t.GameType),
		LeagueAbbrev: t.LeagueAbbrev,
		TeamName:     t.TeamName,
		TeamID:       int8Ptr(t.TeamID),
		GamesPlayed:  int(t.GamesPlayed),
		Goals:        int4Ptr(t.Goals),
		Assists:      int4Ptr(t.Assists),
		Points:       int4Ptr(t.Points),
		PlusMinus:    int4Ptr(t.PlusMinus),
		Pim:          int4Ptr(t.PIM),
	}
}

// --- Edge conversion functions ---

const defaultGameTypeInt = 2 // regular season

func resolveGameType(gameType *int) sqlcdb.GameType {
	gt := defaultGameTypeInt
	if gameType != nil {
		gt = *gameType
	}
	switch gt {
	case 1:
		return sqlcdb.GameTypePreseason
	case 2:
		return sqlcdb.GameTypeRegularSeason
	case 3:
		return sqlcdb.GameTypePlayoffs
	case 4:
		return sqlcdb.GameTypeAllStar
	default:
		return sqlcdb.GameTypeRegularSeason
	}
}

func convertEdgeSkaterStats(s sqlcdb.EdgeSkaterStat, locs []sqlcdb.EdgeSkaterShotLocation, sog []sqlcdb.EdgeSkaterSogSummary) *model.EdgeSkaterStats {
	shotLocs := make([]*model.EdgeShotLocation, len(locs))
	for i, l := range locs {
		shotLocs[i] = &model.EdgeShotLocation{
			Area:                   l.Area,
			Sog:                    int4Ptr(l.SOG),
			Goals:                  int4Ptr(l.Goals),
			ShootingPctg:           float4Ptr(l.ShootingPctg),
			SogPercentile:          float4Ptr(l.SogPercentile),
			GoalsPercentile:        float4Ptr(l.GoalsPercentile),
			ShootingPctgPercentile: float4Ptr(l.ShootingPctgPercentile),
		}
	}
	sogSummary := make([]*model.EdgeSogSummary, len(sog))
	for i, ss := range sog {
		sogSummary[i] = &model.EdgeSogSummary{
			LocationCode:           ss.LocationCode,
			Shots:                  int4Ptr(ss.Shots),
			ShotsPercentile:        float4Ptr(ss.ShotsPercentile),
			ShotsLeagueAvg:         float4Ptr(ss.ShotsLeagueAvg),
			Goals:                  int4Ptr(ss.Goals),
			GoalsPercentile:        float4Ptr(ss.GoalsPercentile),
			GoalsLeagueAvg:         float4Ptr(ss.GoalsLeagueAvg),
			ShootingPctg:           float4Ptr(ss.ShootingPctg),
			ShootingPctgPercentile: float4Ptr(ss.ShootingPctgPercentile),
			ShootingPctgLeagueAvg:  float4Ptr(ss.ShootingPctgLeagueAvg),
		}
	}
	return &model.EdgeSkaterStats{
		PlayerID:                      int(s.PlayerID),
		Season:                        int(s.Season),
		GameType:                      string(s.GameType),
		TopSpeedImperial:              float4Ptr(s.TopSpeedImperial),
		TopSpeedMetric:                float4Ptr(s.TopSpeedMetric),
		TopSpeedPercentile:            float4Ptr(s.TopSpeedPercentile),
		TopSpeedLeagueAvgImperial:     float4Ptr(s.TopSpeedLeagueAvgImperial),
		TopSpeedLeagueAvgMetric:       float4Ptr(s.TopSpeedLeagueAvgMetric),
		BurstsOver20:                  int4Ptr(s.BurstsOver20),
		BurstsOver20Percentile:        float4Ptr(s.BurstsOver20Percentile),
		BurstsOver20LeagueAvg:         float4Ptr(s.BurstsOver20LeagueAvg),
		TotalDistanceImperial:         float4Ptr(s.TotalDistanceImperial),
		TotalDistanceMetric:           float4Ptr(s.TotalDistanceMetric),
		TotalDistancePercentile:       float4Ptr(s.TotalDistancePercentile),
		MaxGameDistanceImperial:       float4Ptr(s.MaxGameDistanceImperial),
		MaxGameDistanceMetric:         float4Ptr(s.MaxGameDistanceMetric),
		MaxGameDistancePercentile:     float4Ptr(s.MaxGameDistancePercentile),
		TopShotSpeedImperial:          float4Ptr(s.TopShotSpeedImperial),
		TopShotSpeedMetric:            float4Ptr(s.TopShotSpeedMetric),
		TopShotSpeedPercentile:        float4Ptr(s.TopShotSpeedPercentile),
		TopShotSpeedLeagueAvgImperial: float4Ptr(s.TopShotSpeedLeagueAvgImperial),
		TopShotSpeedLeagueAvgMetric:   float4Ptr(s.TopShotSpeedLeagueAvgMetric),
		OzPctg:                        float4Ptr(s.OzPctg),
		OzPercentile:                  float4Ptr(s.OzPercentile),
		OzLeagueAvg:                   float4Ptr(s.OzLeagueAvg),
		NzPctg:                        float4Ptr(s.NzPctg),
		NzPercentile:                  float4Ptr(s.NzPercentile),
		NzLeagueAvg:                   float4Ptr(s.NzLeagueAvg),
		DzPctg:                        float4Ptr(s.DzPctg),
		DzPercentile:                  float4Ptr(s.DzPercentile),
		DzLeagueAvg:                   float4Ptr(s.DzLeagueAvg),
		OzEvPctg:                      float4Ptr(s.OzEvPctg),
		OzEvPercentile:                float4Ptr(s.OzEvPercentile),
		ShotLocations:                 shotLocs,
		SogSummary:                    sogSummary,
	}
}

func convertEdgeGoalieStats(s sqlcdb.EdgeGoalieStat, locSummary []sqlcdb.EdgeGoalieShotLocationSummary, locs []sqlcdb.EdgeGoalieShotLocation) *model.EdgeGoalieStats {
	shotLocSummary := make([]*model.EdgeGoalieShotLocationSummary, len(locSummary))
	for i, ls := range locSummary {
		shotLocSummary[i] = &model.EdgeGoalieShotLocationSummary{
			LocationCode:           ls.LocationCode,
			GoalsAgainst:           int4Ptr(ls.GoalsAgainst),
			GoalsAgainstPercentile: float4Ptr(ls.GoalsAgainstPercentile),
			GoalsAgainstLeagueAvg:  float4Ptr(ls.GoalsAgainstLeagueAvg),
			Saves:                  int4Ptr(ls.Saves),
			SavesPercentile:        float4Ptr(ls.SavesPercentile),
			SavesLeagueAvg:         float4Ptr(ls.SavesLeagueAvg),
			SavePctg:               float4Ptr(ls.SavePctg),
			SavePctgPercentile:     float4Ptr(ls.SavePctgPercentile),
			SavePctgLeagueAvg:      float4Ptr(ls.SavePctgLeagueAvg),
		}
	}
	shotLocs := make([]*model.EdgeGoalieShotLocation, len(locs))
	for i, l := range locs {
		shotLocs[i] = &model.EdgeGoalieShotLocation{
			Area:               l.Area,
			Saves:              int4Ptr(l.Saves),
			SavesPercentile:    float4Ptr(l.SavesPercentile),
			SavePctg:           float4Ptr(l.SavePctg),
			SavePctgPercentile: float4Ptr(l.SavePctgPercentile),
		}
	}
	return &model.EdgeGoalieStats{
		PlayerID:                 int(s.PlayerID),
		Season:                   int(s.Season),
		GameType:                 string(s.GameType),
		GaaValue:                 float4Ptr(s.GaaValue),
		GaaPercentile:            float4Ptr(s.GaaPercentile),
		GaaLeagueAvg:             float4Ptr(s.GaaLeagueAvg),
		GamesAbove900:            float4Ptr(s.GamesAbove900Value),
		GamesAbove900Percentile:  float4Ptr(s.GamesAbove900Percentile),
		GamesAbove900LeagueAvg:   float4Ptr(s.GamesAbove900LeagueAvg),
		GoalDiffPer60:            float4Ptr(s.GoalDiffPer60Value),
		GoalDiffPer60Percentile:  float4Ptr(s.GoalDiffPer60Percentile),
		GoalDiffPer60LeagueAvg:   float4Ptr(s.GoalDiffPer60LeagueAvg),
		GoalSupportAvg:           float4Ptr(s.GoalSupportAvgValue),
		GoalSupportAvgPercentile: float4Ptr(s.GoalSupportAvgPercentile),
		GoalSupportAvgLeagueAvg:  float4Ptr(s.GoalSupportAvgLeagueAvg),
		PointPctg:                float4Ptr(s.PointPctgValue),
		PointPctgPercentile:      float4Ptr(s.PointPctgPercentile),
		PointPctgLeagueAvg:       float4Ptr(s.PointPctgLeagueAvg),
		ShotLocationSummary:      shotLocSummary,
		ShotLocations:            shotLocs,
	}
}

func convertEdgeTeamStats(s sqlcdb.EdgeTeamStat, sog []sqlcdb.EdgeTeamSogSummary, locs []sqlcdb.EdgeTeamShotLocation, zt []sqlcdb.EdgeTeamZoneTimeByStrength, sd []sqlcdb.EdgeTeamShotDifferential) *model.EdgeTeamStats {
	sogSummary := make([]*model.EdgeTeamSogSummary, len(sog))
	for i, ss := range sog {
		sogSummary[i] = &model.EdgeTeamSogSummary{
			LocationCode:          ss.LocationCode,
			Shots:                 int4Ptr(ss.Shots),
			ShotsRank:             int4Ptr(ss.ShotsRank),
			ShotsLeagueAvg:        float4Ptr(ss.ShotsLeagueAvg),
			Goals:                 int4Ptr(ss.Goals),
			GoalsRank:             int4Ptr(ss.GoalsRank),
			GoalsLeagueAvg:        float4Ptr(ss.GoalsLeagueAvg),
			ShootingPctg:          float4Ptr(ss.ShootingPctg),
			ShootingPctgRank:      int4Ptr(ss.ShootingPctgRank),
			ShootingPctgLeagueAvg: float4Ptr(ss.ShootingPctgLeagueAvg),
		}
	}
	shotLocs := make([]*model.EdgeTeamShotLocation, len(locs))
	for i, l := range locs {
		shotLocs[i] = &model.EdgeTeamShotLocation{
			Area:      l.Area,
			Shots:     int4Ptr(l.Shots),
			ShotsRank: int4Ptr(l.ShotsRank),
		}
	}
	zoneTime := make([]*model.EdgeTeamZoneTimeByStrength, len(zt))
	for i, z := range zt {
		zoneTime[i] = &model.EdgeTeamZoneTimeByStrength{
			StrengthCode: z.StrengthCode,
			OzPctg:       float4Ptr(z.OzPctg),
			OzRank:       int4Ptr(z.OzRank),
			NzPctg:       float4Ptr(z.NzPctg),
			NzRank:       int4Ptr(z.NzRank),
			DzPctg:       float4Ptr(z.DzPctg),
			DzRank:       int4Ptr(z.DzRank),
		}
	}
	shotDiff := make([]*model.EdgeTeamShotDifferential, len(sd))
	for i, d := range sd {
		shotDiff[i] = &model.EdgeTeamShotDifferential{
			StrengthCode:           d.StrengthCode,
			ForPerGame:             float4Ptr(d.ForPerGame),
			ForPerGameRank:         int4Ptr(d.ForPerGameRank),
			AgainstPerGame:         float4Ptr(d.AgainstPerGame),
			AgainstPerGameRank:     int4Ptr(d.AgainstPerGameRank),
			DifferentialPerGame:     float4Ptr(d.DifferentialPerGame),
			DifferentialPerGameRank: int4Ptr(d.DifferentialPerGameRank),
		}
	}
	return &model.EdgeTeamStats{
		TeamID:                 int(s.TeamID),
		Season:                 int(s.Season),
		GameType:               string(s.GameType),
		ShotAttemptsOver90:     int4Ptr(s.ShotAttemptsOver90),
		ShotAttemptsOver90Rank: int4Ptr(s.ShotAttemptsOver90Rank),
		TopShotSpeedImperial:   float4Ptr(s.TopShotSpeedImperial),
		TopShotSpeedMetric:     float4Ptr(s.TopShotSpeedMetric),
		TopShotSpeedRank:       int4Ptr(s.TopShotSpeedRank),
		SpeedMaxImperial:       float4Ptr(s.SpeedMaxImperial),
		SpeedMaxMetric:         float4Ptr(s.SpeedMaxMetric),
		SpeedMaxRank:           int4Ptr(s.SpeedMaxRank),
		BurstsOver22:           int4Ptr(s.BurstsOver22),
		BurstsOver22Rank:       int4Ptr(s.BurstsOver22Rank),
		BurstsOver20:           int4Ptr(s.BurstsOver20),
		BurstsOver20Rank:       int4Ptr(s.BurstsOver20Rank),
		TotalDistance:          int4Ptr(s.TotalDistance),
		TotalDistanceRank:      int4Ptr(s.TotalDistanceRank),
		OzPctg:                float4Ptr(s.OzPctg),
		OzRank:                int4Ptr(s.OzRank),
		OzLeagueAvg:           float4Ptr(s.OzLeagueAvg),
		OzEvPctg:              float4Ptr(s.OzEvPctg),
		OzEvRank:              int4Ptr(s.OzEvRank),
		NzPctg:                float4Ptr(s.NzPctg),
		NzRank:                int4Ptr(s.NzRank),
		NzLeagueAvg:           float4Ptr(s.NzLeagueAvg),
		DzPctg:                float4Ptr(s.DzPctg),
		DzRank:                int4Ptr(s.DzRank),
		DzLeagueAvg:           float4Ptr(s.DzLeagueAvg),
		SogSummary:            sogSummary,
		ShotLocations:         shotLocs,
		ZoneTimeByStrength:    zoneTime,
		ShotDifferential:      shotDiff,
	}
}

// Ensure time import is used.
var _ = time.DateOnly
