package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/sperano/puckdb/graph/model"
	"github.com/sperano/puckdb/sqlcdb"
)

// Seasons is the resolver for the seasons field.
func (r *queryResolver) Seasons(ctx context.Context) ([]*model.Season, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetAllSeasons(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Season, len(rows))
	for i, s := range rows {
		out[i] = convertSeason(s)
	}
	return out, nil
}

// Season is the resolver for the season field.
func (r *queryResolver) Season(ctx context.Context, id int) (*model.Season, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	s, err := q.GetSeason(ctx, int32(id))
	if err != nil {
		return nil, err
	}
	return convertSeason(s), nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, season int) ([]*model.Team, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetSeasonTeams(ctx, int32(season))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Team, len(rows))
	for i, t := range rows {
		out[i] = convertSeasonTeam(t)
	}
	return out, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, season int, teamID int64) (*model.Team, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	t, err := q.GetSeasonTeam(ctx, sqlcdb.GetSeasonTeamParams{
		Season: int32(season),
		TeamID: teamID,
	})
	if err != nil {
		return nil, err
	}
	return convertSeasonTeam(t), nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id int64) (*model.Player, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	p, err := q.GetPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	return convertPlayer(p), nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context, filter *model.PlayerFilter) ([]*model.Player, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	var params sqlcdb.ListPlayersParams
	if filter != nil {
		params.Name = optionalText(filter.Name)
		params.TeamID = optionalInt8(filter.TeamID)
		params.Position = optionalText(filter.Position)
		params.IsActive = optionalBool(filter.IsActive)
	}
	rows, err := q.ListPlayers(ctx, params)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Player, len(rows))
	for i, p := range rows {
		out[i] = convertPlayer(p)
	}
	return out, nil
}

// SearchPlayers is the resolver for the searchPlayers field.
func (r *queryResolver) SearchPlayers(ctx context.Context, query string) ([]*model.Player, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	// Bound and sanitize the term. SearchPlayersByName wraps the argument
	// in '%'…'%' itself and caps results at LIMIT 500, so we pass the raw
	// (escaped) term — not a pre-built pattern. Escaping the LIKE
	// metacharacters stops input like "%" from wildcard-matching the whole
	// table, and the length cap bounds the scan cost. Truncate by rune so a
	// multibyte term isn't split into invalid UTF-8.
	term := strings.TrimSpace(query)
	if runes := []rune(term); len(runes) > maxSearchQueryLen {
		term = string(runes[:maxSearchQueryLen])
	}
	if term == "" {
		return []*model.Player{}, nil
	}
	rows, err := q.SearchPlayersByName(ctx, escapeLikePattern(term))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Player, len(rows))
	for i, p := range rows {
		out[i] = convertPlayer(p)
	}
	return out, nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id int64) (*model.Game, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	g, err := q.GetGame(ctx, id)
	if err != nil {
		return nil, err
	}
	return convertGetGameRow(g), nil
}

// GamesByDate is the resolver for the gamesByDate field.
func (r *queryResolver) GamesByDate(ctx context.Context, date string) ([]*model.Game, error) {
	d, err := parseDateInput("date", date)
	if err != nil {
		return nil, err
	}
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetGamesByDate(ctx, d)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Game, len(rows))
	for i, g := range rows {
		out[i] = convertGamesByDateRow(g)
	}
	return out, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, filter *model.GameFilter) ([]*model.Game, error) {
	var params sqlcdb.ListGamesParams
	if filter != nil {
		params.Season = optionalInt4(filter.Season)
		params.GameType = optionalGameType(filter.GameType)
		params.GameState = optionalGameState(filter.GameState)
		params.TeamID = optionalInt8(filter.TeamID)
		var err error
		params.StartDate, err = parseOptionalDateInput("startDate", filter.StartDate)
		if err != nil {
			return nil, err
		}
		params.EndDate, err = parseOptionalDateInput("endDate", filter.EndDate)
		if err != nil {
			return nil, err
		}
		params.Limit = optionalInt4(clampListLimit(filter.Limit))
	}
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.ListGames(ctx, params)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Game, len(rows))
	for i, g := range rows {
		out[i] = convertListGamesRow(g)
	}
	return out, nil
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, season int, date string) ([]*model.StandingsEntry, error) {
	d, err := parseDateInput("date", date)
	if err != nil {
		return nil, err
	}
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetStandingsSnapshotsBySeasonAndDate(ctx, sqlcdb.GetStandingsSnapshotsBySeasonAndDateParams{
		Season: int32(season),
		Date:   d,
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.StandingsEntry, len(rows))
	for i, s := range rows {
		out[i] = convertStandingsSnapshot(s)
	}
	return out, nil
}

// Boxscore is the resolver for the boxscore field.
func (r *queryResolver) Boxscore(ctx context.Context, gameID int64) (*model.Boxscore, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	game, err := q.GetGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("game %d: %w", gameID, err)
	}
	skaters, err := q.GetGameSkaterStatsByGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("skater stats for game %d: %w", gameID, err)
	}
	goalies, err := q.GetGameGoalieStatsByGame(ctx, gameID)
	if err != nil {
		return nil, fmt.Errorf("goalie stats for game %d: %w", gameID, err)
	}

	gqlSkaters := make([]*model.GameSkaterStats, len(skaters))
	for i, s := range skaters {
		gqlSkaters[i] = convertGameSkaterStats(s)
	}
	gqlGoalies := make([]*model.GameGoalieStats, len(goalies))
	for i, g := range goalies {
		gqlGoalies[i] = convertGameGoalieStats(g)
	}

	return &model.Boxscore{
		Game:    convertGetGameRow(game),
		Skaters: gqlSkaters,
		Goalies: gqlGoalies,
	}, nil
}

// SkaterGameLog is the resolver for the skaterGameLog field.
func (r *queryResolver) SkaterGameLog(ctx context.Context, playerID int64, season int) ([]*model.SkaterGameLogEntry, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetSkaterStatsByPlayerAndSeason(ctx, sqlcdb.GetSkaterStatsByPlayerAndSeasonParams{
		PlayerID: playerID,
		Season:   int32(season),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.SkaterGameLogEntry, len(rows))
	for i, s := range rows {
		out[i] = convertSkaterGameLogEntry(s)
	}
	return out, nil
}

// GoalieGameLog is the resolver for the goalieGameLog field.
func (r *queryResolver) GoalieGameLog(ctx context.Context, playerID int64, season int) ([]*model.GoalieGameLogEntry, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetGoalieStatsByPlayerAndSeason(ctx, sqlcdb.GetGoalieStatsByPlayerAndSeasonParams{
		PlayerID: playerID,
		Season:   int32(season),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.GoalieGameLogEntry, len(rows))
	for i, g := range rows {
		out[i] = convertGoalieGameLogEntry(g)
	}
	return out, nil
}

// PlayerSeasonTotals is the resolver for the playerSeasonTotals field.
func (r *queryResolver) PlayerSeasonTotals(ctx context.Context, playerID int64) ([]*model.PlayerSeasonTotal, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	rows, err := q.GetPlayerSeasonTotals(ctx, playerID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PlayerSeasonTotal, len(rows))
	for i, t := range rows {
		out[i] = convertPlayerSeasonTotal(t)
	}
	return out, nil
}

// EdgeSkaterStats is the resolver for the edgeSkaterStats field.
func (r *queryResolver) EdgeSkaterStats(ctx context.Context, playerID int, season int, gameType *int) (*model.EdgeSkaterStats, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	gt := resolveGameType(gameType)
	params := sqlcdb.GetEdgeSkaterStatsParams{
		PlayerID: int64(playerID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := q.GetEdgeSkaterStats(ctx, params)
	if err != nil {
		return nil, err
	}

	shotLocs, err := q.GetEdgeSkaterShotLocations(ctx, sqlcdb.GetEdgeSkaterShotLocationsParams(params))
	if err != nil {
		return nil, err
	}
	sogSummary, err := q.GetEdgeSkaterSogSummary(ctx, sqlcdb.GetEdgeSkaterSogSummaryParams(params))
	if err != nil {
		return nil, err
	}

	return convertEdgeSkaterStats(stats, shotLocs, sogSummary), nil
}

// EdgeGoalieStats is the resolver for the edgeGoalieStats field.
func (r *queryResolver) EdgeGoalieStats(ctx context.Context, playerID int, season int, gameType *int) (*model.EdgeGoalieStats, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	gt := resolveGameType(gameType)
	params := sqlcdb.GetEdgeGoalieStatsParams{
		PlayerID: int64(playerID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := q.GetEdgeGoalieStats(ctx, params)
	if err != nil {
		return nil, err
	}

	locSummary, err := q.GetEdgeGoalieShotLocationSummary(ctx, sqlcdb.GetEdgeGoalieShotLocationSummaryParams(params))
	if err != nil {
		return nil, err
	}
	shotLocs, err := q.GetEdgeGoalieShotLocations(ctx, sqlcdb.GetEdgeGoalieShotLocationsParams(params))
	if err != nil {
		return nil, err
	}

	return convertEdgeGoalieStats(stats, locSummary, shotLocs), nil
}

// EdgeTeamStats is the resolver for the edgeTeamStats field.
func (r *queryResolver) EdgeTeamStats(ctx context.Context, teamID int, season int, gameType *int) (*model.EdgeTeamStats, error) {
	q, err := r.Resolver.db()
	if err != nil {
		return nil, err
	}
	gt := resolveGameType(gameType)
	teamParams := sqlcdb.GetEdgeTeamStatsParams{
		TeamID:   int64(teamID),
		Season:   int32(season),
		GameType: gt,
	}
	stats, err := q.GetEdgeTeamStats(ctx, teamParams)
	if err != nil {
		return nil, err
	}

	sogSummary, err := q.GetEdgeTeamSogSummary(ctx, sqlcdb.GetEdgeTeamSogSummaryParams(teamParams))
	if err != nil {
		return nil, err
	}
	shotLocs, err := q.GetEdgeTeamShotLocations(ctx, sqlcdb.GetEdgeTeamShotLocationsParams(teamParams))
	if err != nil {
		return nil, err
	}
	zoneTime, err := q.GetEdgeTeamZoneTimeByStrength(ctx, sqlcdb.GetEdgeTeamZoneTimeByStrengthParams(teamParams))
	if err != nil {
		return nil, err
	}
	shotDiff, err := q.GetEdgeTeamShotDifferential(ctx, sqlcdb.GetEdgeTeamShotDifferentialParams(teamParams))
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, err
	}
	var shotDiffPtr *sqlcdb.EdgeTeamShotDifferential
	if err == nil {
		shotDiffPtr = &shotDiff
	}

	return convertEdgeTeamStats(stats, sogSummary, shotLocs, zoneTime, shotDiffPtr), nil
}
