package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"strconv"

	"github.com/sperano/puckdb/config"
	"github.com/sperano/puckdb/database"
	"github.com/sperano/puckdb/graph/generated"
	"github.com/sperano/puckdb/graph/model"
)

// ClearDatabase is the resolver for the clearDatabase field.
func (r *mutationResolver) ClearDatabase(ctx context.Context) (bool, error) {
	return clearDatabase(ctx)
}

// DropDatabase is the resolver for the dropDatabase field.
func (r *mutationResolver) DropDatabase(ctx context.Context) (bool, error) {
	return dropDatabase(ctx)
}

// CreateDatabase is the resolver for the createDatabase field.
func (r *mutationResolver) CreateDatabase(ctx context.Context) (bool, error) {
	return createDatabase(ctx)
}

// InitDatabase is the resolver for the initDatabase field.
func (r *mutationResolver) InitDatabase(ctx context.Context) (bool, error) {
	return initDatabase(ctx)
}

// ClearCache is the resolver for the clearCache field.
func (r *mutationResolver) ClearCache(ctx context.Context) (bool, error) {
	return clearCache(ctx)
}

// ImportEverything is the resolver for the importEverything field.
func (r *mutationResolver) ImportEverything(ctx context.Context) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelImportEverything is the resolver for the cancelImportEverything field.
func (r *mutationResolver) CancelImportEverything(ctx context.Context) (bool, error) {
	return r.Resolver.cancelImportEverything(ctx)
}

// ImportEverythingForSeason is the resolver for the importEverythingForSeason field.
func (r *mutationResolver) ImportEverythingForSeason(ctx context.Context, season int) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelImportEverythingForSeason is the resolver for the cancelImportEverythingForSeason field.
func (r *mutationResolver) CancelImportEverythingForSeason(ctx context.Context, season int) (bool, error) {
	return r.Resolver.cancelImportEverythingForSeason(ctx, season)
}

// DownloadEverything is the resolver for the downloadEverything field.
func (r *mutationResolver) DownloadEverything(ctx context.Context) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelDownloadEverything is the resolver for the cancelDownloadEverything field.
func (r *mutationResolver) CancelDownloadEverything(ctx context.Context) (bool, error) {
	return r.Resolver.cancelDownloadEverything(ctx)
}

// DownloadEverythingForSeason is the resolver for the downloadEverythingForSeason field.
func (r *mutationResolver) DownloadEverythingForSeason(ctx context.Context, season int) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelDownloadEverythingForSeason is the resolver for the cancelDownloadEverythingForSeason field.
func (r *mutationResolver) CancelDownloadEverythingForSeason(ctx context.Context, season int) (bool, error) {
	return r.Resolver.cancelDownloadEverythingForSeason(ctx, season)
}

// ImportGamesForSeason is the resolver for the importGamesForSeason field.
func (r *mutationResolver) ImportGamesForSeason(ctx context.Context, season int) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelImportGamesForSeason is the resolver for the cancelImportGamesForSeason field.
func (r *mutationResolver) CancelImportGamesForSeason(ctx context.Context, season int) (bool, error) {
	return r.Resolver.cancelImportGamesForSeason(ctx, season)
}

// ImportGamesForDay is the resolver for the importGamesForDay field.
func (r *mutationResolver) ImportGamesForDay(ctx context.Context, year int, month int, day int) (bool, error) {
	return r.Resolver.importGamesForDay(ctx, year, month, day)
}

// CancelImportGamesForDay is the resolver for the cancelImportGamesForDay field.
func (r *mutationResolver) CancelImportGamesForDay(ctx context.Context, year int, month int, day int) (bool, error) {
	return r.Resolver.cancelImportGamesForDay(ctx, year, month, day)
}

// ImportLeague is the resolver for the importLeague field.
func (r *mutationResolver) ImportLeague(ctx context.Context, season int, leagueID int) (*model.League, error) {
	return nil, fmt.Errorf("not implemented")
}

// ImportTeam is the resolver for the importTeam field.
func (r *mutationResolver) ImportTeam(ctx context.Context, season int, leagueID int, teamID int) (*model.Team, error) {
	return nil, fmt.Errorf("not implemented")
}

// ExtractUniquePlayers is the resolver for the extractUniquePlayers field.
func (r *mutationResolver) ExtractUniquePlayers(ctx context.Context) (bool, error) {
	return false, fmt.Errorf("not implemented")
}

// CancelExtractUniquePlayers is the resolver for the cancelExtractUniquePlayers field.
func (r *mutationResolver) CancelExtractUniquePlayers(ctx context.Context) (bool, error) {
	return r.Resolver.cancelExtractUniquePlayers(ctx)
}

// DownloadAll is the resolver for the downloadAll field.
func (r *mutationResolver) DownloadAll(ctx context.Context, input *model.DownloadAllInput) (bool, error) {
	return r.Resolver.downloadAll(ctx, input)
}

// CancelDownloadAll is the resolver for the cancelDownloadAll field.
func (r *mutationResolver) CancelDownloadAll(ctx context.Context) (bool, error) {
	return r.Resolver.cancelDownloadAll(ctx)
}

// Divisions is the resolver for the divisions field.
func (r *nHLConferenceResolver) Divisions(ctx context.Context, obj *model.NHLConference) ([]*model.NHLDivision, error) {
	return divisions(ctx, obj)
}

// Teams is the resolver for the teams field.
func (r *nHLDivisionResolver) Teams(ctx context.Context, obj *model.NHLDivision) ([]*model.NHLTeam, error) {
	return teams(ctx, obj)
}

// BuildNumber is the resolver for the buildNumber field.
func (r *queryResolver) BuildNumber(ctx context.Context) (int, error) {
	_ = ctx
	if config.BuildNumber == "n/a" { // not always true
		return 0, nil
	}
	return strconv.Atoi(config.BuildNumber)
}

// NhlConferences is the resolver for the nhlConferences field.
func (r *queryResolver) NhlConferences(ctx context.Context) ([]*model.NHLConference, error) {
	return nhlConferences(ctx, database.QueriesFromContext(ctx))
}

// NhlDivisions is the resolver for the nhlDivisions field.
func (r *queryResolver) NhlDivisions(ctx context.Context) ([]*model.NHLDivision, error) {
	return nhlDivisions(ctx, database.QueriesFromContext(ctx))
}

// NhlTeams is the resolver for the nhlTeams field.
func (r *queryResolver) NhlTeams(ctx context.Context, allstars bool) ([]*model.NHLTeam, error) {
	return nhlTeams(ctx, database.QueriesFromContext(ctx), allstars)
}

// NhlTeam is the resolver for the nhlTeam field.
func (r *queryResolver) NhlTeam(ctx context.Context, teamID int) (*model.NHLTeam, error) {
	return nhlTeam(ctx, database.QueriesFromContext(ctx), teamID)
}

// CurrentFantasyGameKey is the resolver for the currentFantasyGameKey field.
func (r *queryResolver) CurrentFantasyGameKey(ctx context.Context) (int, error) {
	return currentFantasyGameKey(ctx)
}

// Seasons is the resolver for the seasons field.
func (r *queryResolver) Seasons(ctx context.Context) ([]*model.Season, error) {
	return nil, fmt.Errorf("not implemented")
}

// League is the resolver for the league field.
func (r *queryResolver) League(ctx context.Context, season int, id int) (*model.League, error) {
	return league(ctx, season, id)
}

// DownloadEverythingResult is the resolver for the downloadEverythingResult field.
func (r *queryResolver) DownloadEverythingResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.downloadEverythingResult(ctx)
}

// DownloadEverythingForSeasonResult is the resolver for the downloadEverythingForSeasonResult field.
func (r *queryResolver) DownloadEverythingForSeasonResult(ctx context.Context, season int) (*model.WorkflowResult, error) {
	return r.Resolver.downloadEverythingForSeasonResult(ctx, season)
}

// DownloadEverythingProgress is the resolver for the downloadEverythingProgress field.
func (r *queryResolver) DownloadEverythingProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadEverythingProgress(ctx)
}

// DownloadEverythingForSeasonProgress is the resolver for the downloadEverythingForSeasonProgress field.
func (r *queryResolver) DownloadEverythingForSeasonProgress(ctx context.Context, season int) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadEverythingForSeasonProgress(ctx, season)
}

// ExtractUniquePlayersResult is the resolver for the extractUniquePlayersResult field.
func (r *queryResolver) ExtractUniquePlayersResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.extractUniquePlayersResult(ctx)
}

// ExtractUniquePlayersProgress is the resolver for the extractUniquePlayersProgress field.
func (r *queryResolver) ExtractUniquePlayersProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.extractUniquePlayersProgress(ctx)
}

// DownloadAllResult is the resolver for the downloadAllResult field.
func (r *queryResolver) DownloadAllResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.downloadAllResult(ctx)
}

// DownloadAllProgress is the resolver for the downloadAllProgress field.
func (r *queryResolver) DownloadAllProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadAllProgress(ctx)
}

// Leagues is the resolver for the leagues field.
func (r *seasonResolver) Leagues(ctx context.Context, obj *model.Season) ([]*model.League, error) {
	return nil, fmt.Errorf("not implemented")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// NHLConference returns generated.NHLConferenceResolver implementation.
func (r *Resolver) NHLConference() generated.NHLConferenceResolver { return &nHLConferenceResolver{r} }

// NHLDivision returns generated.NHLDivisionResolver implementation.
func (r *Resolver) NHLDivision() generated.NHLDivisionResolver { return &nHLDivisionResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Season returns generated.SeasonResolver implementation.
func (r *Resolver) Season() generated.SeasonResolver { return &seasonResolver{r} }

type mutationResolver struct{ *Resolver }
type nHLConferenceResolver struct{ *Resolver }
type nHLDivisionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type seasonResolver struct{ *Resolver }
