package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"strconv"

	"github.com/sperano/puckdb/config"
	"github.com/sperano/puckdb/database"
	"github.com/sperano/puckdb/graph/generated"
	"github.com/sperano/puckdb/graph/model"
)

// ClearDatabase is the resolver for the clearDatabase field.
func (r *mutationResolver) ClearDatabase(ctx context.Context) (bool, error) {
	return clearDatabase(ctx)
}

// DropDatabase is the resolver for the dropDatabase field.
func (r *mutationResolver) DropDatabase(ctx context.Context) (bool, error) {
	return dropDatabase(ctx)
}

// CreateDatabase is the resolver for the createDatabase field.
func (r *mutationResolver) CreateDatabase(ctx context.Context) (bool, error) {
	return createDatabase(ctx)
}

// InitDatabase is the resolver for the initDatabase field.
func (r *mutationResolver) InitDatabase(ctx context.Context) (bool, error) {
	return initDatabase(ctx)
}

// FlushRedisDb is the resolver for the flushRedisDB field.
func (r *mutationResolver) FlushRedisDb(ctx context.Context) (bool, error) {
	return flushRedisDB(ctx)
}

// DownloadSeasons is the resolver for the downloadSeasons field.
func (r *mutationResolver) DownloadSeasons(ctx context.Context, input *model.DownloadSeasonsInput) (bool, error) {
	return r.Resolver.downloadSeasons(ctx, input)
}

// CancelDownloadSeasons is the resolver for the cancelDownloadSeasons field.
func (r *mutationResolver) CancelDownloadSeasons(ctx context.Context) (bool, error) {
	return r.Resolver.cancelDownloadSeasons(ctx)
}

// DownloadDay is the resolver for the downloadDay field.
func (r *mutationResolver) DownloadDay(ctx context.Context, input model.DownloadDayInput) (bool, error) {
	return r.Resolver.downloadDay(ctx, input)
}

// DownloadYahooPlayers is the resolver for the downloadYahooPlayers field.
func (r *mutationResolver) DownloadYahooPlayers(ctx context.Context) (bool, error) {
	return r.Resolver.downloadYahooPlayers(ctx)
}

// CancelDownloadYahooPlayers is the resolver for the cancelDownloadYahooPlayers field.
func (r *mutationResolver) CancelDownloadYahooPlayers(ctx context.Context) (bool, error) {
	return r.Resolver.cancelDownloadYahooPlayers(ctx)
}

// DownloadPlayers is the resolver for the downloadPlayers field.
func (r *mutationResolver) DownloadPlayers(ctx context.Context, input *model.DownloadSeasonsInput) (bool, error) {
	return r.Resolver.downloadPlayers(ctx, input)
}

// CancelDownloadPlayers is the resolver for the cancelDownloadPlayers field.
func (r *mutationResolver) CancelDownloadPlayers(ctx context.Context) (bool, error) {
	return r.Resolver.cancelDownloadPlayers(ctx)
}

// ImportPlayers is the resolver for the importPlayers field.
func (r *mutationResolver) ImportPlayers(ctx context.Context, input *model.DownloadSeasonsInput) (bool, error) {
	return r.Resolver.importPlayers(ctx, input)
}

// CancelImportPlayers is the resolver for the cancelImportPlayers field.
func (r *mutationResolver) CancelImportPlayers(ctx context.Context) (bool, error) {
	return r.Resolver.cancelImportPlayers(ctx)
}

// ImportSeasons is the resolver for the importSeasons field.
func (r *mutationResolver) ImportSeasons(ctx context.Context, input *model.DownloadSeasonsInput) (bool, error) {
	return r.Resolver.importSeasons(ctx, input)
}

// CancelImportSeasons is the resolver for the cancelImportSeasons field.
func (r *mutationResolver) CancelImportSeasons(ctx context.Context) (bool, error) {
	return r.Resolver.cancelImportSeasons(ctx)
}

// ImportLeague is the resolver for the importLeague field.
func (r *mutationResolver) ImportLeague(ctx context.Context, season int, leagueID int) (*model.League, error) {
	return nil, fmt.Errorf("not implemented")
}

// ImportTeam is the resolver for the importTeam field.
func (r *mutationResolver) ImportTeam(ctx context.Context, season int, leagueID int, teamID int) (*model.Team, error) {
	return nil, fmt.Errorf("not implemented")
}

// Divisions is the resolver for the divisions field.
func (r *nHLConferenceResolver) Divisions(ctx context.Context, obj *model.NHLConference) ([]*model.NHLDivision, error) {
	return divisions(ctx, obj)
}

// Teams is the resolver for the teams field.
func (r *nHLDivisionResolver) Teams(ctx context.Context, obj *model.NHLDivision) ([]*model.NHLTeam, error) {
	return teams(ctx, obj)
}

// BuildNumber is the resolver for the buildNumber field.
func (r *queryResolver) BuildNumber(ctx context.Context) (int, error) {
	_ = ctx
	if config.BuildNumber == "n/a" { // not always true
		return 0, nil
	}
	return strconv.Atoi(config.BuildNumber)
}

// NhlConferences is the resolver for the nhlConferences field.
func (r *queryResolver) NhlConferences(ctx context.Context) ([]*model.NHLConference, error) {
	return nhlConferences(ctx, database.QueriesFromContext(ctx))
}

// NhlDivisions is the resolver for the nhlDivisions field.
func (r *queryResolver) NhlDivisions(ctx context.Context) ([]*model.NHLDivision, error) {
	return nhlDivisions(ctx, database.QueriesFromContext(ctx))
}

// NhlTeams is the resolver for the nhlTeams field.
func (r *queryResolver) NhlTeams(ctx context.Context, allstars bool) ([]*model.NHLTeam, error) {
	return nhlTeams(ctx, database.QueriesFromContext(ctx), allstars)
}

// NhlTeam is the resolver for the nhlTeam field.
func (r *queryResolver) NhlTeam(ctx context.Context, teamID int) (*model.NHLTeam, error) {
	return nhlTeam(ctx, database.QueriesFromContext(ctx), teamID)
}

// CurrentFantasyGameKey is the resolver for the currentFantasyGameKey field.
func (r *queryResolver) CurrentFantasyGameKey(ctx context.Context) (int, error) {
	return currentFantasyGameKey(ctx)
}

// DownloadSeasonsResult is the resolver for the downloadSeasonsResult field.
func (r *queryResolver) DownloadSeasonsResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.downloadSeasonsResult(ctx)
}

// DownloadSeasonsProgress is the resolver for the downloadSeasonsProgress field.
func (r *queryResolver) DownloadSeasonsProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadSeasonsProgress(ctx)
}

// DownloadYahooPlayersResult is the resolver for the downloadYahooPlayersResult field.
func (r *queryResolver) DownloadYahooPlayersResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.downloadYahooPlayersResult(ctx)
}

// DownloadYahooPlayersProgress is the resolver for the downloadYahooPlayersProgress field.
func (r *queryResolver) DownloadYahooPlayersProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadYahooPlayersProgress(ctx)
}

// DownloadPlayersResult is the resolver for the downloadPlayersResult field.
func (r *queryResolver) DownloadPlayersResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.downloadPlayersResult(ctx)
}

// DownloadPlayersProgress is the resolver for the downloadPlayersProgress field.
func (r *queryResolver) DownloadPlayersProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.downloadPlayersProgress(ctx)
}

// ImportPlayersResult is the resolver for the importPlayersResult field.
func (r *queryResolver) ImportPlayersResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.importPlayersResult(ctx)
}

// ImportPlayersProgress is the resolver for the importPlayersProgress field.
func (r *queryResolver) ImportPlayersProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.importPlayersProgress(ctx)
}

// ImportPlayersResultData is the resolver for the importPlayersResultData field.
func (r *queryResolver) ImportPlayersResultData(ctx context.Context) (*model.ImportPlayersResultData, error) {
	return r.Resolver.importPlayersResultData(ctx)
}

// ImportSeasonsResult is the resolver for the importSeasonsResult field.
func (r *queryResolver) ImportSeasonsResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.importSeasonsResult(ctx)
}

// ImportSeasonsProgress is the resolver for the importSeasonsProgress field.
func (r *queryResolver) ImportSeasonsProgress(ctx context.Context) (*model.WorkflowProgress, error) {
	return r.Resolver.importSeasonsProgress(ctx)
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context, filter *model.PlayersFilter) ([]*model.Player, error) {
	return listPlayers(ctx, database.QueriesFromContext(ctx), filter)
}

// Leagues is the resolver for the leagues field.
func (r *seasonResolver) Leagues(ctx context.Context, obj *model.Season) ([]*model.League, error) {
	return nil, fmt.Errorf("not implemented")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// NHLConference returns generated.NHLConferenceResolver implementation.
func (r *Resolver) NHLConference() generated.NHLConferenceResolver { return &nHLConferenceResolver{r} }

// NHLDivision returns generated.NHLDivisionResolver implementation.
func (r *Resolver) NHLDivision() generated.NHLDivisionResolver { return &nHLDivisionResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Season returns generated.SeasonResolver implementation.
func (r *Resolver) Season() generated.SeasonResolver { return &seasonResolver{r} }

type mutationResolver struct{ *Resolver }
type nHLConferenceResolver struct{ *Resolver }
type nHLDivisionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type seasonResolver struct{ *Resolver }
