-- Consolidated down migration: drops everything 000001_init.up.sql creates.

-- Views first (they depend on tables).
DROP VIEW IF EXISTS goalie_recent_stats;
DROP VIEW IF EXISTS goalie_season_stats;
DROP VIEW IF EXISTS skater_recent_stats;
DROP VIEW IF EXISTS skater_season_stats;
DROP VIEW IF EXISTS yahoo_roster_players;
DROP VIEW IF EXISTS yahoo_roto_standings;
DROP VIEW IF EXISTS yahoo_season_team_totals;

-- Tables (CASCADE resolves FK ordering).
DROP TABLE IF EXISTS club_goalie_stats CASCADE;
DROP TABLE IF EXISTS club_skater_stats CASCADE;
DROP TABLE IF EXISTS edge_goalie_shot_location_summary CASCADE;
DROP TABLE IF EXISTS edge_goalie_shot_locations CASCADE;
DROP TABLE IF EXISTS edge_goalie_stats CASCADE;
DROP TABLE IF EXISTS edge_skater_shot_locations CASCADE;
DROP TABLE IF EXISTS edge_skater_sog_summary CASCADE;
DROP TABLE IF EXISTS edge_skater_stats CASCADE;
DROP TABLE IF EXISTS edge_team_shot_differential CASCADE;
DROP TABLE IF EXISTS edge_team_shot_locations CASCADE;
DROP TABLE IF EXISTS edge_team_sog_summary CASCADE;
DROP TABLE IF EXISTS edge_team_stats CASCADE;
DROP TABLE IF EXISTS edge_team_zone_time_by_strength CASCADE;
DROP TABLE IF EXISTS franchises CASCADE;
DROP TABLE IF EXISTS game_broadcasts CASCADE;
DROP TABLE IF EXISTS game_coaches CASCADE;
DROP TABLE IF EXISTS game_goalie_stats CASCADE;
DROP TABLE IF EXISTS game_officials CASCADE;
DROP TABLE IF EXISTS game_scratches CASCADE;
DROP TABLE IF EXISTS game_skater_stats CASCADE;
DROP TABLE IF EXISTS game_three_stars CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS goal_highlights CASCADE;
DROP TABLE IF EXISTS maurice_conversations CASCADE;
DROP TABLE IF EXISTS maurice_messages CASCADE;
DROP TABLE IF EXISTS play_events CASCADE;
DROP TABLE IF EXISTS player_awards CASCADE;
DROP TABLE IF EXISTS player_season_totals CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS season_rosters CASCADE;
DROP TABLE IF EXISTS season_teams CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS shifts CASCADE;
DROP TABLE IF EXISTS shootout_attempts CASCADE;
DROP TABLE IF EXISTS sim_agent_daily_player_stats CASCADE;
DROP TABLE IF EXISTS sim_agent_daily_stats CASCADE;
DROP TABLE IF EXISTS sim_agent_tool_calls CASCADE;
DROP TABLE IF EXISTS sim_agent_totals CASCADE;
DROP TABLE IF EXISTS sim_agent_turn_messages CASCADE;
DROP TABLE IF EXISTS sim_agent_turn_rounds CASCADE;
DROP TABLE IF EXISTS sim_agent_turns CASCADE;
DROP TABLE IF EXISTS sim_agents CASCADE;
DROP TABLE IF EXISTS sim_lineup_moves CASCADE;
DROP TABLE IF EXISTS sim_pools CASCADE;
DROP TABLE IF EXISTS sim_rosters CASCADE;
DROP TABLE IF EXISTS sim_standings CASCADE;
DROP TABLE IF EXISTS sim_transactions CASCADE;
DROP TABLE IF EXISTS sim_waiver_claims CASCADE;
DROP TABLE IF EXISTS sim_waiver_priority CASCADE;
DROP TABLE IF EXISTS standings_snapshots CASCADE;
DROP TABLE IF EXISTS yahoo_draft_results CASCADE;
DROP TABLE IF EXISTS yahoo_league_roster_positions CASCADE;
DROP TABLE IF EXISTS yahoo_league_stat_categories CASCADE;
DROP TABLE IF EXISTS yahoo_leagues CASCADE;
DROP TABLE IF EXISTS yahoo_matchups CASCADE;
DROP TABLE IF EXISTS yahoo_team_managers CASCADE;
DROP TABLE IF EXISTS yahoo_team_rosters CASCADE;
DROP TABLE IF EXISTS yahoo_team_summaries CASCADE;
DROP TABLE IF EXISTS yahoo_teams CASCADE;
DROP TABLE IF EXISTS yahoo_transaction_players CASCADE;
DROP TABLE IF EXISTS yahoo_transactions CASCADE;

-- Enum types.
DROP TYPE IF EXISTS chat_role;
DROP TYPE IF EXISTS game_schedule_state;
DROP TYPE IF EXISTS game_state;
DROP TYPE IF EXISTS game_type;
DROP TYPE IF EXISTS goalie_decision;
DROP TYPE IF EXISTS hand_side;
DROP TYPE IF EXISTS ice_side;
DROP TYPE IF EXISTS official_role;
DROP TYPE IF EXISTS period_type;
DROP TYPE IF EXISTS play_event_type;
DROP TYPE IF EXISTS player_position;
DROP TYPE IF EXISTS shift_detail;
DROP TYPE IF EXISTS shift_type;
DROP TYPE IF EXISTS shootout_result;
DROP TYPE IF EXISTS team_kind_enum;
DROP TYPE IF EXISTS zone_code;
