// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type FetchPlayerLandingsInput struct {
	BatchSize   *int `json:"batchSize,omitempty"`
	Concurrency *int `json:"concurrency,omitempty"`
}

type Mutation struct {
}

type ProcessPlayersInput struct {
	BatchSize   *int `json:"batchSize,omitempty"`
	Concurrency *int `json:"concurrency,omitempty"`
}

type ProcessPlayersResultData struct {
	TotalPlayers          int                     `json:"totalPlayers"`
	ImportedPlayers       int                     `json:"importedPlayers"`
	MatchedWithYahoo      int                     `json:"matchedWithYahoo"`
	Downloaded            int                     `json:"downloaded"`
	CacheHits             int                     `json:"cacheHits"`
	Missing               int                     `json:"missing"`
	TotalYahooPlayers     int                     `json:"totalYahooPlayers"`
	SkippedNonNHL         int                     `json:"skippedNonNHL"`
	VerifiedNonNHLThisRun int                     `json:"verifiedNonNHLThisRun"`
	TrulyUnmatched        []*TrulyUnmatchedPlayer `json:"trulyUnmatched"`
	Errors                []string                `json:"errors"`
}

type ProgressBar struct {
	Label   *string `json:"label,omitempty"`
	Current int     `json:"current"`
	Total   int     `json:"total"`
	Started bool    `json:"started"`
}

type ProgressGroup struct {
	Header       string         `json:"header"`
	CompletedMsg string         `json:"completedMsg"`
	Bars         []*ProgressBar `json:"bars"`
	StartedAt    int64          `json:"startedAt"`
	CompletedAt  int64          `json:"completedAt"`
}

type ProgressReport struct {
	Total     int              `json:"total"`
	Completed int              `json:"completed"`
	Message   *string          `json:"message,omitempty"`
	Groups    []*ProgressGroup `json:"groups"`
}

type Query struct {
}

type SeasonsInput struct {
	// Season start year (e.g., 2023 for the 2023-2024 season)
	StartSeason *int `json:"startSeason,omitempty"`
	// Season start year to filter up to (inclusive)
	EndSeason         *int `json:"endSeason,omitempty"`
	SeasonConcurrency *int `json:"seasonConcurrency,omitempty"`
}

type TrulyUnmatchedPlayer struct {
	YahooID     int    `json:"yahooID"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	NhlGames    int    `json:"nhlGames"`
	NhlPlayerID int    `json:"nhlPlayerID"`
	NhlName     string `json:"nhlName"`
}

type WorkflowResult struct {
	Status        TemporalWorkflowStatus `json:"status"`
	FailureReason *string                `json:"failureReason,omitempty"`
}

type TemporalWorkflowStatus string

const (
	TemporalWorkflowStatusUnspecified    TemporalWorkflowStatus = "UNSPECIFIED"
	TemporalWorkflowStatusRunning        TemporalWorkflowStatus = "RUNNING"
	TemporalWorkflowStatusCompleted      TemporalWorkflowStatus = "COMPLETED"
	TemporalWorkflowStatusFailed         TemporalWorkflowStatus = "FAILED"
	TemporalWorkflowStatusCanceled       TemporalWorkflowStatus = "CANCELED"
	TemporalWorkflowStatusTerminated     TemporalWorkflowStatus = "TERMINATED"
	TemporalWorkflowStatusContinuedAsNew TemporalWorkflowStatus = "CONTINUED_AS_NEW"
	TemporalWorkflowStatusTimedOut       TemporalWorkflowStatus = "TIMED_OUT"
)

var AllTemporalWorkflowStatus = []TemporalWorkflowStatus{
	TemporalWorkflowStatusUnspecified,
	TemporalWorkflowStatusRunning,
	TemporalWorkflowStatusCompleted,
	TemporalWorkflowStatusFailed,
	TemporalWorkflowStatusCanceled,
	TemporalWorkflowStatusTerminated,
	TemporalWorkflowStatusContinuedAsNew,
	TemporalWorkflowStatusTimedOut,
}

func (e TemporalWorkflowStatus) IsValid() bool {
	switch e {
	case TemporalWorkflowStatusUnspecified, TemporalWorkflowStatusRunning, TemporalWorkflowStatusCompleted, TemporalWorkflowStatusFailed, TemporalWorkflowStatusCanceled, TemporalWorkflowStatusTerminated, TemporalWorkflowStatusContinuedAsNew, TemporalWorkflowStatusTimedOut:
		return true
	}
	return false
}

func (e TemporalWorkflowStatus) String() string {
	return string(e)
}

func (e *TemporalWorkflowStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemporalWorkflowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemporalWorkflowStatus", str)
	}
	return nil
}

func (e TemporalWorkflowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
