// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlcdb

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertGameGoalieStatsBatch = `-- name: UpsertGameGoalieStatsBatch :batchexec
INSERT INTO game_goalie_stats (
    game_id, player_id, team_id, is_home, sweater_number,
    decision, starter,
    shots_against, saves, save_pctg,
    goals_against, even_strength_goals_against, power_play_goals_against, shorthanded_goals_against,
    toi_seconds, penalty_minutes,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16,
    NOW()
)
ON CONFLICT (game_id, player_id) DO UPDATE SET
    team_id = EXCLUDED.team_id,
    is_home = EXCLUDED.is_home,
    sweater_number = EXCLUDED.sweater_number,
    decision = EXCLUDED.decision,
    starter = EXCLUDED.starter,
    shots_against = EXCLUDED.shots_against,
    saves = EXCLUDED.saves,
    save_pctg = EXCLUDED.save_pctg,
    goals_against = EXCLUDED.goals_against,
    even_strength_goals_against = EXCLUDED.even_strength_goals_against,
    power_play_goals_against = EXCLUDED.power_play_goals_against,
    shorthanded_goals_against = EXCLUDED.shorthanded_goals_against,
    toi_seconds = EXCLUDED.toi_seconds,
    penalty_minutes = EXCLUDED.penalty_minutes,
    updated_at = NOW()
WHERE (game_goalie_stats.team_id, game_goalie_stats.is_home,
       game_goalie_stats.sweater_number,
       game_goalie_stats.decision, game_goalie_stats.starter,
       game_goalie_stats.shots_against, game_goalie_stats.saves,
       game_goalie_stats.save_pctg, game_goalie_stats.goals_against,
       game_goalie_stats.even_strength_goals_against,
       game_goalie_stats.power_play_goals_against,
       game_goalie_stats.shorthanded_goals_against,
       game_goalie_stats.toi_seconds, game_goalie_stats.penalty_minutes)
      IS DISTINCT FROM
      (EXCLUDED.team_id, EXCLUDED.is_home,
       EXCLUDED.sweater_number,
       EXCLUDED.decision, EXCLUDED.starter,
       EXCLUDED.shots_against, EXCLUDED.saves,
       EXCLUDED.save_pctg, EXCLUDED.goals_against,
       EXCLUDED.even_strength_goals_against,
       EXCLUDED.power_play_goals_against,
       EXCLUDED.shorthanded_goals_against,
       EXCLUDED.toi_seconds, EXCLUDED.penalty_minutes)
`

type UpsertGameGoalieStatsBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertGameGoalieStatsBatchParams struct {
	GameID                   int64         `json:"game_id"`
	PlayerID                 int64         `json:"player_id"`
	TeamID                   int64         `json:"team_id"`
	IsHome                   bool          `json:"is_home"`
	SweaterNumber            int16         `json:"sweater_number"`
	Decision                 pgtype.Text   `json:"decision"`
	Starter                  pgtype.Bool   `json:"starter"`
	ShotsAgainst             int32         `json:"shots_against"`
	Saves                    int32         `json:"saves"`
	SavePctg                 pgtype.Float4 `json:"save_pctg"`
	GoalsAgainst             int16         `json:"goals_against"`
	EvenStrengthGoalsAgainst int16         `json:"even_strength_goals_against"`
	PowerPlayGoalsAgainst    int16         `json:"power_play_goals_against"`
	ShorthandedGoalsAgainst  int16         `json:"shorthanded_goals_against"`
	TOISeconds               int32         `json:"toi_seconds"`
	PenaltyMinutes           pgtype.Int2   `json:"penalty_minutes"`
}

func (q *Queries) UpsertGameGoalieStatsBatch(ctx context.Context, arg []UpsertGameGoalieStatsBatchParams) *UpsertGameGoalieStatsBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GameID,
			a.PlayerID,
			a.TeamID,
			a.IsHome,
			a.SweaterNumber,
			a.Decision,
			a.Starter,
			a.ShotsAgainst,
			a.Saves,
			a.SavePctg,
			a.GoalsAgainst,
			a.EvenStrengthGoalsAgainst,
			a.PowerPlayGoalsAgainst,
			a.ShorthandedGoalsAgainst,
			a.TOISeconds,
			a.PenaltyMinutes,
		}
		batch.Queue(upsertGameGoalieStatsBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertGameGoalieStatsBatchBatchResults{br, len(arg), false}
}

func (b *UpsertGameGoalieStatsBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertGameGoalieStatsBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertGameSkaterStatsBatch = `-- name: UpsertGameSkaterStatsBatch :batchexec
INSERT INTO game_skater_stats (
    game_id, player_id, team_id, is_home, sweater_number, position,
    goals, assists, points, plus_minus, shots_on_goal,
    toi_seconds, shifts, faceoff_winning_pctg,
    hits, blocked_shots, penalty_minutes,
    giveaways, takeaways, power_play_goals,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    NOW()
)
ON CONFLICT (game_id, player_id) DO UPDATE SET
    team_id = EXCLUDED.team_id,
    is_home = EXCLUDED.is_home,
    sweater_number = EXCLUDED.sweater_number,
    position = EXCLUDED.position,
    goals = EXCLUDED.goals,
    assists = EXCLUDED.assists,
    points = EXCLUDED.points,
    plus_minus = EXCLUDED.plus_minus,
    shots_on_goal = EXCLUDED.shots_on_goal,
    toi_seconds = EXCLUDED.toi_seconds,
    shifts = EXCLUDED.shifts,
    faceoff_winning_pctg = EXCLUDED.faceoff_winning_pctg,
    hits = EXCLUDED.hits,
    blocked_shots = EXCLUDED.blocked_shots,
    penalty_minutes = EXCLUDED.penalty_minutes,
    giveaways = EXCLUDED.giveaways,
    takeaways = EXCLUDED.takeaways,
    power_play_goals = EXCLUDED.power_play_goals,
    updated_at = NOW()
WHERE (game_skater_stats.team_id, game_skater_stats.is_home,
       game_skater_stats.sweater_number, game_skater_stats.position,
       game_skater_stats.goals, game_skater_stats.assists,
       game_skater_stats.points, game_skater_stats.plus_minus,
       game_skater_stats.shots_on_goal, game_skater_stats.toi_seconds,
       game_skater_stats.shifts, game_skater_stats.faceoff_winning_pctg,
       game_skater_stats.hits, game_skater_stats.blocked_shots,
       game_skater_stats.penalty_minutes, game_skater_stats.giveaways,
       game_skater_stats.takeaways, game_skater_stats.power_play_goals)
      IS DISTINCT FROM
      (EXCLUDED.team_id, EXCLUDED.is_home,
       EXCLUDED.sweater_number, EXCLUDED.position,
       EXCLUDED.goals, EXCLUDED.assists,
       EXCLUDED.points, EXCLUDED.plus_minus,
       EXCLUDED.shots_on_goal, EXCLUDED.toi_seconds,
       EXCLUDED.shifts, EXCLUDED.faceoff_winning_pctg,
       EXCLUDED.hits, EXCLUDED.blocked_shots,
       EXCLUDED.penalty_minutes, EXCLUDED.giveaways,
       EXCLUDED.takeaways, EXCLUDED.power_play_goals)
`

type UpsertGameSkaterStatsBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertGameSkaterStatsBatchParams struct {
	GameID             int64         `json:"game_id"`
	PlayerID           int64         `json:"player_id"`
	TeamID             int64         `json:"team_id"`
	IsHome             bool          `json:"is_home"`
	SweaterNumber      int16         `json:"sweater_number"`
	Position           string        `json:"position"`
	Goals              int16         `json:"goals"`
	Assists            int16         `json:"assists"`
	Points             int16         `json:"points"`
	PlusMinus          int16         `json:"plus_minus"`
	ShotsOnGoal        int16         `json:"shots_on_goal"`
	TOISeconds         int32         `json:"toi_seconds"`
	Shifts             int16         `json:"shifts"`
	FaceoffWinningPctg pgtype.Float4 `json:"faceoff_winning_pctg"`
	Hits               int16         `json:"hits"`
	BlockedShots       int16         `json:"blocked_shots"`
	PenaltyMinutes     int16         `json:"penalty_minutes"`
	Giveaways          int16         `json:"giveaways"`
	Takeaways          int16         `json:"takeaways"`
	PowerPlayGoals     int16         `json:"power_play_goals"`
}

func (q *Queries) UpsertGameSkaterStatsBatch(ctx context.Context, arg []UpsertGameSkaterStatsBatchParams) *UpsertGameSkaterStatsBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GameID,
			a.PlayerID,
			a.TeamID,
			a.IsHome,
			a.SweaterNumber,
			a.Position,
			a.Goals,
			a.Assists,
			a.Points,
			a.PlusMinus,
			a.ShotsOnGoal,
			a.TOISeconds,
			a.Shifts,
			a.FaceoffWinningPctg,
			a.Hits,
			a.BlockedShots,
			a.PenaltyMinutes,
			a.Giveaways,
			a.Takeaways,
			a.PowerPlayGoals,
		}
		batch.Queue(upsertGameSkaterStatsBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertGameSkaterStatsBatchBatchResults{br, len(arg), false}
}

func (b *UpsertGameSkaterStatsBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertGameSkaterStatsBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertPlayEventBatch = `-- name: UpsertPlayEventBatch :batchexec
INSERT INTO play_events (
    game_id, event_id, period, period_type, time_in_period, time_remaining,
    situation_code, home_team_defending_side, type_code, type_desc_key, sort_order,
    x_coord, y_coord, zone_code, event_owner_team_id,
    shot_type, shooting_player_id, goalie_in_net_id,
    blocking_player_id,
    scoring_player_id, scoring_player_total,
    assist1_player_id, assist1_player_total,
    assist2_player_id, assist2_player_total,
    away_score, home_score,
    highlight_clip_id, highlight_clip_url, discrete_clip_id,
    penalty_type_code, penalty_desc_key, penalty_duration,
    committed_by_player_id, drawn_by_player_id,
    hitting_player_id, hittee_player_id,
    winning_player_id, losing_player_id,
    player_id, reason, away_sog, home_sog
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18,
    $19,
    $20, $21,
    $22, $23,
    $24, $25,
    $26, $27,
    $28, $29, $30,
    $31, $32, $33,
    $34, $35,
    $36, $37,
    $38, $39,
    $40, $41, $42, $43
)
ON CONFLICT (game_id, event_id) DO UPDATE SET
    period = EXCLUDED.period,
    period_type = EXCLUDED.period_type,
    time_in_period = EXCLUDED.time_in_period,
    time_remaining = EXCLUDED.time_remaining,
    situation_code = EXCLUDED.situation_code,
    home_team_defending_side = EXCLUDED.home_team_defending_side,
    type_code = EXCLUDED.type_code,
    type_desc_key = EXCLUDED.type_desc_key,
    sort_order = EXCLUDED.sort_order,
    x_coord = EXCLUDED.x_coord,
    y_coord = EXCLUDED.y_coord,
    zone_code = EXCLUDED.zone_code,
    event_owner_team_id = EXCLUDED.event_owner_team_id,
    shot_type = EXCLUDED.shot_type,
    shooting_player_id = EXCLUDED.shooting_player_id,
    goalie_in_net_id = EXCLUDED.goalie_in_net_id,
    blocking_player_id = EXCLUDED.blocking_player_id,
    scoring_player_id = EXCLUDED.scoring_player_id,
    scoring_player_total = EXCLUDED.scoring_player_total,
    assist1_player_id = EXCLUDED.assist1_player_id,
    assist1_player_total = EXCLUDED.assist1_player_total,
    assist2_player_id = EXCLUDED.assist2_player_id,
    assist2_player_total = EXCLUDED.assist2_player_total,
    away_score = EXCLUDED.away_score,
    home_score = EXCLUDED.home_score,
    highlight_clip_id = EXCLUDED.highlight_clip_id,
    highlight_clip_url = EXCLUDED.highlight_clip_url,
    discrete_clip_id = EXCLUDED.discrete_clip_id,
    penalty_type_code = EXCLUDED.penalty_type_code,
    penalty_desc_key = EXCLUDED.penalty_desc_key,
    penalty_duration = EXCLUDED.penalty_duration,
    committed_by_player_id = EXCLUDED.committed_by_player_id,
    drawn_by_player_id = EXCLUDED.drawn_by_player_id,
    hitting_player_id = EXCLUDED.hitting_player_id,
    hittee_player_id = EXCLUDED.hittee_player_id,
    winning_player_id = EXCLUDED.winning_player_id,
    losing_player_id = EXCLUDED.losing_player_id,
    player_id = EXCLUDED.player_id,
    reason = EXCLUDED.reason,
    away_sog = EXCLUDED.away_sog,
    home_sog = EXCLUDED.home_sog
WHERE (play_events.period, play_events.period_type,
       play_events.time_in_period, play_events.time_remaining,
       play_events.situation_code, play_events.home_team_defending_side,
       play_events.type_code, play_events.type_desc_key, play_events.sort_order,
       play_events.x_coord, play_events.y_coord, play_events.zone_code,
       play_events.event_owner_team_id,
       play_events.shot_type, play_events.shooting_player_id,
       play_events.goalie_in_net_id, play_events.blocking_player_id,
       play_events.scoring_player_id, play_events.scoring_player_total,
       play_events.assist1_player_id, play_events.assist1_player_total,
       play_events.assist2_player_id, play_events.assist2_player_total,
       play_events.away_score, play_events.home_score,
       play_events.highlight_clip_id, play_events.highlight_clip_url,
       play_events.discrete_clip_id,
       play_events.penalty_type_code, play_events.penalty_desc_key,
       play_events.penalty_duration,
       play_events.committed_by_player_id, play_events.drawn_by_player_id,
       play_events.hitting_player_id, play_events.hittee_player_id,
       play_events.winning_player_id, play_events.losing_player_id,
       play_events.player_id, play_events.reason,
       play_events.away_sog, play_events.home_sog)
      IS DISTINCT FROM
      (EXCLUDED.period, EXCLUDED.period_type,
       EXCLUDED.time_in_period, EXCLUDED.time_remaining,
       EXCLUDED.situation_code, EXCLUDED.home_team_defending_side,
       EXCLUDED.type_code, EXCLUDED.type_desc_key, EXCLUDED.sort_order,
       EXCLUDED.x_coord, EXCLUDED.y_coord, EXCLUDED.zone_code,
       EXCLUDED.event_owner_team_id,
       EXCLUDED.shot_type, EXCLUDED.shooting_player_id,
       EXCLUDED.goalie_in_net_id, EXCLUDED.blocking_player_id,
       EXCLUDED.scoring_player_id, EXCLUDED.scoring_player_total,
       EXCLUDED.assist1_player_id, EXCLUDED.assist1_player_total,
       EXCLUDED.assist2_player_id, EXCLUDED.assist2_player_total,
       EXCLUDED.away_score, EXCLUDED.home_score,
       EXCLUDED.highlight_clip_id, EXCLUDED.highlight_clip_url,
       EXCLUDED.discrete_clip_id,
       EXCLUDED.penalty_type_code, EXCLUDED.penalty_desc_key,
       EXCLUDED.penalty_duration,
       EXCLUDED.committed_by_player_id, EXCLUDED.drawn_by_player_id,
       EXCLUDED.hitting_player_id, EXCLUDED.hittee_player_id,
       EXCLUDED.winning_player_id, EXCLUDED.losing_player_id,
       EXCLUDED.player_id, EXCLUDED.reason,
       EXCLUDED.away_sog, EXCLUDED.home_sog)
`

type UpsertPlayEventBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertPlayEventBatchParams struct {
	GameID                int64       `json:"game_id"`
	EventID               int64       `json:"event_id"`
	Period                int32       `json:"period"`
	PeriodType            string      `json:"period_type"`
	TimeInPeriod          string      `json:"time_in_period"`
	TimeRemaining         string      `json:"time_remaining"`
	SituationCode         pgtype.Text `json:"situation_code"`
	HomeTeamDefendingSide pgtype.Text `json:"home_team_defending_side"`
	TypeCode              int32       `json:"type_code"`
	TypeDescKey           string      `json:"type_desc_key"`
	SortOrder             int32       `json:"sort_order"`
	XCoord                pgtype.Int4 `json:"x_coord"`
	YCoord                pgtype.Int4 `json:"y_coord"`
	ZoneCode              pgtype.Text `json:"zone_code"`
	EventOwnerTeamID      pgtype.Int8 `json:"event_owner_team_id"`
	ShotType              pgtype.Text `json:"shot_type"`
	ShootingPlayerID      pgtype.Int8 `json:"shooting_player_id"`
	GoalieInNetID         pgtype.Int8 `json:"goalie_in_net_id"`
	BlockingPlayerID      pgtype.Int8 `json:"blocking_player_id"`
	ScoringPlayerID       pgtype.Int8 `json:"scoring_player_id"`
	ScoringPlayerTotal    pgtype.Int4 `json:"scoring_player_total"`
	Assist1PlayerID       pgtype.Int8 `json:"assist1_player_id"`
	Assist1PlayerTotal    pgtype.Int4 `json:"assist1_player_total"`
	Assist2PlayerID       pgtype.Int8 `json:"assist2_player_id"`
	Assist2PlayerTotal    pgtype.Int4 `json:"assist2_player_total"`
	AwayScore             pgtype.Int4 `json:"away_score"`
	HomeScore             pgtype.Int4 `json:"home_score"`
	HighlightClipID       pgtype.Int8 `json:"highlight_clip_id"`
	HighlightClipUrl      pgtype.Text `json:"highlight_clip_url"`
	DiscreteClipID        pgtype.Int8 `json:"discrete_clip_id"`
	PenaltyTypeCode       pgtype.Text `json:"penalty_type_code"`
	PenaltyDescKey        pgtype.Text `json:"penalty_desc_key"`
	PenaltyDuration       pgtype.Int4 `json:"penalty_duration"`
	CommittedByPlayerID   pgtype.Int8 `json:"committed_by_player_id"`
	DrawnByPlayerID       pgtype.Int8 `json:"drawn_by_player_id"`
	HittingPlayerID       pgtype.Int8 `json:"hitting_player_id"`
	HitteePlayerID        pgtype.Int8 `json:"hittee_player_id"`
	WinningPlayerID       pgtype.Int8 `json:"winning_player_id"`
	LosingPlayerID        pgtype.Int8 `json:"losing_player_id"`
	PlayerID              pgtype.Int8 `json:"player_id"`
	Reason                pgtype.Text `json:"reason"`
	AwaySog               pgtype.Int4 `json:"away_sog"`
	HomeSog               pgtype.Int4 `json:"home_sog"`
}

func (q *Queries) UpsertPlayEventBatch(ctx context.Context, arg []UpsertPlayEventBatchParams) *UpsertPlayEventBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GameID,
			a.EventID,
			a.Period,
			a.PeriodType,
			a.TimeInPeriod,
			a.TimeRemaining,
			a.SituationCode,
			a.HomeTeamDefendingSide,
			a.TypeCode,
			a.TypeDescKey,
			a.SortOrder,
			a.XCoord,
			a.YCoord,
			a.ZoneCode,
			a.EventOwnerTeamID,
			a.ShotType,
			a.ShootingPlayerID,
			a.GoalieInNetID,
			a.BlockingPlayerID,
			a.ScoringPlayerID,
			a.ScoringPlayerTotal,
			a.Assist1PlayerID,
			a.Assist1PlayerTotal,
			a.Assist2PlayerID,
			a.Assist2PlayerTotal,
			a.AwayScore,
			a.HomeScore,
			a.HighlightClipID,
			a.HighlightClipUrl,
			a.DiscreteClipID,
			a.PenaltyTypeCode,
			a.PenaltyDescKey,
			a.PenaltyDuration,
			a.CommittedByPlayerID,
			a.DrawnByPlayerID,
			a.HittingPlayerID,
			a.HitteePlayerID,
			a.WinningPlayerID,
			a.LosingPlayerID,
			a.PlayerID,
			a.Reason,
			a.AwaySog,
			a.HomeSog,
		}
		batch.Queue(upsertPlayEventBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertPlayEventBatchBatchResults{br, len(arg), false}
}

func (b *UpsertPlayEventBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertPlayEventBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertShiftBatch = `-- name: UpsertShiftBatch :batchexec
INSERT INTO shifts (
    id, game_id, player_id, team_id, period,
    start_time, end_time, duration,
    shift_number, type_code, detail_code,
    event_number, event_description
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
ON CONFLICT (id) DO UPDATE SET
    game_id = EXCLUDED.game_id,
    player_id = EXCLUDED.player_id,
    team_id = EXCLUDED.team_id,
    period = EXCLUDED.period,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    duration = EXCLUDED.duration,
    shift_number = EXCLUDED.shift_number,
    type_code = EXCLUDED.type_code,
    detail_code = EXCLUDED.detail_code,
    event_number = EXCLUDED.event_number,
    event_description = EXCLUDED.event_description
WHERE (shifts.game_id, shifts.player_id, shifts.team_id, shifts.period,
       shifts.start_time, shifts.end_time, shifts.duration,
       shifts.shift_number, shifts.type_code, shifts.detail_code,
       shifts.event_number, shifts.event_description)
      IS DISTINCT FROM
      (EXCLUDED.game_id, EXCLUDED.player_id, EXCLUDED.team_id, EXCLUDED.period,
       EXCLUDED.start_time, EXCLUDED.end_time, EXCLUDED.duration,
       EXCLUDED.shift_number, EXCLUDED.type_code, EXCLUDED.detail_code,
       EXCLUDED.event_number, EXCLUDED.event_description)
`

type UpsertShiftBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertShiftBatchParams struct {
	ID               int64       `json:"id"`
	GameID           int64       `json:"game_id"`
	PlayerID         int64       `json:"player_id"`
	TeamID           int64       `json:"team_id"`
	Period           int32       `json:"period"`
	StartTime        string      `json:"start_time"`
	EndTime          string      `json:"end_time"`
	Duration         string      `json:"duration"`
	ShiftNumber      int32       `json:"shift_number"`
	TypeCode         int32       `json:"type_code"`
	DetailCode       int32       `json:"detail_code"`
	EventNumber      int64       `json:"event_number"`
	EventDescription pgtype.Text `json:"event_description"`
}

func (q *Queries) UpsertShiftBatch(ctx context.Context, arg []UpsertShiftBatchParams) *UpsertShiftBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.GameID,
			a.PlayerID,
			a.TeamID,
			a.Period,
			a.StartTime,
			a.EndTime,
			a.Duration,
			a.ShiftNumber,
			a.TypeCode,
			a.DetailCode,
			a.EventNumber,
			a.EventDescription,
		}
		batch.Queue(upsertShiftBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertShiftBatchBatchResults{br, len(arg), false}
}

func (b *UpsertShiftBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertShiftBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooLeagueRosterPositionBatch = `-- name: UpsertYahooLeagueRosterPositionBatch :batchexec
INSERT INTO yahoo_league_roster_positions (
    league_id, position, position_type, count, is_starting_position
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (league_id, position) DO UPDATE SET
    position_type = EXCLUDED.position_type,
    count = EXCLUDED.count,
    is_starting_position = EXCLUDED.is_starting_position
WHERE (yahoo_league_roster_positions.position_type,
       yahoo_league_roster_positions.count,
       yahoo_league_roster_positions.is_starting_position)
      IS DISTINCT FROM
      (EXCLUDED.position_type, EXCLUDED.count, EXCLUDED.is_starting_position)
`

type UpsertYahooLeagueRosterPositionBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooLeagueRosterPositionBatchParams struct {
	LeagueID           int32  `json:"league_id"`
	Position           string `json:"position"`
	PositionType       string `json:"position_type"`
	Count              int32  `json:"count"`
	IsStartingPosition bool   `json:"is_starting_position"`
}

func (q *Queries) UpsertYahooLeagueRosterPositionBatch(ctx context.Context, arg []UpsertYahooLeagueRosterPositionBatchParams) *UpsertYahooLeagueRosterPositionBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.Position,
			a.PositionType,
			a.Count,
			a.IsStartingPosition,
		}
		batch.Queue(upsertYahooLeagueRosterPositionBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooLeagueRosterPositionBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooLeagueRosterPositionBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooLeagueRosterPositionBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooLeagueStatCategoryBatch = `-- name: UpsertYahooLeagueStatCategoryBatch :batchexec
INSERT INTO yahoo_league_stat_categories (
    league_id, stat_id, name, abbr, stat_group, enabled, value
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (league_id, stat_id) DO UPDATE SET
    name = EXCLUDED.name,
    abbr = EXCLUDED.abbr,
    stat_group = EXCLUDED.stat_group,
    enabled = EXCLUDED.enabled,
    value = EXCLUDED.value
WHERE (yahoo_league_stat_categories.name, yahoo_league_stat_categories.abbr,
       yahoo_league_stat_categories.stat_group,
       yahoo_league_stat_categories.enabled,
       yahoo_league_stat_categories.value)
      IS DISTINCT FROM
      (EXCLUDED.name, EXCLUDED.abbr, EXCLUDED.stat_group,
       EXCLUDED.enabled, EXCLUDED.value)
`

type UpsertYahooLeagueStatCategoryBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooLeagueStatCategoryBatchParams struct {
	LeagueID  int32         `json:"league_id"`
	StatID    int32         `json:"stat_id"`
	Name      string        `json:"name"`
	Abbr      string        `json:"abbr"`
	StatGroup string        `json:"stat_group"`
	Enabled   bool          `json:"enabled"`
	Value     pgtype.Float4 `json:"value"`
}

func (q *Queries) UpsertYahooLeagueStatCategoryBatch(ctx context.Context, arg []UpsertYahooLeagueStatCategoryBatchParams) *UpsertYahooLeagueStatCategoryBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.StatID,
			a.Name,
			a.Abbr,
			a.StatGroup,
			a.Enabled,
			a.Value,
		}
		batch.Queue(upsertYahooLeagueStatCategoryBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooLeagueStatCategoryBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooLeagueStatCategoryBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooLeagueStatCategoryBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooTeamBatch = `-- name: UpsertYahooTeamBatch :batchexec
INSERT INTO yahoo_teams (
    league_id, id, team_key, name, url, logo_url,
    draft_position, waiver_priority, number_of_moves, number_of_trades,
    is_owned_by_current_login
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (league_id, id) DO UPDATE SET
    team_key = EXCLUDED.team_key,
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    logo_url = EXCLUDED.logo_url,
    draft_position = EXCLUDED.draft_position,
    waiver_priority = EXCLUDED.waiver_priority,
    number_of_moves = EXCLUDED.number_of_moves,
    number_of_trades = EXCLUDED.number_of_trades,
    is_owned_by_current_login = EXCLUDED.is_owned_by_current_login,
    updated_at = NOW()
WHERE (yahoo_teams.team_key, yahoo_teams.name, yahoo_teams.url,
       yahoo_teams.logo_url, yahoo_teams.draft_position,
       yahoo_teams.waiver_priority, yahoo_teams.number_of_moves,
       yahoo_teams.number_of_trades, yahoo_teams.is_owned_by_current_login)
      IS DISTINCT FROM
      (EXCLUDED.team_key, EXCLUDED.name, EXCLUDED.url,
       EXCLUDED.logo_url, EXCLUDED.draft_position,
       EXCLUDED.waiver_priority, EXCLUDED.number_of_moves,
       EXCLUDED.number_of_trades, EXCLUDED.is_owned_by_current_login)
`

type UpsertYahooTeamBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooTeamBatchParams struct {
	LeagueID              int32       `json:"league_id"`
	ID                    int32       `json:"id"`
	TeamKey               string      `json:"team_key"`
	Name                  string      `json:"name"`
	Url                   string      `json:"url"`
	LogoUrl               string      `json:"logo_url"`
	DraftPosition         pgtype.Int4 `json:"draft_position"`
	WaiverPriority        pgtype.Int4 `json:"waiver_priority"`
	NumberOfMoves         int32       `json:"number_of_moves"`
	NumberOfTrades        int32       `json:"number_of_trades"`
	IsOwnedByCurrentLogin bool        `json:"is_owned_by_current_login"`
}

func (q *Queries) UpsertYahooTeamBatch(ctx context.Context, arg []UpsertYahooTeamBatchParams) *UpsertYahooTeamBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.ID,
			a.TeamKey,
			a.Name,
			a.Url,
			a.LogoUrl,
			a.DraftPosition,
			a.WaiverPriority,
			a.NumberOfMoves,
			a.NumberOfTrades,
			a.IsOwnedByCurrentLogin,
		}
		batch.Queue(upsertYahooTeamBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooTeamBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooTeamBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooTeamBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooTeamManagerBatch = `-- name: UpsertYahooTeamManagerBatch :batchexec
INSERT INTO yahoo_team_managers (
    league_id, team_id, id, nickname, guid, email, image_url,
    felo_score, felo_tier, is_current_login, is_commissioner
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (league_id, team_id, id) DO UPDATE SET
    nickname = EXCLUDED.nickname,
    guid = EXCLUDED.guid,
    email = EXCLUDED.email,
    image_url = EXCLUDED.image_url,
    felo_score = EXCLUDED.felo_score,
    felo_tier = EXCLUDED.felo_tier,
    is_current_login = EXCLUDED.is_current_login,
    is_commissioner = EXCLUDED.is_commissioner
WHERE (yahoo_team_managers.nickname, yahoo_team_managers.guid,
       yahoo_team_managers.email, yahoo_team_managers.image_url,
       yahoo_team_managers.felo_score, yahoo_team_managers.felo_tier,
       yahoo_team_managers.is_current_login, yahoo_team_managers.is_commissioner)
      IS DISTINCT FROM
      (EXCLUDED.nickname, EXCLUDED.guid,
       EXCLUDED.email, EXCLUDED.image_url,
       EXCLUDED.felo_score, EXCLUDED.felo_tier,
       EXCLUDED.is_current_login, EXCLUDED.is_commissioner)
`

type UpsertYahooTeamManagerBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooTeamManagerBatchParams struct {
	LeagueID       int32  `json:"league_id"`
	TeamID         int32  `json:"team_id"`
	ID             int32  `json:"id"`
	Nickname       string `json:"nickname"`
	Guid           string `json:"guid"`
	Email          string `json:"email"`
	ImageUrl       string `json:"image_url"`
	FeloScore      int32  `json:"felo_score"`
	FeloTier       string `json:"felo_tier"`
	IsCurrentLogin bool   `json:"is_current_login"`
	IsCommissioner bool   `json:"is_commissioner"`
}

func (q *Queries) UpsertYahooTeamManagerBatch(ctx context.Context, arg []UpsertYahooTeamManagerBatchParams) *UpsertYahooTeamManagerBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.TeamID,
			a.ID,
			a.Nickname,
			a.Guid,
			a.Email,
			a.ImageUrl,
			a.FeloScore,
			a.FeloTier,
			a.IsCurrentLogin,
			a.IsCommissioner,
		}
		batch.Queue(upsertYahooTeamManagerBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooTeamManagerBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooTeamManagerBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooTeamManagerBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooTeamRosterBatch = `-- name: UpsertYahooTeamRosterBatch :batchexec
INSERT INTO yahoo_team_rosters (
    league_id, team_id, date, player_id,
    coverage_type, is_editable, player_key,
    selected_position, is_flex
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (league_id, team_id, date, player_id) DO UPDATE SET
    coverage_type = EXCLUDED.coverage_type,
    is_editable = EXCLUDED.is_editable,
    player_key = EXCLUDED.player_key,
    selected_position = EXCLUDED.selected_position,
    is_flex = EXCLUDED.is_flex,
    updated_at = NOW()
WHERE (yahoo_team_rosters.coverage_type, yahoo_team_rosters.is_editable,
       yahoo_team_rosters.player_key, yahoo_team_rosters.selected_position,
       yahoo_team_rosters.is_flex)
      IS DISTINCT FROM
      (EXCLUDED.coverage_type, EXCLUDED.is_editable,
       EXCLUDED.player_key, EXCLUDED.selected_position,
       EXCLUDED.is_flex)
`

type UpsertYahooTeamRosterBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooTeamRosterBatchParams struct {
	LeagueID         int32       `json:"league_id"`
	TeamID           int32       `json:"team_id"`
	Date             pgtype.Date `json:"date"`
	PlayerID         int32       `json:"player_id"`
	CoverageType     string      `json:"coverage_type"`
	IsEditable       bool        `json:"is_editable"`
	PlayerKey        string      `json:"player_key"`
	SelectedPosition string      `json:"selected_position"`
	IsFlex           bool        `json:"is_flex"`
}

func (q *Queries) UpsertYahooTeamRosterBatch(ctx context.Context, arg []UpsertYahooTeamRosterBatchParams) *UpsertYahooTeamRosterBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.TeamID,
			a.Date,
			a.PlayerID,
			a.CoverageType,
			a.IsEditable,
			a.PlayerKey,
			a.SelectedPosition,
			a.IsFlex,
		}
		batch.Queue(upsertYahooTeamRosterBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooTeamRosterBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooTeamRosterBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooTeamRosterBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooTeamSummaryBatch = `-- name: UpsertYahooTeamSummaryBatch :batchexec
INSERT INTO yahoo_team_summaries (
    league_id, team_id, date, coverage_type
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (league_id, team_id, date) DO UPDATE SET
    coverage_type = EXCLUDED.coverage_type,
    updated_at = NOW()
WHERE yahoo_team_summaries.coverage_type IS DISTINCT FROM EXCLUDED.coverage_type
`

type UpsertYahooTeamSummaryBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooTeamSummaryBatchParams struct {
	LeagueID     int32       `json:"league_id"`
	TeamID       int32       `json:"team_id"`
	Date         pgtype.Date `json:"date"`
	CoverageType string      `json:"coverage_type"`
}

func (q *Queries) UpsertYahooTeamSummaryBatch(ctx context.Context, arg []UpsertYahooTeamSummaryBatchParams) *UpsertYahooTeamSummaryBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.TeamID,
			a.Date,
			a.CoverageType,
		}
		batch.Queue(upsertYahooTeamSummaryBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooTeamSummaryBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooTeamSummaryBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooTeamSummaryBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertYahooTeamSummaryStatBatch = `-- name: UpsertYahooTeamSummaryStatBatch :batchexec
INSERT INTO yahoo_team_summary_stats (
    league_id, team_id, date, stat_id, value
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (league_id, team_id, date, stat_id) DO UPDATE SET
    value = EXCLUDED.value
WHERE yahoo_team_summary_stats.value IS DISTINCT FROM EXCLUDED.value
`

type UpsertYahooTeamSummaryStatBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertYahooTeamSummaryStatBatchParams struct {
	LeagueID int32       `json:"league_id"`
	TeamID   int32       `json:"team_id"`
	Date     pgtype.Date `json:"date"`
	StatID   int32       `json:"stat_id"`
	Value    string      `json:"value"`
}

func (q *Queries) UpsertYahooTeamSummaryStatBatch(ctx context.Context, arg []UpsertYahooTeamSummaryStatBatchParams) *UpsertYahooTeamSummaryStatBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.LeagueID,
			a.TeamID,
			a.Date,
			a.StatID,
			a.Value,
		}
		batch.Queue(upsertYahooTeamSummaryStatBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertYahooTeamSummaryStatBatchBatchResults{br, len(arg), false}
}

func (b *UpsertYahooTeamSummaryStatBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertYahooTeamSummaryStatBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
