// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: franchises.sql

package sqlcdb

import (
	"context"
)

const countFranchises = `-- name: CountFranchises :one
SELECT COUNT(*) FROM franchises
`

func (q *Queries) CountFranchises(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFranchises)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllFranchises = `-- name: GetAllFranchises :many
SELECT id, full_name, team_common_name, team_place_name
FROM franchises
ORDER BY id
`

func (q *Queries) GetAllFranchises(ctx context.Context) ([]Franchise, error) {
	rows, err := q.db.Query(ctx, getAllFranchises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Franchise{}
	for rows.Next() {
		var i Franchise
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.TeamCommonName,
			&i.TeamPlaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFranchise = `-- name: GetFranchise :one
SELECT id, full_name, team_common_name, team_place_name
FROM franchises
WHERE id = $1
`

func (q *Queries) GetFranchise(ctx context.Context, id int64) (Franchise, error) {
	row := q.db.QueryRow(ctx, getFranchise, id)
	var i Franchise
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.TeamCommonName,
		&i.TeamPlaceName,
	)
	return i, err
}

const upsertFranchise = `-- name: UpsertFranchise :exec
INSERT INTO franchises (id, full_name, team_common_name, team_place_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    team_common_name = EXCLUDED.team_common_name,
    team_place_name = EXCLUDED.team_place_name
WHERE (franchises.full_name, franchises.team_common_name, franchises.team_place_name)
      IS DISTINCT FROM
      (EXCLUDED.full_name, EXCLUDED.team_common_name, EXCLUDED.team_place_name)
`

type UpsertFranchiseParams struct {
	ID             int64  `json:"id"`
	FullName       string `json:"full_name"`
	TeamCommonName string `json:"team_common_name"`
	TeamPlaceName  string `json:"team_place_name"`
}

func (q *Queries) UpsertFranchise(ctx context.Context, arg UpsertFranchiseParams) error {
	_, err := q.db.Exec(ctx, upsertFranchise,
		arg.ID,
		arg.FullName,
		arg.TeamCommonName,
		arg.TeamPlaceName,
	)
	return err
}
