// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_story.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayerThreeStars = `-- name: CountPlayerThreeStars :one
SELECT
    COUNT(*) FILTER (WHERE star = 1)::int as first_stars,
    COUNT(*) FILTER (WHERE star = 2)::int as second_stars,
    COUNT(*) FILTER (WHERE star = 3)::int as third_stars
FROM game_three_stars ts
JOIN games g ON ts.game_id = g.id
WHERE ts.player_id = $1 AND g.season = $2
`

type CountPlayerThreeStarsParams struct {
	PlayerID int64 `json:"player_id"`
	Season   int32 `json:"season"`
}

type CountPlayerThreeStarsRow struct {
	FirstStars  int32 `json:"first_stars"`
	SecondStars int32 `json:"second_stars"`
	ThirdStars  int32 `json:"third_stars"`
}

// Count three-star selections by type for a player in a season
func (q *Queries) CountPlayerThreeStars(ctx context.Context, arg CountPlayerThreeStarsParams) (CountPlayerThreeStarsRow, error) {
	row := q.db.QueryRow(ctx, countPlayerThreeStars, arg.PlayerID, arg.Season)
	var i CountPlayerThreeStarsRow
	err := row.Scan(&i.FirstStars, &i.SecondStars, &i.ThirdStars)
	return i, err
}

const getGameThreeStars = `-- name: GetGameThreeStars :many
SELECT ts.game_id, ts.star, ts.player_id, p.first_name, p.last_name, p.position
FROM game_three_stars ts
JOIN players p ON ts.player_id = p.id
WHERE ts.game_id = $1
ORDER BY ts.star
`

type GetGameThreeStarsRow struct {
	GameID    int64  `json:"game_id"`
	Star      int16  `json:"star"`
	PlayerID  int64  `json:"player_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Position  string `json:"position"`
}

func (q *Queries) GetGameThreeStars(ctx context.Context, gameID int64) ([]GetGameThreeStarsRow, error) {
	rows, err := q.db.Query(ctx, getGameThreeStars, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGameThreeStarsRow{}
	for rows.Next() {
		var i GetGameThreeStarsRow
		if err := rows.Scan(
			&i.GameID,
			&i.Star,
			&i.PlayerID,
			&i.FirstName,
			&i.LastName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalHighlights = `-- name: GetGoalHighlights :many
SELECT gh.game_id, gh.event_id, gh.player_id, gh.period, gh.time_in_period, gh.goals_to_date, gh.highlight_clip_id, gh.highlight_clip_url, gh.discrete_clip_id, p.first_name, p.last_name
FROM goal_highlights gh
JOIN players p ON gh.player_id = p.id
WHERE gh.game_id = $1
ORDER BY gh.period, gh.time_in_period
`

type GetGoalHighlightsRow struct {
	GameID           int64       `json:"game_id"`
	EventID          int64       `json:"event_id"`
	PlayerID         int64       `json:"player_id"`
	Period           int16       `json:"period"`
	TimeInPeriod     string      `json:"time_in_period"`
	GoalsToDate      pgtype.Int2 `json:"goals_to_date"`
	HighlightClipID  pgtype.Int8 `json:"highlight_clip_id"`
	HighlightClipUrl pgtype.Text `json:"highlight_clip_url"`
	DiscreteClipID   pgtype.Int8 `json:"discrete_clip_id"`
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
}

func (q *Queries) GetGoalHighlights(ctx context.Context, gameID int64) ([]GetGoalHighlightsRow, error) {
	rows, err := q.db.Query(ctx, getGoalHighlights, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGoalHighlightsRow{}
	for rows.Next() {
		var i GetGoalHighlightsRow
		if err := rows.Scan(
			&i.GameID,
			&i.EventID,
			&i.PlayerID,
			&i.Period,
			&i.TimeInPeriod,
			&i.GoalsToDate,
			&i.HighlightClipID,
			&i.HighlightClipUrl,
			&i.DiscreteClipID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerThreeStarSelections = `-- name: GetPlayerThreeStarSelections :many
SELECT ts.star, g.game_date, g.season
FROM game_three_stars ts
JOIN games g ON ts.game_id = g.id
WHERE ts.player_id = $1
ORDER BY g.game_date DESC
`

type GetPlayerThreeStarSelectionsRow struct {
	Star     int16       `json:"star"`
	GameDate pgtype.Date `json:"game_date"`
	Season   int32       `json:"season"`
}

// Get all three-star selections for a player
func (q *Queries) GetPlayerThreeStarSelections(ctx context.Context, playerID int64) ([]GetPlayerThreeStarSelectionsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerThreeStarSelections, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerThreeStarSelectionsRow{}
	for rows.Next() {
		var i GetPlayerThreeStarSelectionsRow
		if err := rows.Scan(&i.Star, &i.GameDate, &i.Season); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShootoutAttempts = `-- name: GetShootoutAttempts :many
SELECT sa.game_id, sa.sequence, sa.player_id, sa.team_id, sa.shot_type, sa.result, sa.game_winner, p.first_name, p.last_name
FROM shootout_attempts sa
JOIN players p ON sa.player_id = p.id
WHERE sa.game_id = $1
ORDER BY sa.sequence
`

type GetShootoutAttemptsRow struct {
	GameID     int64  `json:"game_id"`
	Sequence   int16  `json:"sequence"`
	PlayerID   int64  `json:"player_id"`
	TeamID     int64  `json:"team_id"`
	ShotType   string `json:"shot_type"`
	Result     string `json:"result"`
	GameWinner bool   `json:"game_winner"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
}

func (q *Queries) GetShootoutAttempts(ctx context.Context, gameID int64) ([]GetShootoutAttemptsRow, error) {
	rows, err := q.db.Query(ctx, getShootoutAttempts, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetShootoutAttemptsRow{}
	for rows.Next() {
		var i GetShootoutAttemptsRow
		if err := rows.Scan(
			&i.GameID,
			&i.Sequence,
			&i.PlayerID,
			&i.TeamID,
			&i.ShotType,
			&i.Result,
			&i.GameWinner,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamIDByAbbrev = `-- name: GetTeamIDByAbbrev :one
SELECT team_id FROM season_teams
WHERE abbrev = $1 AND season_id = $2
`

type GetTeamIDByAbbrevParams struct {
	Abbrev   string `json:"abbrev"`
	SeasonID int32  `json:"season_id"`
}

// Look up team_id from abbreviation for a given season
func (q *Queries) GetTeamIDByAbbrev(ctx context.Context, arg GetTeamIDByAbbrevParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTeamIDByAbbrev, arg.Abbrev, arg.SeasonID)
	var team_id int64
	err := row.Scan(&team_id)
	return team_id, err
}

const upsertGameThreeStar = `-- name: UpsertGameThreeStar :exec

INSERT INTO game_three_stars (game_id, star, player_id)
VALUES ($1, $2, $3)
ON CONFLICT (game_id, star) DO UPDATE SET
    player_id = EXCLUDED.player_id
`

type UpsertGameThreeStarParams struct {
	GameID   int64 `json:"game_id"`
	Star     int16 `json:"star"`
	PlayerID int64 `json:"player_id"`
}

// =============================================================================
// Game Story Data Queries (Three Stars, Goal Highlights, Shootout Attempts)
// =============================================================================
func (q *Queries) UpsertGameThreeStar(ctx context.Context, arg UpsertGameThreeStarParams) error {
	_, err := q.db.Exec(ctx, upsertGameThreeStar, arg.GameID, arg.Star, arg.PlayerID)
	return err
}

const upsertGoalHighlight = `-- name: UpsertGoalHighlight :exec
INSERT INTO goal_highlights (
    game_id, event_id, player_id, period, time_in_period,
    goals_to_date, highlight_clip_id, highlight_clip_url, discrete_clip_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (game_id, event_id) DO UPDATE SET
    player_id = EXCLUDED.player_id,
    period = EXCLUDED.period,
    time_in_period = EXCLUDED.time_in_period,
    goals_to_date = EXCLUDED.goals_to_date,
    highlight_clip_id = EXCLUDED.highlight_clip_id,
    highlight_clip_url = EXCLUDED.highlight_clip_url,
    discrete_clip_id = EXCLUDED.discrete_clip_id
`

type UpsertGoalHighlightParams struct {
	GameID           int64       `json:"game_id"`
	EventID          int64       `json:"event_id"`
	PlayerID         int64       `json:"player_id"`
	Period           int16       `json:"period"`
	TimeInPeriod     string      `json:"time_in_period"`
	GoalsToDate      pgtype.Int2 `json:"goals_to_date"`
	HighlightClipID  pgtype.Int8 `json:"highlight_clip_id"`
	HighlightClipUrl pgtype.Text `json:"highlight_clip_url"`
	DiscreteClipID   pgtype.Int8 `json:"discrete_clip_id"`
}

func (q *Queries) UpsertGoalHighlight(ctx context.Context, arg UpsertGoalHighlightParams) error {
	_, err := q.db.Exec(ctx, upsertGoalHighlight,
		arg.GameID,
		arg.EventID,
		arg.PlayerID,
		arg.Period,
		arg.TimeInPeriod,
		arg.GoalsToDate,
		arg.HighlightClipID,
		arg.HighlightClipUrl,
		arg.DiscreteClipID,
	)
	return err
}

const upsertShootoutAttempt = `-- name: UpsertShootoutAttempt :exec
INSERT INTO shootout_attempts (
    game_id, sequence, player_id, team_id, shot_type, result, game_winner
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (game_id, sequence) DO UPDATE SET
    player_id = EXCLUDED.player_id,
    team_id = EXCLUDED.team_id,
    shot_type = EXCLUDED.shot_type,
    result = EXCLUDED.result,
    game_winner = EXCLUDED.game_winner
`

type UpsertShootoutAttemptParams struct {
	GameID     int64  `json:"game_id"`
	Sequence   int16  `json:"sequence"`
	PlayerID   int64  `json:"player_id"`
	TeamID     int64  `json:"team_id"`
	ShotType   string `json:"shot_type"`
	Result     string `json:"result"`
	GameWinner bool   `json:"game_winner"`
}

func (q *Queries) UpsertShootoutAttempt(ctx context.Context, arg UpsertShootoutAttemptParams) error {
	_, err := q.db.Exec(ctx, upsertShootoutAttempt,
		arg.GameID,
		arg.Sequence,
		arg.PlayerID,
		arg.TeamID,
		arg.ShotType,
		arg.Result,
		arg.GameWinner,
	)
	return err
}
