// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNHLGames = `-- name: CountNHLGames :one
SELECT COUNT(*) FROM nhl_games
`

func (q *Queries) CountNHLGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNHLGamesBySeason = `-- name: CountNHLGamesBySeason :one
SELECT COUNT(*) FROM nhl_games WHERE season = $1
`

func (q *Queries) CountNHLGamesBySeason(ctx context.Context, season int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLGamesBySeason, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNHLGamesByTeamAndSeason = `-- name: CountNHLGamesByTeamAndSeason :one
SELECT COUNT(*) FROM nhl_games
WHERE (home_team_id = $1 OR away_team_id = $1) AND season = $2
`

type CountNHLGamesByTeamAndSeasonParams struct {
	HomeTeamID int64 `json:"home_team_id"`
	Season     int32 `json:"season"`
}

func (q *Queries) CountNHLGamesByTeamAndSeason(ctx context.Context, arg CountNHLGamesByTeamAndSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLGamesByTeamAndSeason, arg.HomeTeamID, arg.Season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNHLGame = `-- name: DeleteNHLGame :exec
DELETE FROM nhl_games WHERE id = $1
`

func (q *Queries) DeleteNHLGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNHLGame, id)
	return err
}

const deleteNHLGamesBySeason = `-- name: DeleteNHLGamesBySeason :exec
DELETE FROM nhl_games WHERE season = $1
`

func (q *Queries) DeleteNHLGamesBySeason(ctx context.Context, season int32) error {
	_, err := q.db.Exec(ctx, deleteNHLGamesBySeason, season)
	return err
}

const getNHLGame = `-- name: GetNHLGame :one

SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE g.id = $1
`

type GetNHLGameRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// =============================================================================
// NHL Games Queries
// =============================================================================
// Get a single game by ID with team details
func (q *Queries) GetNHLGame(ctx context.Context, id int64) (GetNHLGameRow, error) {
	row := q.db.QueryRow(ctx, getNHLGame, id)
	var i GetNHLGameRow
	err := row.Scan(
		&i.ID,
		&i.Season,
		&i.GameType,
		&i.GameDate,
		&i.Venue,
		&i.VenueLocation,
		&i.StartTimeUTC,
		&i.EasternUTCOffset,
		&i.VenueUTCOffset,
		&i.GameState,
		&i.GameScheduleState,
		&i.PeriodNumber,
		&i.PeriodType,
		&i.MaxRegulationPeriods,
		&i.ClockTimeRemaining,
		&i.ClockSecondsRemaining,
		&i.ClockRunning,
		&i.ClockInIntermission,
		&i.HomeTeamID,
		&i.HomeTeamScore,
		&i.HomeTeamSog,
		&i.AwayTeamID,
		&i.AwayTeamScore,
		&i.AwayTeamSog,
		&i.LimitedScoring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeTeamCity,
		&i.HomeTeamName,
		&i.HomeTeamAbbrev,
		&i.AwayTeamCity,
		&i.AwayTeamName,
		&i.AwayTeamAbbrev,
	)
	return i, err
}

const getNHLGamesByDate = `-- name: GetNHLGamesByDate :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE g.game_date = $1
ORDER BY g.start_time_utc
`

type GetNHLGamesByDateRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games on a specific date
func (q *Queries) GetNHLGamesByDate(ctx context.Context, gameDate pgtype.Date) ([]GetNHLGamesByDateRow, error) {
	rows, err := q.db.Query(ctx, getNHLGamesByDate, gameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNHLGamesByDateRow{}
	for rows.Next() {
		var i GetNHLGamesByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLGamesByDateRange = `-- name: GetNHLGamesByDateRange :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE g.game_date >= $1 AND g.game_date <= $2
ORDER BY g.game_date, g.start_time_utc
`

type GetNHLGamesByDateRangeParams struct {
	GameDate   pgtype.Date `json:"game_date"`
	GameDate_2 pgtype.Date `json:"game_date_2"`
}

type GetNHLGamesByDateRangeRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games within a date range
func (q *Queries) GetNHLGamesByDateRange(ctx context.Context, arg GetNHLGamesByDateRangeParams) ([]GetNHLGamesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getNHLGamesByDateRange, arg.GameDate, arg.GameDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNHLGamesByDateRangeRow{}
	for rows.Next() {
		var i GetNHLGamesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLGamesBySeason = `-- name: GetNHLGamesBySeason :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE g.season = $1
ORDER BY g.game_date, g.start_time_utc
`

type GetNHLGamesBySeasonRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a season
func (q *Queries) GetNHLGamesBySeason(ctx context.Context, season int32) ([]GetNHLGamesBySeasonRow, error) {
	rows, err := q.db.Query(ctx, getNHLGamesBySeason, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNHLGamesBySeasonRow{}
	for rows.Next() {
		var i GetNHLGamesBySeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLGamesByTeam = `-- name: GetNHLGamesByTeam :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE g.home_team_id = $1 OR g.away_team_id = $1
ORDER BY g.game_date, g.start_time_utc
`

type GetNHLGamesByTeamRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a team (home or away)
func (q *Queries) GetNHLGamesByTeam(ctx context.Context, homeTeamID int64) ([]GetNHLGamesByTeamRow, error) {
	rows, err := q.db.Query(ctx, getNHLGamesByTeam, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNHLGamesByTeamRow{}
	for rows.Next() {
		var i GetNHLGamesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLGamesByTeamAndSeason = `-- name: GetNHLGamesByTeamAndSeason :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE (g.home_team_id = $1 OR g.away_team_id = $1)
  AND g.season = $2
ORDER BY g.game_date, g.start_time_utc
`

type GetNHLGamesByTeamAndSeasonParams struct {
	HomeTeamID int64 `json:"home_team_id"`
	Season     int32 `json:"season"`
}

type GetNHLGamesByTeamAndSeasonRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a team in a specific season
func (q *Queries) GetNHLGamesByTeamAndSeason(ctx context.Context, arg GetNHLGamesByTeamAndSeasonParams) ([]GetNHLGamesByTeamAndSeasonRow, error) {
	rows, err := q.db.Query(ctx, getNHLGamesByTeamAndSeason, arg.HomeTeamID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNHLGamesByTeamAndSeasonRow{}
	for rows.Next() {
		var i GetNHLGamesByTeamAndSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNHLGames = `-- name: ListNHLGames :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.city as home_team_city, ht.name as home_team_name, ht.abbreviation as home_team_abbrev,
    at.city as away_team_city, at.name as away_team_name, at.abbreviation as away_team_abbrev
FROM nhl_games g
JOIN nhl_teams ht ON g.home_team_id = ht.id
JOIN nhl_teams at ON g.away_team_id = at.id
WHERE
    ($1::int IS NULL OR g.season = $1)
    AND ($2::smallint IS NULL OR g.game_type = $2)
    AND ($3::text IS NULL OR g.game_state = $3)
    AND ($4::bigint IS NULL OR g.home_team_id = $4 OR g.away_team_id = $4)
    AND ($5::date IS NULL OR g.game_date >= $5)
    AND ($6::date IS NULL OR g.game_date <= $6)
ORDER BY g.game_date, g.start_time_utc
LIMIT COALESCE($7::int, 100)
`

type ListNHLGamesParams struct {
	Season    pgtype.Int4 `json:"season"`
	GameType  pgtype.Int2 `json:"game_type"`
	GameState pgtype.Text `json:"game_state"`
	TeamID    pgtype.Int8 `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Limit     pgtype.Int4 `json:"limit"`
}

type ListNHLGamesRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamCity          string             `json:"home_team_city"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamCity          string             `json:"away_team_city"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Flexible game listing with optional filters
func (q *Queries) ListNHLGames(ctx context.Context, arg ListNHLGamesParams) ([]ListNHLGamesRow, error) {
	rows, err := q.db.Query(ctx, listNHLGames,
		arg.Season,
		arg.GameType,
		arg.GameState,
		arg.TeamID,
		arg.StartDate,
		arg.EndDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNHLGamesRow{}
	for rows.Next() {
		var i ListNHLGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamCity,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamCity,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNHLGame = `-- name: UpsertNHLGame :exec
INSERT INTO nhl_games (
    id, season, game_type, game_date,
    venue, venue_location, start_time_utc, eastern_utc_offset, venue_utc_offset,
    game_state, game_schedule_state,
    period_number, period_type, max_regulation_periods,
    clock_time_remaining, clock_seconds_remaining, clock_running, clock_in_intermission,
    home_team_id, home_team_score, home_team_sog,
    away_team_id, away_team_score, away_team_sog,
    limited_scoring, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23, $24,
    $25, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    season = EXCLUDED.season,
    game_type = EXCLUDED.game_type,
    game_date = EXCLUDED.game_date,
    venue = EXCLUDED.venue,
    venue_location = EXCLUDED.venue_location,
    start_time_utc = EXCLUDED.start_time_utc,
    eastern_utc_offset = EXCLUDED.eastern_utc_offset,
    venue_utc_offset = EXCLUDED.venue_utc_offset,
    game_state = EXCLUDED.game_state,
    game_schedule_state = EXCLUDED.game_schedule_state,
    period_number = EXCLUDED.period_number,
    period_type = EXCLUDED.period_type,
    max_regulation_periods = EXCLUDED.max_regulation_periods,
    clock_time_remaining = EXCLUDED.clock_time_remaining,
    clock_seconds_remaining = EXCLUDED.clock_seconds_remaining,
    clock_running = EXCLUDED.clock_running,
    clock_in_intermission = EXCLUDED.clock_in_intermission,
    home_team_id = EXCLUDED.home_team_id,
    home_team_score = EXCLUDED.home_team_score,
    home_team_sog = EXCLUDED.home_team_sog,
    away_team_id = EXCLUDED.away_team_id,
    away_team_score = EXCLUDED.away_team_score,
    away_team_sog = EXCLUDED.away_team_sog,
    limited_scoring = EXCLUDED.limited_scoring,
    updated_at = NOW()
`

type UpsertNHLGameParams struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              int16              `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             string             `json:"game_state"`
	GameScheduleState     string             `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            string             `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
}

func (q *Queries) UpsertNHLGame(ctx context.Context, arg UpsertNHLGameParams) error {
	_, err := q.db.Exec(ctx, upsertNHLGame,
		arg.ID,
		arg.Season,
		arg.GameType,
		arg.GameDate,
		arg.Venue,
		arg.VenueLocation,
		arg.StartTimeUTC,
		arg.EasternUTCOffset,
		arg.VenueUTCOffset,
		arg.GameState,
		arg.GameScheduleState,
		arg.PeriodNumber,
		arg.PeriodType,
		arg.MaxRegulationPeriods,
		arg.ClockTimeRemaining,
		arg.ClockSecondsRemaining,
		arg.ClockRunning,
		arg.ClockInIntermission,
		arg.HomeTeamID,
		arg.HomeTeamScore,
		arg.HomeTeamSog,
		arg.AwayTeamID,
		arg.AwayTeamScore,
		arg.AwayTeamSog,
		arg.LimitedScoring,
	)
	return err
}
