// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGames = `-- name: CountGames :one
SELECT COUNT(*) FROM games
`

func (q *Queries) CountGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGamesBySeason = `-- name: CountGamesBySeason :one
SELECT COUNT(*) FROM games WHERE season = $1
`

func (q *Queries) CountGamesBySeason(ctx context.Context, season int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGamesBySeason, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGamesByTeamAndSeason = `-- name: CountGamesByTeamAndSeason :one
SELECT COUNT(*) FROM games
WHERE (home_team_id = $1 OR away_team_id = $1) AND season = $2
`

type CountGamesByTeamAndSeasonParams struct {
	HomeTeamID int64 `json:"home_team_id"`
	Season     int32 `json:"season"`
}

func (q *Queries) CountGamesByTeamAndSeason(ctx context.Context, arg CountGamesByTeamAndSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGamesByTeamAndSeason, arg.HomeTeamID, arg.Season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const deleteGamesBySeason = `-- name: DeleteGamesBySeason :exec
DELETE FROM games WHERE season = $1
`

func (q *Queries) DeleteGamesBySeason(ctx context.Context, season int32) error {
	_, err := q.db.Exec(ctx, deleteGamesBySeason, season)
	return err
}

const getGame = `-- name: GetGame :one

SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE g.id = $1
`

type GetGameRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// =============================================================================
// Games Queries
// =============================================================================
// Get a single game by ID with team details
func (q *Queries) GetGame(ctx context.Context, id int64) (GetGameRow, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.Season,
		&i.GameType,
		&i.GameDate,
		&i.Venue,
		&i.VenueLocation,
		&i.StartTimeUTC,
		&i.EasternUTCOffset,
		&i.VenueUTCOffset,
		&i.GameState,
		&i.GameScheduleState,
		&i.PeriodNumber,
		&i.PeriodType,
		&i.MaxRegulationPeriods,
		&i.ClockTimeRemaining,
		&i.ClockSecondsRemaining,
		&i.ClockRunning,
		&i.ClockInIntermission,
		&i.HomeTeamID,
		&i.HomeTeamScore,
		&i.HomeTeamSog,
		&i.AwayTeamID,
		&i.AwayTeamScore,
		&i.AwayTeamSog,
		&i.LimitedScoring,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeTeamName,
		&i.HomeTeamAbbrev,
		&i.AwayTeamName,
		&i.AwayTeamAbbrev,
	)
	return i, err
}

const getGameTeamIDs = `-- name: GetGameTeamIDs :one
SELECT home_team_id, away_team_id FROM games WHERE id = $1
`

type GetGameTeamIDsRow struct {
	HomeTeamID int64 `json:"home_team_id"`
	AwayTeamID int64 `json:"away_team_id"`
}

func (q *Queries) GetGameTeamIDs(ctx context.Context, id int64) (GetGameTeamIDsRow, error) {
	row := q.db.QueryRow(ctx, getGameTeamIDs, id)
	var i GetGameTeamIDsRow
	err := row.Scan(&i.HomeTeamID, &i.AwayTeamID)
	return i, err
}

const getGamesByDate = `-- name: GetGamesByDate :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE g.game_date = $1
ORDER BY g.start_time_utc
`

type GetGamesByDateRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games on a specific date
func (q *Queries) GetGamesByDate(ctx context.Context, gameDate pgtype.Date) ([]GetGamesByDateRow, error) {
	rows, err := q.db.Query(ctx, getGamesByDate, gameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGamesByDateRow{}
	for rows.Next() {
		var i GetGamesByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByDateRange = `-- name: GetGamesByDateRange :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE g.game_date >= $1 AND g.game_date <= $2
ORDER BY g.game_date, g.start_time_utc
`

type GetGamesByDateRangeParams struct {
	GameDate   pgtype.Date `json:"game_date"`
	GameDate_2 pgtype.Date `json:"game_date_2"`
}

type GetGamesByDateRangeRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games within a date range
func (q *Queries) GetGamesByDateRange(ctx context.Context, arg GetGamesByDateRangeParams) ([]GetGamesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getGamesByDateRange, arg.GameDate, arg.GameDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGamesByDateRangeRow{}
	for rows.Next() {
		var i GetGamesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesBySeason = `-- name: GetGamesBySeason :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE g.season = $1
ORDER BY g.game_date, g.start_time_utc
`

type GetGamesBySeasonRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a season
func (q *Queries) GetGamesBySeason(ctx context.Context, season int32) ([]GetGamesBySeasonRow, error) {
	rows, err := q.db.Query(ctx, getGamesBySeason, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGamesBySeasonRow{}
	for rows.Next() {
		var i GetGamesBySeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByTeam = `-- name: GetGamesByTeam :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE g.home_team_id = $1 OR g.away_team_id = $1
ORDER BY g.game_date, g.start_time_utc
`

type GetGamesByTeamRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a team (home or away)
func (q *Queries) GetGamesByTeam(ctx context.Context, homeTeamID int64) ([]GetGamesByTeamRow, error) {
	rows, err := q.db.Query(ctx, getGamesByTeam, homeTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGamesByTeamRow{}
	for rows.Next() {
		var i GetGamesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByTeamAndSeason = `-- name: GetGamesByTeamAndSeason :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE (g.home_team_id = $1 OR g.away_team_id = $1)
  AND g.season = $2
ORDER BY g.game_date, g.start_time_utc
`

type GetGamesByTeamAndSeasonParams struct {
	HomeTeamID int64 `json:"home_team_id"`
	Season     int32 `json:"season"`
}

type GetGamesByTeamAndSeasonRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Get all games for a team in a specific season
func (q *Queries) GetGamesByTeamAndSeason(ctx context.Context, arg GetGamesByTeamAndSeasonParams) ([]GetGamesByTeamAndSeasonRow, error) {
	rows, err := q.db.Query(ctx, getGamesByTeamAndSeason, arg.HomeTeamID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGamesByTeamAndSeasonRow{}
	for rows.Next() {
		var i GetGamesByTeamAndSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT g.id, g.season, g.game_type, g.game_date, g.venue, g.venue_location, g.start_time_utc, g.eastern_utc_offset, g.venue_utc_offset, g.game_state, g.game_schedule_state, g.period_number, g.period_type, g.max_regulation_periods, g.clock_time_remaining, g.clock_seconds_remaining, g.clock_running, g.clock_in_intermission, g.home_team_id, g.home_team_score, g.home_team_sog, g.away_team_id, g.away_team_score, g.away_team_sog, g.limited_scoring, g.created_at, g.updated_at,
    ht.full_name as home_team_name, ht.abbrev as home_team_abbrev,
    at.full_name as away_team_name, at.abbrev as away_team_abbrev
FROM games g
JOIN season_teams ht ON ht.team_id = g.home_team_id AND ht.season = g.season
JOIN season_teams at ON at.team_id = g.away_team_id AND at.season = g.season
WHERE
    ($1::int IS NULL OR g.season = $1)
    AND ($2::game_type IS NULL OR g.game_type = $2)
    AND ($3::game_state IS NULL OR g.game_state = $3)
    AND ($4::bigint IS NULL OR g.home_team_id = $4 OR g.away_team_id = $4)
    AND ($5::date IS NULL OR g.game_date >= $5)
    AND ($6::date IS NULL OR g.game_date <= $6)
ORDER BY g.game_date, g.start_time_utc
LIMIT COALESCE($7::int, 100)
`

type ListGamesParams struct {
	Season    pgtype.Int4   `json:"season"`
	GameType  NullGameType  `json:"game_type"`
	GameState NullGameState `json:"game_state"`
	TeamID    pgtype.Int8   `json:"team_id"`
	StartDate pgtype.Date   `json:"start_date"`
	EndDate   pgtype.Date   `json:"end_date"`
	Limit     pgtype.Int4   `json:"limit"`
}

type ListGamesRow struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	HomeTeamName          string             `json:"home_team_name"`
	HomeTeamAbbrev        string             `json:"home_team_abbrev"`
	AwayTeamName          string             `json:"away_team_name"`
	AwayTeamAbbrev        string             `json:"away_team_abbrev"`
}

// Flexible game listing with optional filters
func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]ListGamesRow, error) {
	rows, err := q.db.Query(ctx, listGames,
		arg.Season,
		arg.GameType,
		arg.GameState,
		arg.TeamID,
		arg.StartDate,
		arg.EndDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGamesRow{}
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.GameType,
			&i.GameDate,
			&i.Venue,
			&i.VenueLocation,
			&i.StartTimeUTC,
			&i.EasternUTCOffset,
			&i.VenueUTCOffset,
			&i.GameState,
			&i.GameScheduleState,
			&i.PeriodNumber,
			&i.PeriodType,
			&i.MaxRegulationPeriods,
			&i.ClockTimeRemaining,
			&i.ClockSecondsRemaining,
			&i.ClockRunning,
			&i.ClockInIntermission,
			&i.HomeTeamID,
			&i.HomeTeamScore,
			&i.HomeTeamSog,
			&i.AwayTeamID,
			&i.AwayTeamScore,
			&i.AwayTeamSog,
			&i.LimitedScoring,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeTeamName,
			&i.HomeTeamAbbrev,
			&i.AwayTeamName,
			&i.AwayTeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGame = `-- name: UpsertGame :exec
INSERT INTO games (
    id, season, game_type, game_date,
    venue, venue_location, start_time_utc, eastern_utc_offset, venue_utc_offset,
    game_state, game_schedule_state,
    period_number, period_type, max_regulation_periods,
    clock_time_remaining, clock_seconds_remaining, clock_running, clock_in_intermission,
    home_team_id, home_team_score, home_team_sog,
    away_team_id, away_team_score, away_team_sog,
    limited_scoring, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23, $24,
    $25, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    season = EXCLUDED.season,
    game_type = EXCLUDED.game_type,
    game_date = EXCLUDED.game_date,
    venue = EXCLUDED.venue,
    venue_location = EXCLUDED.venue_location,
    start_time_utc = EXCLUDED.start_time_utc,
    eastern_utc_offset = EXCLUDED.eastern_utc_offset,
    venue_utc_offset = EXCLUDED.venue_utc_offset,
    game_state = EXCLUDED.game_state,
    game_schedule_state = EXCLUDED.game_schedule_state,
    period_number = EXCLUDED.period_number,
    period_type = EXCLUDED.period_type,
    max_regulation_periods = EXCLUDED.max_regulation_periods,
    clock_time_remaining = EXCLUDED.clock_time_remaining,
    clock_seconds_remaining = EXCLUDED.clock_seconds_remaining,
    clock_running = EXCLUDED.clock_running,
    clock_in_intermission = EXCLUDED.clock_in_intermission,
    home_team_id = EXCLUDED.home_team_id,
    home_team_score = EXCLUDED.home_team_score,
    home_team_sog = EXCLUDED.home_team_sog,
    away_team_id = EXCLUDED.away_team_id,
    away_team_score = EXCLUDED.away_team_score,
    away_team_sog = EXCLUDED.away_team_sog,
    limited_scoring = EXCLUDED.limited_scoring,
    updated_at = NOW()
WHERE (games.season, games.game_type, games.game_date,
       games.venue, games.venue_location,
       games.start_time_utc, games.eastern_utc_offset, games.venue_utc_offset,
       games.game_state, games.game_schedule_state,
       games.period_number, games.period_type, games.max_regulation_periods,
       games.clock_time_remaining, games.clock_seconds_remaining,
       games.clock_running, games.clock_in_intermission,
       games.home_team_id, games.home_team_score, games.home_team_sog,
       games.away_team_id, games.away_team_score, games.away_team_sog,
       games.limited_scoring)
      IS DISTINCT FROM
      (EXCLUDED.season, EXCLUDED.game_type, EXCLUDED.game_date,
       EXCLUDED.venue, EXCLUDED.venue_location,
       EXCLUDED.start_time_utc, EXCLUDED.eastern_utc_offset, EXCLUDED.venue_utc_offset,
       EXCLUDED.game_state, EXCLUDED.game_schedule_state,
       EXCLUDED.period_number, EXCLUDED.period_type, EXCLUDED.max_regulation_periods,
       EXCLUDED.clock_time_remaining, EXCLUDED.clock_seconds_remaining,
       EXCLUDED.clock_running, EXCLUDED.clock_in_intermission,
       EXCLUDED.home_team_id, EXCLUDED.home_team_score, EXCLUDED.home_team_sog,
       EXCLUDED.away_team_id, EXCLUDED.away_team_score, EXCLUDED.away_team_sog,
       EXCLUDED.limited_scoring)
`

type UpsertGameParams struct {
	ID                    int64              `json:"id"`
	Season                int32              `json:"season"`
	GameType              GameType           `json:"game_type"`
	GameDate              pgtype.Date        `json:"game_date"`
	Venue                 string             `json:"venue"`
	VenueLocation         string             `json:"venue_location"`
	StartTimeUTC          pgtype.Timestamptz `json:"start_time_utc"`
	EasternUTCOffset      string             `json:"eastern_utc_offset"`
	VenueUTCOffset        string             `json:"venue_utc_offset"`
	GameState             GameState          `json:"game_state"`
	GameScheduleState     GameScheduleState  `json:"game_schedule_state"`
	PeriodNumber          int16              `json:"period_number"`
	PeriodType            PeriodType         `json:"period_type"`
	MaxRegulationPeriods  int16              `json:"max_regulation_periods"`
	ClockTimeRemaining    string             `json:"clock_time_remaining"`
	ClockSecondsRemaining int32              `json:"clock_seconds_remaining"`
	ClockRunning          bool               `json:"clock_running"`
	ClockInIntermission   bool               `json:"clock_in_intermission"`
	HomeTeamID            int64              `json:"home_team_id"`
	HomeTeamScore         int32              `json:"home_team_score"`
	HomeTeamSog           int32              `json:"home_team_sog"`
	AwayTeamID            int64              `json:"away_team_id"`
	AwayTeamScore         int32              `json:"away_team_score"`
	AwayTeamSog           int32              `json:"away_team_sog"`
	LimitedScoring        bool               `json:"limited_scoring"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.Exec(ctx, upsertGame,
		arg.ID,
		arg.Season,
		arg.GameType,
		arg.GameDate,
		arg.Venue,
		arg.VenueLocation,
		arg.StartTimeUTC,
		arg.EasternUTCOffset,
		arg.VenueUTCOffset,
		arg.GameState,
		arg.GameScheduleState,
		arg.PeriodNumber,
		arg.PeriodType,
		arg.MaxRegulationPeriods,
		arg.ClockTimeRemaining,
		arg.ClockSecondsRemaining,
		arg.ClockRunning,
		arg.ClockInIntermission,
		arg.HomeTeamID,
		arg.HomeTeamScore,
		arg.HomeTeamSog,
		arg.AwayTeamID,
		arg.AwayTeamScore,
		arg.AwayTeamSog,
		arg.LimitedScoring,
	)
	return err
}
