// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nhl_seasons.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNHLSeasonTeams = `-- name: CountNHLSeasonTeams :one
SELECT COUNT(*) FROM nhl_season_teams
`

func (q *Queries) CountNHLSeasonTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLSeasonTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNHLSeasonTeamsForSeason = `-- name: CountNHLSeasonTeamsForSeason :one
SELECT COUNT(*) FROM nhl_season_teams WHERE season_id = $1
`

func (q *Queries) CountNHLSeasonTeamsForSeason(ctx context.Context, seasonID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLSeasonTeamsForSeason, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNHLSeasons = `-- name: CountNHLSeasons :one
SELECT COUNT(*) FROM nhl_seasons
`

func (q *Queries) CountNHLSeasons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNHLSeasons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllNHLSeasons = `-- name: GetAllNHLSeasons :many
SELECT id, standings_start, standings_end
FROM nhl_seasons
ORDER BY id DESC
`

func (q *Queries) GetAllNHLSeasons(ctx context.Context) ([]NhlSeason, error) {
	rows, err := q.db.Query(ctx, getAllNHLSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NhlSeason{}
	for rows.Next() {
		var i NhlSeason
		if err := rows.Scan(&i.ID, &i.StandingsStart, &i.StandingsEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDivisions = `-- name: GetDistinctDivisions :many
SELECT DISTINCT division_name, division_abbrev, conference_name, conference_abbrev
FROM nhl_season_teams
WHERE season_id = $1
ORDER BY conference_name, division_name
`

type GetDistinctDivisionsRow struct {
	DivisionName     string      `json:"division_name"`
	DivisionAbbrev   string      `json:"division_abbrev"`
	ConferenceName   pgtype.Text `json:"conference_name"`
	ConferenceAbbrev pgtype.Text `json:"conference_abbrev"`
}

func (q *Queries) GetDistinctDivisions(ctx context.Context, seasonID int32) ([]GetDistinctDivisionsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctDivisions, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctDivisionsRow{}
	for rows.Next() {
		var i GetDistinctDivisionsRow
		if err := rows.Scan(
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLSeason = `-- name: GetNHLSeason :one
SELECT id, standings_start, standings_end
FROM nhl_seasons
WHERE id = $1
`

func (q *Queries) GetNHLSeason(ctx context.Context, id int32) (NhlSeason, error) {
	row := q.db.QueryRow(ctx, getNHLSeason, id)
	var i NhlSeason
	err := row.Scan(&i.ID, &i.StandingsStart, &i.StandingsEnd)
	return i, err
}

const getNHLSeasonTeam = `-- name: GetNHLSeasonTeam :one
SELECT
    season_id, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
FROM nhl_season_teams
WHERE season_id = $1 AND team_id = $2
`

type GetNHLSeasonTeamParams struct {
	SeasonID int32 `json:"season_id"`
	TeamID   int64 `json:"team_id"`
}

func (q *Queries) GetNHLSeasonTeam(ctx context.Context, arg GetNHLSeasonTeamParams) (NhlSeasonTeam, error) {
	row := q.db.QueryRow(ctx, getNHLSeasonTeam, arg.SeasonID, arg.TeamID)
	var i NhlSeasonTeam
	err := row.Scan(
		&i.SeasonID,
		&i.TeamID,
		&i.FranchiseID,
		&i.FullName,
		&i.Abbrev,
		&i.LogoUrl,
		&i.DivisionName,
		&i.DivisionAbbrev,
		&i.ConferenceName,
		&i.ConferenceAbbrev,
	)
	return i, err
}

const getNHLSeasonTeams = `-- name: GetNHLSeasonTeams :many
SELECT
    season_id, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
FROM nhl_season_teams
WHERE season_id = $1
ORDER BY division_name, full_name
`

func (q *Queries) GetNHLSeasonTeams(ctx context.Context, seasonID int32) ([]NhlSeasonTeam, error) {
	rows, err := q.db.Query(ctx, getNHLSeasonTeams, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NhlSeasonTeam{}
	for rows.Next() {
		var i NhlSeasonTeam
		if err := rows.Scan(
			&i.SeasonID,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLSeasonTeamsByDivision = `-- name: GetNHLSeasonTeamsByDivision :many
SELECT
    season_id, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
FROM nhl_season_teams
WHERE season_id = $1 AND division_name = $2
ORDER BY full_name
`

type GetNHLSeasonTeamsByDivisionParams struct {
	SeasonID     int32  `json:"season_id"`
	DivisionName string `json:"division_name"`
}

func (q *Queries) GetNHLSeasonTeamsByDivision(ctx context.Context, arg GetNHLSeasonTeamsByDivisionParams) ([]NhlSeasonTeam, error) {
	rows, err := q.db.Query(ctx, getNHLSeasonTeamsByDivision, arg.SeasonID, arg.DivisionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NhlSeasonTeam{}
	for rows.Next() {
		var i NhlSeasonTeam
		if err := rows.Scan(
			&i.SeasonID,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNHLTeamHistory = `-- name: GetNHLTeamHistory :many
SELECT
    season_id, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
FROM nhl_season_teams
WHERE franchise_id = $1
ORDER BY season_id DESC
`

func (q *Queries) GetNHLTeamHistory(ctx context.Context, franchiseID pgtype.Int8) ([]NhlSeasonTeam, error) {
	rows, err := q.db.Query(ctx, getNHLTeamHistory, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NhlSeasonTeam{}
	for rows.Next() {
		var i NhlSeasonTeam
		if err := rows.Scan(
			&i.SeasonID,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNHLSeason = `-- name: UpsertNHLSeason :exec
INSERT INTO nhl_seasons (id, standings_start, standings_end)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    standings_start = EXCLUDED.standings_start,
    standings_end = EXCLUDED.standings_end
`

type UpsertNHLSeasonParams struct {
	ID             int32       `json:"id"`
	StandingsStart pgtype.Date `json:"standings_start"`
	StandingsEnd   pgtype.Date `json:"standings_end"`
}

func (q *Queries) UpsertNHLSeason(ctx context.Context, arg UpsertNHLSeasonParams) error {
	_, err := q.db.Exec(ctx, upsertNHLSeason, arg.ID, arg.StandingsStart, arg.StandingsEnd)
	return err
}

const upsertNHLSeasonTeam = `-- name: UpsertNHLSeasonTeam :exec
INSERT INTO nhl_season_teams (
    season_id, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (season_id, team_id) DO UPDATE SET
    franchise_id = EXCLUDED.franchise_id,
    full_name = EXCLUDED.full_name,
    abbrev = EXCLUDED.abbrev,
    logo_url = EXCLUDED.logo_url,
    division_name = EXCLUDED.division_name,
    division_abbrev = EXCLUDED.division_abbrev,
    conference_name = EXCLUDED.conference_name,
    conference_abbrev = EXCLUDED.conference_abbrev
`

type UpsertNHLSeasonTeamParams struct {
	SeasonID         int32       `json:"season_id"`
	TeamID           int64       `json:"team_id"`
	FranchiseID      pgtype.Int8 `json:"franchise_id"`
	FullName         string      `json:"full_name"`
	Abbrev           string      `json:"abbrev"`
	LogoUrl          pgtype.Text `json:"logo_url"`
	DivisionName     string      `json:"division_name"`
	DivisionAbbrev   string      `json:"division_abbrev"`
	ConferenceName   pgtype.Text `json:"conference_name"`
	ConferenceAbbrev pgtype.Text `json:"conference_abbrev"`
}

func (q *Queries) UpsertNHLSeasonTeam(ctx context.Context, arg UpsertNHLSeasonTeamParams) error {
	_, err := q.db.Exec(ctx, upsertNHLSeasonTeam,
		arg.SeasonID,
		arg.TeamID,
		arg.FranchiseID,
		arg.FullName,
		arg.Abbrev,
		arg.LogoUrl,
		arg.DivisionName,
		arg.DivisionAbbrev,
		arg.ConferenceName,
		arg.ConferenceAbbrev,
	)
	return err
}
