// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePlayers = `-- name: CountActivePlayers :one
SELECT COUNT(*) FROM players WHERE is_active = TRUE
`

func (q *Queries) CountActivePlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayers = `-- name: CountPlayers :one
SELECT COUNT(*) FROM players
`

func (q *Queries) CountPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getActivePlayers = `-- name: GetActivePlayers :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.is_active = TRUE
ORDER BY p.last_name, p.first_name
`

type GetActivePlayersRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetActivePlayers(ctx context.Context) ([]GetActivePlayersRow, error) {
	rows, err := q.db.Query(ctx, getActivePlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivePlayersRow{}
	for rows.Next() {
		var i GetActivePlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlayers = `-- name: GetAllPlayers :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
ORDER BY p.last_name, p.first_name
`

type GetAllPlayersRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetAllPlayers(ctx context.Context) ([]GetAllPlayersRow, error) {
	rows, err := q.db.Query(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllPlayersRow{}
	for rows.Next() {
		var i GetAllPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.id = $1
`

type GetPlayerRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetPlayer(ctx context.Context, id int64) (GetPlayerRow, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i GetPlayerRow
	err := row.Scan(
		&i.ID,
		&i.YahooID,
		&i.FirstName,
		&i.LastName,
		&i.NhlTeamID,
		&i.Position,
		&i.ShootsCatches,
		&i.HeightInches,
		&i.WeightPounds,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthStateProvince,
		&i.BirthCountry,
		&i.SweaterNumber,
		&i.IsActive,
		&i.HeadshotUrl,
		&i.HeroImageUrl,
		&i.YahooImageSmall,
		&i.YahooImageMedium,
		&i.YahooImageLarge,
		&i.YahooHomeUrl,
		&i.PlayerSlug,
		&i.DraftYear,
		&i.DraftTeamAbbrev,
		&i.DraftRound,
		&i.DraftPickInRound,
		&i.DraftOverallPick,
		&i.FirstNameNormalized,
		&i.LastNameNormalized,
		&i.TeamCity,
		&i.TeamName,
		&i.TeamAbbrev,
	)
	return i, err
}

const getPlayerByYahooID = `-- name: GetPlayerByYahooID :one
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.yahoo_id = $1
`

type GetPlayerByYahooIDRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetPlayerByYahooID(ctx context.Context, yahooID pgtype.Int8) (GetPlayerByYahooIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByYahooID, yahooID)
	var i GetPlayerByYahooIDRow
	err := row.Scan(
		&i.ID,
		&i.YahooID,
		&i.FirstName,
		&i.LastName,
		&i.NhlTeamID,
		&i.Position,
		&i.ShootsCatches,
		&i.HeightInches,
		&i.WeightPounds,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthStateProvince,
		&i.BirthCountry,
		&i.SweaterNumber,
		&i.IsActive,
		&i.HeadshotUrl,
		&i.HeroImageUrl,
		&i.YahooImageSmall,
		&i.YahooImageMedium,
		&i.YahooImageLarge,
		&i.YahooHomeUrl,
		&i.PlayerSlug,
		&i.DraftYear,
		&i.DraftTeamAbbrev,
		&i.DraftRound,
		&i.DraftPickInRound,
		&i.DraftOverallPick,
		&i.FirstNameNormalized,
		&i.LastNameNormalized,
		&i.TeamCity,
		&i.TeamName,
		&i.TeamAbbrev,
	)
	return i, err
}

const getPlayersByPosition = `-- name: GetPlayersByPosition :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.position = $1
ORDER BY p.last_name, p.first_name
`

type GetPlayersByPositionRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetPlayersByPosition(ctx context.Context, position string) ([]GetPlayersByPositionRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByPosition, position)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByPositionRow{}
	for rows.Next() {
		var i GetPlayersByPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByTeam = `-- name: GetPlayersByTeam :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.nhl_team_id = $1
ORDER BY p.last_name, p.first_name
`

type GetPlayersByTeamRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) GetPlayersByTeam(ctx context.Context, nhlTeamID pgtype.Int8) ([]GetPlayersByTeamRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByTeam, nhlTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByTeamRow{}
	for rows.Next() {
		var i GetPlayersByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkYahooToNHLPlayer = `-- name: LinkYahooToNHLPlayer :exec
UPDATE players SET yahoo_id = $2 WHERE id = $1
`

type LinkYahooToNHLPlayerParams struct {
	ID      int64       `json:"id"`
	YahooID pgtype.Int8 `json:"yahoo_id"`
}

// Link a Yahoo player ID to an existing NHL player
func (q *Queries) LinkYahooToNHLPlayer(ctx context.Context, arg LinkYahooToNHLPlayerParams) error {
	_, err := q.db.Exec(ctx, linkYahooToNHLPlayer, arg.ID, arg.YahooID)
	return err
}

const listPlayers = `-- name: ListPlayers :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE
    ($1::text IS NULL OR
     p.first_name ILIKE '%' || $1 || '%' OR
     p.last_name ILIKE '%' || $1 || '%')
    AND ($2::int IS NULL OR p.sweater_number = $2)
    AND ($3::boolean IS NULL OR
         (CASE WHEN $3 THEN p.yahoo_id IS NOT NULL ELSE p.yahoo_id IS NULL END))
    AND ($4::bigint IS NULL OR p.nhl_team_id = $4)
    AND ($5::text IS NULL OR p.position = $5)
    AND ($6::boolean IS NULL OR p.is_active = $6)
ORDER BY p.last_name, p.first_name
`

type ListPlayersParams struct {
	Name          pgtype.Text `json:"name"`
	SweaterNumber pgtype.Int4 `json:"sweater_number"`
	HasYahooID    pgtype.Bool `json:"has_yahoo_id"`
	TeamID        pgtype.Int8 `json:"team_id"`
	Position      pgtype.Text `json:"position"`
	IsActive      pgtype.Bool `json:"is_active"`
}

type ListPlayersRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers,
		arg.Name,
		arg.SweaterNumber,
		arg.HasYahooID,
		arg.TeamID,
		arg.Position,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersRow{}
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayersByName = `-- name: SearchPlayersByName :many
SELECT p.id, p.yahoo_id, p.first_name, p.last_name, p.nhl_team_id, p.position, p.shoots_catches, p.height_inches, p.weight_pounds, p.birth_date, p.birth_city, p.birth_state_province, p.birth_country, p.sweater_number, p.is_active, p.headshot_url, p.hero_image_url, p.yahoo_image_small, p.yahoo_image_medium, p.yahoo_image_large, p.yahoo_home_url, p.player_slug, p.draft_year, p.draft_team_abbrev, p.draft_round, p.draft_pick_in_round, p.draft_overall_pick, p.first_name_normalized, p.last_name_normalized, t.city as team_city, t.name as team_name, t.abbreviation as team_abbrev
FROM players p
LEFT JOIN nhl_teams t ON p.nhl_team_id = t.id
WHERE p.last_name_normalized LIKE $1 OR p.first_name_normalized LIKE $1
   OR p.last_name ILIKE $1 OR p.first_name ILIKE $1
ORDER BY p.last_name, p.first_name
LIMIT 50
`

type SearchPlayersByNameRow struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	TeamCity            pgtype.Text `json:"team_city"`
	TeamName            pgtype.Text `json:"team_name"`
	TeamAbbrev          pgtype.Text `json:"team_abbrev"`
}

// Search by name using normalized columns for accent-insensitive matching
func (q *Queries) SearchPlayersByName(ctx context.Context, lastNameNormalized string) ([]SearchPlayersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchPlayersByName, lastNameNormalized)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersByNameRow{}
	for rows.Next() {
		var i SearchPlayersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.YahooID,
			&i.FirstName,
			&i.LastName,
			&i.NhlTeamID,
			&i.Position,
			&i.ShootsCatches,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.SweaterNumber,
			&i.IsActive,
			&i.HeadshotUrl,
			&i.HeroImageUrl,
			&i.YahooImageSmall,
			&i.YahooImageMedium,
			&i.YahooImageLarge,
			&i.YahooHomeUrl,
			&i.PlayerSlug,
			&i.DraftYear,
			&i.DraftTeamAbbrev,
			&i.DraftRound,
			&i.DraftPickInRound,
			&i.DraftOverallPick,
			&i.FirstNameNormalized,
			&i.LastNameNormalized,
			&i.TeamCity,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerYahooInfo = `-- name: UpdatePlayerYahooInfo :exec
UPDATE players SET
    yahoo_id = $2,
    yahoo_image_small = $3,
    yahoo_image_medium = $4,
    yahoo_image_large = $5,
    yahoo_home_url = $6
WHERE id = $1
`

type UpdatePlayerYahooInfoParams struct {
	ID               int64       `json:"id"`
	YahooID          pgtype.Int8 `json:"yahoo_id"`
	YahooImageSmall  string      `json:"yahoo_image_small"`
	YahooImageMedium string      `json:"yahoo_image_medium"`
	YahooImageLarge  string      `json:"yahoo_image_large"`
	YahooHomeUrl     string      `json:"yahoo_home_url"`
}

// Use this when importing from Yahoo API (updates Yahoo-specific fields)
func (q *Queries) UpdatePlayerYahooInfo(ctx context.Context, arg UpdatePlayerYahooInfoParams) error {
	_, err := q.db.Exec(ctx, updatePlayerYahooInfo,
		arg.ID,
		arg.YahooID,
		arg.YahooImageSmall,
		arg.YahooImageMedium,
		arg.YahooImageLarge,
		arg.YahooHomeUrl,
	)
	return err
}

const upsertPlayer = `-- name: UpsertPlayer :exec
INSERT INTO players (
    id, yahoo_id, first_name, last_name, first_name_normalized, last_name_normalized, nhl_team_id,
    position, shoots_catches, height_inches, weight_pounds,
    birth_date, birth_city, birth_state_province, birth_country,
    sweater_number, is_active, headshot_url, hero_image_url,
    yahoo_image_small, yahoo_image_medium, yahoo_image_large,
    yahoo_home_url, player_slug,
    draft_year, draft_team_abbrev, draft_round, draft_pick_in_round, draft_overall_pick
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22,
    $23, $24,
    $25, $26, $27, $28, $29
)
ON CONFLICT (id) DO UPDATE SET
    yahoo_id = COALESCE(EXCLUDED.yahoo_id, players.yahoo_id),
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    first_name_normalized = EXCLUDED.first_name_normalized,
    last_name_normalized = EXCLUDED.last_name_normalized,
    nhl_team_id = EXCLUDED.nhl_team_id,
    position = EXCLUDED.position,
    shoots_catches = EXCLUDED.shoots_catches,
    height_inches = COALESCE(EXCLUDED.height_inches, players.height_inches),
    weight_pounds = COALESCE(EXCLUDED.weight_pounds, players.weight_pounds),
    birth_date = COALESCE(EXCLUDED.birth_date, players.birth_date),
    birth_city = COALESCE(EXCLUDED.birth_city, players.birth_city),
    birth_state_province = COALESCE(EXCLUDED.birth_state_province, players.birth_state_province),
    birth_country = COALESCE(EXCLUDED.birth_country, players.birth_country),
    sweater_number = COALESCE(EXCLUDED.sweater_number, players.sweater_number),
    is_active = EXCLUDED.is_active,
    headshot_url = CASE WHEN EXCLUDED.headshot_url != '' THEN EXCLUDED.headshot_url ELSE players.headshot_url END,
    hero_image_url = COALESCE(EXCLUDED.hero_image_url, players.hero_image_url),
    yahoo_image_small = CASE WHEN EXCLUDED.yahoo_image_small != '' THEN EXCLUDED.yahoo_image_small ELSE players.yahoo_image_small END,
    yahoo_image_medium = CASE WHEN EXCLUDED.yahoo_image_medium != '' THEN EXCLUDED.yahoo_image_medium ELSE players.yahoo_image_medium END,
    yahoo_image_large = CASE WHEN EXCLUDED.yahoo_image_large != '' THEN EXCLUDED.yahoo_image_large ELSE players.yahoo_image_large END,
    yahoo_home_url = CASE WHEN EXCLUDED.yahoo_home_url != '' THEN EXCLUDED.yahoo_home_url ELSE players.yahoo_home_url END,
    player_slug = COALESCE(EXCLUDED.player_slug, players.player_slug),
    draft_year = COALESCE(EXCLUDED.draft_year, players.draft_year),
    draft_team_abbrev = COALESCE(EXCLUDED.draft_team_abbrev, players.draft_team_abbrev),
    draft_round = COALESCE(EXCLUDED.draft_round, players.draft_round),
    draft_pick_in_round = COALESCE(EXCLUDED.draft_pick_in_round, players.draft_pick_in_round),
    draft_overall_pick = COALESCE(EXCLUDED.draft_overall_pick, players.draft_overall_pick)
`

type UpsertPlayerParams struct {
	ID                  int64       `json:"id"`
	YahooID             pgtype.Int8 `json:"yahoo_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	FirstNameNormalized string      `json:"first_name_normalized"`
	LastNameNormalized  string      `json:"last_name_normalized"`
	NhlTeamID           pgtype.Int8 `json:"nhl_team_id"`
	Position            string      `json:"position"`
	ShootsCatches       string      `json:"shoots_catches"`
	HeightInches        pgtype.Int4 `json:"height_inches"`
	WeightPounds        pgtype.Int4 `json:"weight_pounds"`
	BirthDate           pgtype.Date `json:"birth_date"`
	BirthCity           pgtype.Text `json:"birth_city"`
	BirthStateProvince  pgtype.Text `json:"birth_state_province"`
	BirthCountry        pgtype.Text `json:"birth_country"`
	SweaterNumber       pgtype.Int4 `json:"sweater_number"`
	IsActive            bool        `json:"is_active"`
	HeadshotUrl         string      `json:"headshot_url"`
	HeroImageUrl        pgtype.Text `json:"hero_image_url"`
	YahooImageSmall     string      `json:"yahoo_image_small"`
	YahooImageMedium    string      `json:"yahoo_image_medium"`
	YahooImageLarge     string      `json:"yahoo_image_large"`
	YahooHomeUrl        string      `json:"yahoo_home_url"`
	PlayerSlug          pgtype.Text `json:"player_slug"`
	DraftYear           pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev     pgtype.Text `json:"draft_team_abbrev"`
	DraftRound          pgtype.Int4 `json:"draft_round"`
	DraftPickInRound    pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick    pgtype.Int4 `json:"draft_overall_pick"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) error {
	_, err := q.db.Exec(ctx, upsertPlayer,
		arg.ID,
		arg.YahooID,
		arg.FirstName,
		arg.LastName,
		arg.FirstNameNormalized,
		arg.LastNameNormalized,
		arg.NhlTeamID,
		arg.Position,
		arg.ShootsCatches,
		arg.HeightInches,
		arg.WeightPounds,
		arg.BirthDate,
		arg.BirthCity,
		arg.BirthStateProvince,
		arg.BirthCountry,
		arg.SweaterNumber,
		arg.IsActive,
		arg.HeadshotUrl,
		arg.HeroImageUrl,
		arg.YahooImageSmall,
		arg.YahooImageMedium,
		arg.YahooImageLarge,
		arg.YahooHomeUrl,
		arg.PlayerSlug,
		arg.DraftYear,
		arg.DraftTeamAbbrev,
		arg.DraftRound,
		arg.DraftPickInRound,
		arg.DraftOverallPick,
	)
	return err
}

const upsertPlayerFromNHL = `-- name: UpsertPlayerFromNHL :exec
INSERT INTO players (
    id, first_name, last_name, nhl_team_id,
    position, shoots_catches, height_inches, weight_pounds,
    birth_date, birth_city, birth_state_province, birth_country,
    sweater_number, is_active, headshot_url, hero_image_url, player_slug,
    draft_year, draft_team_abbrev, draft_round, draft_pick_in_round, draft_overall_pick
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22
)
ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    nhl_team_id = EXCLUDED.nhl_team_id,
    position = EXCLUDED.position,
    shoots_catches = EXCLUDED.shoots_catches,
    height_inches = EXCLUDED.height_inches,
    weight_pounds = EXCLUDED.weight_pounds,
    birth_date = EXCLUDED.birth_date,
    birth_city = EXCLUDED.birth_city,
    birth_state_province = EXCLUDED.birth_state_province,
    birth_country = EXCLUDED.birth_country,
    sweater_number = EXCLUDED.sweater_number,
    is_active = EXCLUDED.is_active,
    headshot_url = EXCLUDED.headshot_url,
    hero_image_url = EXCLUDED.hero_image_url,
    player_slug = EXCLUDED.player_slug,
    draft_year = EXCLUDED.draft_year,
    draft_team_abbrev = EXCLUDED.draft_team_abbrev,
    draft_round = EXCLUDED.draft_round,
    draft_pick_in_round = EXCLUDED.draft_pick_in_round,
    draft_overall_pick = EXCLUDED.draft_overall_pick
`

type UpsertPlayerFromNHLParams struct {
	ID                 int64       `json:"id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	NhlTeamID          pgtype.Int8 `json:"nhl_team_id"`
	Position           string      `json:"position"`
	ShootsCatches      string      `json:"shoots_catches"`
	HeightInches       pgtype.Int4 `json:"height_inches"`
	WeightPounds       pgtype.Int4 `json:"weight_pounds"`
	BirthDate          pgtype.Date `json:"birth_date"`
	BirthCity          pgtype.Text `json:"birth_city"`
	BirthStateProvince pgtype.Text `json:"birth_state_province"`
	BirthCountry       pgtype.Text `json:"birth_country"`
	SweaterNumber      pgtype.Int4 `json:"sweater_number"`
	IsActive           bool        `json:"is_active"`
	HeadshotUrl        string      `json:"headshot_url"`
	HeroImageUrl       pgtype.Text `json:"hero_image_url"`
	PlayerSlug         pgtype.Text `json:"player_slug"`
	DraftYear          pgtype.Int4 `json:"draft_year"`
	DraftTeamAbbrev    pgtype.Text `json:"draft_team_abbrev"`
	DraftRound         pgtype.Int4 `json:"draft_round"`
	DraftPickInRound   pgtype.Int4 `json:"draft_pick_in_round"`
	DraftOverallPick   pgtype.Int4 `json:"draft_overall_pick"`
}

// Use this when importing from NHL API (has NHL ID as primary)
func (q *Queries) UpsertPlayerFromNHL(ctx context.Context, arg UpsertPlayerFromNHLParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerFromNHL,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.NhlTeamID,
		arg.Position,
		arg.ShootsCatches,
		arg.HeightInches,
		arg.WeightPounds,
		arg.BirthDate,
		arg.BirthCity,
		arg.BirthStateProvince,
		arg.BirthCountry,
		arg.SweaterNumber,
		arg.IsActive,
		arg.HeadshotUrl,
		arg.HeroImageUrl,
		arg.PlayerSlug,
		arg.DraftYear,
		arg.DraftTeamAbbrev,
		arg.DraftRound,
		arg.DraftPickInRound,
		arg.DraftOverallPick,
	)
	return err
}
