// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season_rosters.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSeasonRosters = `-- name: CountSeasonRosters :one
SELECT COUNT(*) FROM season_rosters
`

func (q *Queries) CountSeasonRosters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasonRosters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSeasonRostersBySeason = `-- name: CountSeasonRostersBySeason :one
SELECT COUNT(*) FROM season_rosters WHERE season = $1
`

func (q *Queries) CountSeasonRostersBySeason(ctx context.Context, season int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasonRostersBySeason, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSeasonRosterByPlayer = `-- name: GetSeasonRosterByPlayer :many
SELECT r.season, r.team_id, r.player_id, r.position, r.shoots_catches, r.sweater_number, r.height_inches, r.weight_pounds, r.birth_date, r.birth_city, r.birth_state_province, r.birth_country, r.created_at, r.updated_at, st.full_name as team_name, st.abbrev as team_abbrev
FROM season_rosters r
JOIN season_teams st ON st.season = r.season AND st.team_id = r.team_id
WHERE r.player_id = $1
ORDER BY r.season DESC
`

type GetSeasonRosterByPlayerRow struct {
	Season             int32              `json:"season"`
	TeamID             int64              `json:"team_id"`
	PlayerID           int64              `json:"player_id"`
	Position           NullPlayerPosition `json:"position"`
	ShootsCatches      string             `json:"shoots_catches"`
	SweaterNumber      int16              `json:"sweater_number"`
	HeightInches       int16              `json:"height_inches"`
	WeightPounds       int16              `json:"weight_pounds"`
	BirthDate          string             `json:"birth_date"`
	BirthCity          pgtype.Text        `json:"birth_city"`
	BirthStateProvince pgtype.Text        `json:"birth_state_province"`
	BirthCountry       string             `json:"birth_country"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TeamName           string             `json:"team_name"`
	TeamAbbrev         string             `json:"team_abbrev"`
}

func (q *Queries) GetSeasonRosterByPlayer(ctx context.Context, playerID int64) ([]GetSeasonRosterByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getSeasonRosterByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeasonRosterByPlayerRow{}
	for rows.Next() {
		var i GetSeasonRosterByPlayerRow
		if err := rows.Scan(
			&i.Season,
			&i.TeamID,
			&i.PlayerID,
			&i.Position,
			&i.ShootsCatches,
			&i.SweaterNumber,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamName,
			&i.TeamAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonRosterByTeam = `-- name: GetSeasonRosterByTeam :many
SELECT r.season, r.team_id, r.player_id, r.position, r.shoots_catches, r.sweater_number, r.height_inches, r.weight_pounds, r.birth_date, r.birth_city, r.birth_state_province, r.birth_country, r.created_at, r.updated_at, p.first_name, p.last_name
FROM season_rosters r
JOIN players p ON r.player_id = p.id
WHERE r.season = $1 AND r.team_id = $2
ORDER BY r.position, p.last_name
`

type GetSeasonRosterByTeamParams struct {
	Season int32 `json:"season"`
	TeamID int64 `json:"team_id"`
}

type GetSeasonRosterByTeamRow struct {
	Season             int32              `json:"season"`
	TeamID             int64              `json:"team_id"`
	PlayerID           int64              `json:"player_id"`
	Position           NullPlayerPosition `json:"position"`
	ShootsCatches      string             `json:"shoots_catches"`
	SweaterNumber      int16              `json:"sweater_number"`
	HeightInches       int16              `json:"height_inches"`
	WeightPounds       int16              `json:"weight_pounds"`
	BirthDate          string             `json:"birth_date"`
	BirthCity          pgtype.Text        `json:"birth_city"`
	BirthStateProvince pgtype.Text        `json:"birth_state_province"`
	BirthCountry       string             `json:"birth_country"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
}

func (q *Queries) GetSeasonRosterByTeam(ctx context.Context, arg GetSeasonRosterByTeamParams) ([]GetSeasonRosterByTeamRow, error) {
	rows, err := q.db.Query(ctx, getSeasonRosterByTeam, arg.Season, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeasonRosterByTeamRow{}
	for rows.Next() {
		var i GetSeasonRosterByTeamRow
		if err := rows.Scan(
			&i.Season,
			&i.TeamID,
			&i.PlayerID,
			&i.Position,
			&i.ShootsCatches,
			&i.SweaterNumber,
			&i.HeightInches,
			&i.WeightPounds,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthStateProvince,
			&i.BirthCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonTeamAbbrevs = `-- name: GetSeasonTeamAbbrevs :many
SELECT team_id, abbrev FROM season_teams
WHERE season = $1
ORDER BY abbrev
`

type GetSeasonTeamAbbrevsRow struct {
	TeamID int64  `json:"team_id"`
	Abbrev string `json:"abbrev"`
}

func (q *Queries) GetSeasonTeamAbbrevs(ctx context.Context, season int32) ([]GetSeasonTeamAbbrevsRow, error) {
	rows, err := q.db.Query(ctx, getSeasonTeamAbbrevs, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeasonTeamAbbrevsRow{}
	for rows.Next() {
		var i GetSeasonTeamAbbrevsRow
		if err := rows.Scan(&i.TeamID, &i.Abbrev); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
