// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: yahoo_leagues.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countYahooLeagues = `-- name: CountYahooLeagues :one
SELECT COUNT(*) FROM yahoo_leagues
`

func (q *Queries) CountYahooLeagues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countYahooLeagues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countYahooLeaguesBySeason = `-- name: CountYahooLeaguesBySeason :one
SELECT COUNT(*) FROM yahoo_leagues WHERE season = $1
`

func (q *Queries) CountYahooLeaguesBySeason(ctx context.Context, season int32) (int64, error) {
	row := q.db.QueryRow(ctx, countYahooLeaguesBySeason, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countYahooTeams = `-- name: CountYahooTeams :one
SELECT COUNT(*) FROM yahoo_teams
`

func (q *Queries) CountYahooTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countYahooTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countYahooTeamsByLeague = `-- name: CountYahooTeamsByLeague :one
SELECT COUNT(*) FROM yahoo_teams WHERE league_id = $1
`

func (q *Queries) CountYahooTeamsByLeague(ctx context.Context, leagueID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countYahooTeamsByLeague, leagueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteYahooLeague = `-- name: DeleteYahooLeague :exec
DELETE FROM yahoo_leagues WHERE id = $1
`

func (q *Queries) DeleteYahooLeague(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteYahooLeague, id)
	return err
}

const deleteYahooLeagueRosterPositions = `-- name: DeleteYahooLeagueRosterPositions :exec
DELETE FROM yahoo_league_roster_positions WHERE league_id = $1
`

func (q *Queries) DeleteYahooLeagueRosterPositions(ctx context.Context, leagueID int32) error {
	_, err := q.db.Exec(ctx, deleteYahooLeagueRosterPositions, leagueID)
	return err
}

const deleteYahooLeagueStatCategories = `-- name: DeleteYahooLeagueStatCategories :exec
DELETE FROM yahoo_league_stat_categories WHERE league_id = $1
`

func (q *Queries) DeleteYahooLeagueStatCategories(ctx context.Context, leagueID int32) error {
	_, err := q.db.Exec(ctx, deleteYahooLeagueStatCategories, leagueID)
	return err
}

const deleteYahooTeam = `-- name: DeleteYahooTeam :exec
DELETE FROM yahoo_teams WHERE league_id = $1 AND id = $2
`

type DeleteYahooTeamParams struct {
	LeagueID int32 `json:"league_id"`
	ID       int32 `json:"id"`
}

func (q *Queries) DeleteYahooTeam(ctx context.Context, arg DeleteYahooTeamParams) error {
	_, err := q.db.Exec(ctx, deleteYahooTeam, arg.LeagueID, arg.ID)
	return err
}

const deleteYahooTeamManagers = `-- name: DeleteYahooTeamManagers :exec
DELETE FROM yahoo_team_managers WHERE league_id = $1 AND team_id = $2
`

type DeleteYahooTeamManagersParams struct {
	LeagueID int32 `json:"league_id"`
	TeamID   int32 `json:"team_id"`
}

func (q *Queries) DeleteYahooTeamManagers(ctx context.Context, arg DeleteYahooTeamManagersParams) error {
	_, err := q.db.Exec(ctx, deleteYahooTeamManagers, arg.LeagueID, arg.TeamID)
	return err
}

const deleteYahooTeamManagersByLeague = `-- name: DeleteYahooTeamManagersByLeague :exec
DELETE FROM yahoo_team_managers WHERE league_id = $1
`

func (q *Queries) DeleteYahooTeamManagersByLeague(ctx context.Context, leagueID int32) error {
	_, err := q.db.Exec(ctx, deleteYahooTeamManagersByLeague, leagueID)
	return err
}

const deleteYahooTeamsByLeague = `-- name: DeleteYahooTeamsByLeague :exec
DELETE FROM yahoo_teams WHERE league_id = $1
`

func (q *Queries) DeleteYahooTeamsByLeague(ctx context.Context, leagueID int32) error {
	_, err := q.db.Exec(ctx, deleteYahooTeamsByLeague, leagueID)
	return err
}

const getAllYahooLeagues = `-- name: GetAllYahooLeagues :many
SELECT id, league_key, name, url, logo_url, season, game_code, num_teams, scoring_type, league_type, draft_status, is_pro_league, is_cash_league, start_date, end_date, draft_type, is_auction_draft, draft_time, draft_pick_time, waiver_type, waiver_rule, waiver_time, trade_end_date, trade_ratify_type, trade_reject_time, max_teams, player_pool, post_draft_players, cant_cut_list, uses_playoff, persistent_url, league_update_timestamp, created_at, updated_at FROM yahoo_leagues ORDER BY season DESC, name
`

func (q *Queries) GetAllYahooLeagues(ctx context.Context) ([]YahooLeague, error) {
	rows, err := q.db.Query(ctx, getAllYahooLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeague{}
	for rows.Next() {
		var i YahooLeague
		if err := rows.Scan(
			&i.ID,
			&i.LeagueKey,
			&i.Name,
			&i.Url,
			&i.LogoUrl,
			&i.Season,
			&i.GameCode,
			&i.NumTeams,
			&i.ScoringType,
			&i.LeagueType,
			&i.DraftStatus,
			&i.IsProLeague,
			&i.IsCashLeague,
			&i.StartDate,
			&i.EndDate,
			&i.DraftType,
			&i.IsAuctionDraft,
			&i.DraftTime,
			&i.DraftPickTime,
			&i.WaiverType,
			&i.WaiverRule,
			&i.WaiverTime,
			&i.TradeEndDate,
			&i.TradeRatifyType,
			&i.TradeRejectTime,
			&i.MaxTeams,
			&i.PlayerPool,
			&i.PostDraftPlayers,
			&i.CantCutList,
			&i.UsesPlayoff,
			&i.PersistentUrl,
			&i.LeagueUpdateTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooLeague = `-- name: GetYahooLeague :one

SELECT id, league_key, name, url, logo_url, season, game_code, num_teams, scoring_type, league_type, draft_status, is_pro_league, is_cash_league, start_date, end_date, draft_type, is_auction_draft, draft_time, draft_pick_time, waiver_type, waiver_rule, waiver_time, trade_end_date, trade_ratify_type, trade_reject_time, max_teams, player_pool, post_draft_players, cant_cut_list, uses_playoff, persistent_url, league_update_timestamp, created_at, updated_at FROM yahoo_leagues WHERE id = $1
`

// =============================================================================
// Yahoo Leagues
// =============================================================================
func (q *Queries) GetYahooLeague(ctx context.Context, id int32) (YahooLeague, error) {
	row := q.db.QueryRow(ctx, getYahooLeague, id)
	var i YahooLeague
	err := row.Scan(
		&i.ID,
		&i.LeagueKey,
		&i.Name,
		&i.Url,
		&i.LogoUrl,
		&i.Season,
		&i.GameCode,
		&i.NumTeams,
		&i.ScoringType,
		&i.LeagueType,
		&i.DraftStatus,
		&i.IsProLeague,
		&i.IsCashLeague,
		&i.StartDate,
		&i.EndDate,
		&i.DraftType,
		&i.IsAuctionDraft,
		&i.DraftTime,
		&i.DraftPickTime,
		&i.WaiverType,
		&i.WaiverRule,
		&i.WaiverTime,
		&i.TradeEndDate,
		&i.TradeRatifyType,
		&i.TradeRejectTime,
		&i.MaxTeams,
		&i.PlayerPool,
		&i.PostDraftPlayers,
		&i.CantCutList,
		&i.UsesPlayoff,
		&i.PersistentUrl,
		&i.LeagueUpdateTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYahooLeagueByKey = `-- name: GetYahooLeagueByKey :one
SELECT id, league_key, name, url, logo_url, season, game_code, num_teams, scoring_type, league_type, draft_status, is_pro_league, is_cash_league, start_date, end_date, draft_type, is_auction_draft, draft_time, draft_pick_time, waiver_type, waiver_rule, waiver_time, trade_end_date, trade_ratify_type, trade_reject_time, max_teams, player_pool, post_draft_players, cant_cut_list, uses_playoff, persistent_url, league_update_timestamp, created_at, updated_at FROM yahoo_leagues WHERE league_key = $1
`

func (q *Queries) GetYahooLeagueByKey(ctx context.Context, leagueKey string) (YahooLeague, error) {
	row := q.db.QueryRow(ctx, getYahooLeagueByKey, leagueKey)
	var i YahooLeague
	err := row.Scan(
		&i.ID,
		&i.LeagueKey,
		&i.Name,
		&i.Url,
		&i.LogoUrl,
		&i.Season,
		&i.GameCode,
		&i.NumTeams,
		&i.ScoringType,
		&i.LeagueType,
		&i.DraftStatus,
		&i.IsProLeague,
		&i.IsCashLeague,
		&i.StartDate,
		&i.EndDate,
		&i.DraftType,
		&i.IsAuctionDraft,
		&i.DraftTime,
		&i.DraftPickTime,
		&i.WaiverType,
		&i.WaiverRule,
		&i.WaiverTime,
		&i.TradeEndDate,
		&i.TradeRatifyType,
		&i.TradeRejectTime,
		&i.MaxTeams,
		&i.PlayerPool,
		&i.PostDraftPlayers,
		&i.CantCutList,
		&i.UsesPlayoff,
		&i.PersistentUrl,
		&i.LeagueUpdateTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYahooLeagueEnabledStatCategories = `-- name: GetYahooLeagueEnabledStatCategories :many
SELECT league_id, stat_id, name, abbr, stat_group, enabled, value FROM yahoo_league_stat_categories
WHERE league_id = $1 AND enabled = TRUE
ORDER BY stat_group, name
`

func (q *Queries) GetYahooLeagueEnabledStatCategories(ctx context.Context, leagueID int32) ([]YahooLeagueStatCategory, error) {
	rows, err := q.db.Query(ctx, getYahooLeagueEnabledStatCategories, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeagueStatCategory{}
	for rows.Next() {
		var i YahooLeagueStatCategory
		if err := rows.Scan(
			&i.LeagueID,
			&i.StatID,
			&i.Name,
			&i.Abbr,
			&i.StatGroup,
			&i.Enabled,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooLeagueRosterPositions = `-- name: GetYahooLeagueRosterPositions :many

SELECT league_id, position, position_type, count, is_starting_position FROM yahoo_league_roster_positions
WHERE league_id = $1
ORDER BY is_starting_position DESC, position
`

// =============================================================================
// Yahoo League Roster Positions
// =============================================================================
func (q *Queries) GetYahooLeagueRosterPositions(ctx context.Context, leagueID int32) ([]YahooLeagueRosterPosition, error) {
	rows, err := q.db.Query(ctx, getYahooLeagueRosterPositions, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeagueRosterPosition{}
	for rows.Next() {
		var i YahooLeagueRosterPosition
		if err := rows.Scan(
			&i.LeagueID,
			&i.Position,
			&i.PositionType,
			&i.Count,
			&i.IsStartingPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooLeagueStartingPositions = `-- name: GetYahooLeagueStartingPositions :many
SELECT league_id, position, position_type, count, is_starting_position FROM yahoo_league_roster_positions
WHERE league_id = $1 AND is_starting_position = TRUE
ORDER BY position
`

func (q *Queries) GetYahooLeagueStartingPositions(ctx context.Context, leagueID int32) ([]YahooLeagueRosterPosition, error) {
	rows, err := q.db.Query(ctx, getYahooLeagueStartingPositions, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeagueRosterPosition{}
	for rows.Next() {
		var i YahooLeagueRosterPosition
		if err := rows.Scan(
			&i.LeagueID,
			&i.Position,
			&i.PositionType,
			&i.Count,
			&i.IsStartingPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooLeagueStatCategories = `-- name: GetYahooLeagueStatCategories :many

SELECT league_id, stat_id, name, abbr, stat_group, enabled, value FROM yahoo_league_stat_categories
WHERE league_id = $1
ORDER BY stat_group, name
`

// =============================================================================
// Yahoo League Stat Categories
// =============================================================================
func (q *Queries) GetYahooLeagueStatCategories(ctx context.Context, leagueID int32) ([]YahooLeagueStatCategory, error) {
	rows, err := q.db.Query(ctx, getYahooLeagueStatCategories, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeagueStatCategory{}
	for rows.Next() {
		var i YahooLeagueStatCategory
		if err := rows.Scan(
			&i.LeagueID,
			&i.StatID,
			&i.Name,
			&i.Abbr,
			&i.StatGroup,
			&i.Enabled,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooLeaguesBySeason = `-- name: GetYahooLeaguesBySeason :many
SELECT id, league_key, name, url, logo_url, season, game_code, num_teams, scoring_type, league_type, draft_status, is_pro_league, is_cash_league, start_date, end_date, draft_type, is_auction_draft, draft_time, draft_pick_time, waiver_type, waiver_rule, waiver_time, trade_end_date, trade_ratify_type, trade_reject_time, max_teams, player_pool, post_draft_players, cant_cut_list, uses_playoff, persistent_url, league_update_timestamp, created_at, updated_at FROM yahoo_leagues WHERE season = $1 ORDER BY name
`

func (q *Queries) GetYahooLeaguesBySeason(ctx context.Context, season int32) ([]YahooLeague, error) {
	rows, err := q.db.Query(ctx, getYahooLeaguesBySeason, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeague{}
	for rows.Next() {
		var i YahooLeague
		if err := rows.Scan(
			&i.ID,
			&i.LeagueKey,
			&i.Name,
			&i.Url,
			&i.LogoUrl,
			&i.Season,
			&i.GameCode,
			&i.NumTeams,
			&i.ScoringType,
			&i.LeagueType,
			&i.DraftStatus,
			&i.IsProLeague,
			&i.IsCashLeague,
			&i.StartDate,
			&i.EndDate,
			&i.DraftType,
			&i.IsAuctionDraft,
			&i.DraftTime,
			&i.DraftPickTime,
			&i.WaiverType,
			&i.WaiverRule,
			&i.WaiverTime,
			&i.TradeEndDate,
			&i.TradeRatifyType,
			&i.TradeRejectTime,
			&i.MaxTeams,
			&i.PlayerPool,
			&i.PostDraftPlayers,
			&i.CantCutList,
			&i.UsesPlayoff,
			&i.PersistentUrl,
			&i.LeagueUpdateTimestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooTeam = `-- name: GetYahooTeam :one

SELECT league_id, id, team_key, name, url, logo_url, draft_position, waiver_priority, number_of_moves, number_of_trades, is_owned_by_current_login, created_at, updated_at FROM yahoo_teams WHERE league_id = $1 AND id = $2
`

type GetYahooTeamParams struct {
	LeagueID int32 `json:"league_id"`
	ID       int32 `json:"id"`
}

// =============================================================================
// Yahoo Teams
// =============================================================================
func (q *Queries) GetYahooTeam(ctx context.Context, arg GetYahooTeamParams) (YahooTeam, error) {
	row := q.db.QueryRow(ctx, getYahooTeam, arg.LeagueID, arg.ID)
	var i YahooTeam
	err := row.Scan(
		&i.LeagueID,
		&i.ID,
		&i.TeamKey,
		&i.Name,
		&i.Url,
		&i.LogoUrl,
		&i.DraftPosition,
		&i.WaiverPriority,
		&i.NumberOfMoves,
		&i.NumberOfTrades,
		&i.IsOwnedByCurrentLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYahooTeamByKey = `-- name: GetYahooTeamByKey :one
SELECT league_id, id, team_key, name, url, logo_url, draft_position, waiver_priority, number_of_moves, number_of_trades, is_owned_by_current_login, created_at, updated_at FROM yahoo_teams WHERE team_key = $1
`

func (q *Queries) GetYahooTeamByKey(ctx context.Context, teamKey string) (YahooTeam, error) {
	row := q.db.QueryRow(ctx, getYahooTeamByKey, teamKey)
	var i YahooTeam
	err := row.Scan(
		&i.LeagueID,
		&i.ID,
		&i.TeamKey,
		&i.Name,
		&i.Url,
		&i.LogoUrl,
		&i.DraftPosition,
		&i.WaiverPriority,
		&i.NumberOfMoves,
		&i.NumberOfTrades,
		&i.IsOwnedByCurrentLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYahooTeamManagerByGUID = `-- name: GetYahooTeamManagerByGUID :one
SELECT league_id, team_id, id, nickname, guid, email, image_url, felo_score, felo_tier, is_current_login, is_commissioner FROM yahoo_team_managers WHERE guid = $1
`

func (q *Queries) GetYahooTeamManagerByGUID(ctx context.Context, guid string) (YahooTeamManager, error) {
	row := q.db.QueryRow(ctx, getYahooTeamManagerByGUID, guid)
	var i YahooTeamManager
	err := row.Scan(
		&i.LeagueID,
		&i.TeamID,
		&i.ID,
		&i.Nickname,
		&i.Guid,
		&i.Email,
		&i.ImageUrl,
		&i.FeloScore,
		&i.FeloTier,
		&i.IsCurrentLogin,
		&i.IsCommissioner,
	)
	return i, err
}

const getYahooTeamManagers = `-- name: GetYahooTeamManagers :many

SELECT league_id, team_id, id, nickname, guid, email, image_url, felo_score, felo_tier, is_current_login, is_commissioner FROM yahoo_team_managers
WHERE league_id = $1 AND team_id = $2
ORDER BY id
`

type GetYahooTeamManagersParams struct {
	LeagueID int32 `json:"league_id"`
	TeamID   int32 `json:"team_id"`
}

// =============================================================================
// Yahoo Team Managers
// =============================================================================
func (q *Queries) GetYahooTeamManagers(ctx context.Context, arg GetYahooTeamManagersParams) ([]YahooTeamManager, error) {
	rows, err := q.db.Query(ctx, getYahooTeamManagers, arg.LeagueID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooTeamManager{}
	for rows.Next() {
		var i YahooTeamManager
		if err := rows.Scan(
			&i.LeagueID,
			&i.TeamID,
			&i.ID,
			&i.Nickname,
			&i.Guid,
			&i.Email,
			&i.ImageUrl,
			&i.FeloScore,
			&i.FeloTier,
			&i.IsCurrentLogin,
			&i.IsCommissioner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooTeamsByLeague = `-- name: GetYahooTeamsByLeague :many
SELECT league_id, id, team_key, name, url, logo_url, draft_position, waiver_priority, number_of_moves, number_of_trades, is_owned_by_current_login, created_at, updated_at FROM yahoo_teams WHERE league_id = $1 ORDER BY id
`

func (q *Queries) GetYahooTeamsByLeague(ctx context.Context, leagueID int32) ([]YahooTeam, error) {
	rows, err := q.db.Query(ctx, getYahooTeamsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooTeam{}
	for rows.Next() {
		var i YahooTeam
		if err := rows.Scan(
			&i.LeagueID,
			&i.ID,
			&i.TeamKey,
			&i.Name,
			&i.Url,
			&i.LogoUrl,
			&i.DraftPosition,
			&i.WaiverPriority,
			&i.NumberOfMoves,
			&i.NumberOfTrades,
			&i.IsOwnedByCurrentLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYahooTeamsByLeagueWithWaiverOrder = `-- name: GetYahooTeamsByLeagueWithWaiverOrder :many
SELECT league_id, id, team_key, name, url, logo_url, draft_position, waiver_priority, number_of_moves, number_of_trades, is_owned_by_current_login, created_at, updated_at FROM yahoo_teams WHERE league_id = $1 ORDER BY waiver_priority
`

func (q *Queries) GetYahooTeamsByLeagueWithWaiverOrder(ctx context.Context, leagueID int32) ([]YahooTeam, error) {
	rows, err := q.db.Query(ctx, getYahooTeamsByLeagueWithWaiverOrder, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooTeam{}
	for rows.Next() {
		var i YahooTeam
		if err := rows.Scan(
			&i.LeagueID,
			&i.ID,
			&i.TeamKey,
			&i.Name,
			&i.Url,
			&i.LogoUrl,
			&i.DraftPosition,
			&i.WaiverPriority,
			&i.NumberOfMoves,
			&i.NumberOfTrades,
			&i.IsOwnedByCurrentLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertYahooLeague = `-- name: UpsertYahooLeague :exec
INSERT INTO yahoo_leagues (
    id, league_key, name, url, logo_url,
    season, game_code, num_teams, scoring_type, league_type, draft_status,
    is_pro_league, is_cash_league, start_date, end_date,
    draft_type, is_auction_draft, draft_time, draft_pick_time,
    waiver_type, waiver_rule, waiver_time,
    trade_end_date, trade_ratify_type, trade_reject_time,
    max_teams, player_pool, post_draft_players, cant_cut_list,
    uses_playoff, persistent_url, league_update_timestamp
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18, $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28, $29,
    $30, $31, $32
)
ON CONFLICT (id) DO UPDATE SET
    league_key = EXCLUDED.league_key,
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    logo_url = EXCLUDED.logo_url,
    season = EXCLUDED.season,
    game_code = EXCLUDED.game_code,
    num_teams = EXCLUDED.num_teams,
    scoring_type = EXCLUDED.scoring_type,
    league_type = EXCLUDED.league_type,
    draft_status = EXCLUDED.draft_status,
    is_pro_league = EXCLUDED.is_pro_league,
    is_cash_league = EXCLUDED.is_cash_league,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    draft_type = EXCLUDED.draft_type,
    is_auction_draft = EXCLUDED.is_auction_draft,
    draft_time = EXCLUDED.draft_time,
    draft_pick_time = EXCLUDED.draft_pick_time,
    waiver_type = EXCLUDED.waiver_type,
    waiver_rule = EXCLUDED.waiver_rule,
    waiver_time = EXCLUDED.waiver_time,
    trade_end_date = EXCLUDED.trade_end_date,
    trade_ratify_type = EXCLUDED.trade_ratify_type,
    trade_reject_time = EXCLUDED.trade_reject_time,
    max_teams = EXCLUDED.max_teams,
    player_pool = EXCLUDED.player_pool,
    post_draft_players = EXCLUDED.post_draft_players,
    cant_cut_list = EXCLUDED.cant_cut_list,
    uses_playoff = EXCLUDED.uses_playoff,
    persistent_url = EXCLUDED.persistent_url,
    league_update_timestamp = EXCLUDED.league_update_timestamp,
    updated_at = NOW()
`

type UpsertYahooLeagueParams struct {
	ID                    int32              `json:"id"`
	LeagueKey             string             `json:"league_key"`
	Name                  string             `json:"name"`
	Url                   string             `json:"url"`
	LogoUrl               string             `json:"logo_url"`
	Season                int32              `json:"season"`
	GameCode              string             `json:"game_code"`
	NumTeams              int32              `json:"num_teams"`
	ScoringType           string             `json:"scoring_type"`
	LeagueType            string             `json:"league_type"`
	DraftStatus           string             `json:"draft_status"`
	IsProLeague           bool               `json:"is_pro_league"`
	IsCashLeague          bool               `json:"is_cash_league"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	DraftType             string             `json:"draft_type"`
	IsAuctionDraft        bool               `json:"is_auction_draft"`
	DraftTime             pgtype.Timestamptz `json:"draft_time"`
	DraftPickTime         pgtype.Int4        `json:"draft_pick_time"`
	WaiverType            string             `json:"waiver_type"`
	WaiverRule            string             `json:"waiver_rule"`
	WaiverTime            pgtype.Int4        `json:"waiver_time"`
	TradeEndDate          pgtype.Date        `json:"trade_end_date"`
	TradeRatifyType       string             `json:"trade_ratify_type"`
	TradeRejectTime       pgtype.Int4        `json:"trade_reject_time"`
	MaxTeams              pgtype.Int4        `json:"max_teams"`
	PlayerPool            string             `json:"player_pool"`
	PostDraftPlayers      string             `json:"post_draft_players"`
	CantCutList           string             `json:"cant_cut_list"`
	UsesPlayoff           bool               `json:"uses_playoff"`
	PersistentUrl         string             `json:"persistent_url"`
	LeagueUpdateTimestamp pgtype.Int8        `json:"league_update_timestamp"`
}

func (q *Queries) UpsertYahooLeague(ctx context.Context, arg UpsertYahooLeagueParams) error {
	_, err := q.db.Exec(ctx, upsertYahooLeague,
		arg.ID,
		arg.LeagueKey,
		arg.Name,
		arg.Url,
		arg.LogoUrl,
		arg.Season,
		arg.GameCode,
		arg.NumTeams,
		arg.ScoringType,
		arg.LeagueType,
		arg.DraftStatus,
		arg.IsProLeague,
		arg.IsCashLeague,
		arg.StartDate,
		arg.EndDate,
		arg.DraftType,
		arg.IsAuctionDraft,
		arg.DraftTime,
		arg.DraftPickTime,
		arg.WaiverType,
		arg.WaiverRule,
		arg.WaiverTime,
		arg.TradeEndDate,
		arg.TradeRatifyType,
		arg.TradeRejectTime,
		arg.MaxTeams,
		arg.PlayerPool,
		arg.PostDraftPlayers,
		arg.CantCutList,
		arg.UsesPlayoff,
		arg.PersistentUrl,
		arg.LeagueUpdateTimestamp,
	)
	return err
}
