package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/sperano/puckdb/internal/graph/model"
	"github.com/sperano/puckdb/internal/worker/shared"
)

// RefreshDraftRankings is the resolver for the refreshDraftRankings field.
func (r *mutationResolver) RefreshDraftRankings(ctx context.Context, input *model.RefreshDraftRankingsInput) (bool, error) {
	return r.Resolver.refreshDraftRankings(ctx, input)
}

// CancelRefreshDraftRankings is the resolver for the cancelRefreshDraftRankings field.
func (r *mutationResolver) CancelRefreshDraftRankings(ctx context.Context) (bool, error) {
	return r.Resolver.cancelWorkflow(ctx, shared.WorkflowIDRefreshDraftRankings)
}

// CreateDraftOverride is the resolver for the createDraftOverride field.
func (r *mutationResolver) CreateDraftOverride(ctx context.Context, input model.DraftOverrideCreateInput) (*model.DraftOverride, error) {
	return r.Resolver.createDraftOverride(ctx, input)
}

// ResetDraftOverride is the resolver for the resetDraftOverride field.
func (r *mutationResolver) ResetDraftOverride(ctx context.Context, id string, reason string) (bool, error) {
	return r.Resolver.resetDraftOverride(ctx, id, reason)
}

// DraftLeagues is the resolver for the draftLeagues field.
func (r *queryResolver) DraftLeagues(ctx context.Context, season *int) ([]*model.DraftLeagueSummary, error) {
	return r.Resolver.draftLeagues(ctx, season)
}

// DraftRankings is the resolver for the draftRankings field.
func (r *queryResolver) DraftRankings(ctx context.Context, input model.DraftRankingsInput) (*model.DraftRankingsPage, error) {
	return r.Resolver.draftRankings(ctx, input)
}

// DraftPlayerComparison is the resolver for the draftPlayerComparison field.
func (r *queryResolver) DraftPlayerComparison(ctx context.Context, input model.DraftComparisonInput) (*model.DraftRankingsPage, error) {
	return r.Resolver.draftPlayerComparison(ctx, input)
}

// DraftOverrides is the resolver for the draftOverrides field.
func (r *queryResolver) DraftOverrides(ctx context.Context, leagueKey *string, playerKey *string, includeInactive *bool) ([]*model.DraftOverride, error) {
	return r.Resolver.draftOverrides(ctx, leagueKey, playerKey, includeInactive)
}

// RefreshDraftRankingsResult is the resolver for the refreshDraftRankingsResult field.
func (r *queryResolver) RefreshDraftRankingsResult(ctx context.Context) (*model.WorkflowResult, error) {
	return r.Resolver.getWorkflowResult(ctx, shared.WorkflowIDRefreshDraftRankings)
}

// RefreshDraftRankingsProgress is the resolver for the refreshDraftRankingsProgress field.
func (r *queryResolver) RefreshDraftRankingsProgress(ctx context.Context) (*model.ProgressReport, error) {
	return r.Resolver.queryProgressReport(ctx, shared.WorkflowIDRefreshDraftRankings)
}
