package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/sperano/puckdb/internal/graph/model"
)

// StartMauriceDraftWatch is the resolver for the startMauriceDraftWatch field.
func (r *mutationResolver) StartMauriceDraftWatch(ctx context.Context, input model.MauriceDraftSessionRefInput) (*model.MauriceDraftWatchStatus, error) {
	return r.Resolver.startMauriceDraftWatch(ctx, input)
}

// StopMauriceDraftWatch is the resolver for the stopMauriceDraftWatch field.
func (r *mutationResolver) StopMauriceDraftWatch(ctx context.Context, input model.MauriceDraftSessionRefInput) (*model.MauriceDraftWatchStatus, error) {
	return r.Resolver.stopMauriceDraftWatch(ctx, input)
}

// RefreshMauriceDraftBoard is the resolver for the refreshMauriceDraftBoard field.
func (r *mutationResolver) RefreshMauriceDraftBoard(ctx context.Context, input model.MauriceDraftSessionRefInput) (*model.MauriceDraftSyncStatus, error) {
	return r.Resolver.refreshMauriceDraftBoard(ctx, input)
}

// ApplyMauriceDraftPick is the resolver for the applyMauriceDraftPick field.
func (r *mutationResolver) ApplyMauriceDraftPick(ctx context.Context, input model.MauriceDraftManualPickInput) (*model.MauriceDraftSyncStatus, error) {
	return r.Resolver.applyMauriceDraftPick(ctx, input)
}

// UndoMauriceDraftPick is the resolver for the undoMauriceDraftPick field.
func (r *mutationResolver) UndoMauriceDraftPick(ctx context.Context, input model.MauriceDraftSlotInput) (*model.MauriceDraftSyncStatus, error) {
	return r.Resolver.undoMauriceDraftPick(ctx, input)
}

// ResolveMauriceDraftConflict is the resolver for the resolveMauriceDraftConflict field.
func (r *mutationResolver) ResolveMauriceDraftConflict(ctx context.Context, input model.MauriceDraftResolveInput) (*model.MauriceDraftSyncStatus, error) {
	return r.Resolver.resolveMauriceDraftConflict(ctx, input)
}

// SetMauriceDraftShortlist is the resolver for the setMauriceDraftShortlist field.
func (r *mutationResolver) SetMauriceDraftShortlist(ctx context.Context, input model.MauriceDraftShortlistInput) (*model.MauriceDraftSyncStatus, error) {
	return r.Resolver.setMauriceDraftShortlist(ctx, input)
}

// MauriceDraftBoard is the resolver for the mauriceDraftBoard field.
func (r *queryResolver) MauriceDraftBoard(ctx context.Context, input model.MauriceDraftBoardInput) (*model.MauriceDraftBoard, error) {
	return r.Resolver.mauriceDraftBoard(ctx, input)
}

// MauriceDraftEvents is the resolver for the mauriceDraftEvents field.
func (r *queryResolver) MauriceDraftEvents(ctx context.Context, league string, season *int, afterStateVersion int64, limit *int) ([]*model.MauriceDraftSessionEvent, error) {
	return r.Resolver.mauriceDraftEvents(ctx, league, season, afterStateVersion, limit)
}
