// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draft_rankings.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDraftRankingRefreshes = `-- name: CancelDraftRankingRefreshes :execrows
UPDATE draft_ranking_refreshes
SET status = 'canceled', state = 'canceled', finished_at = $2
WHERE run_id = $1 AND status = 'running'
`

type CancelDraftRankingRefreshesParams struct {
	RunID      string             `json:"run_id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// Marks a run's unfinished attempts canceled.
func (q *Queries) CancelDraftRankingRefreshes(ctx context.Context, arg CancelDraftRankingRefreshesParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelDraftRankingRefreshes, arg.RunID, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countNewsAdjustmentOverrideChanges = `-- name: CountNewsAdjustmentOverrideChanges :one
SELECT COUNT(*) FROM news_adjustment_overrides
WHERE (league_key = $1 OR league_key = '')
  AND ((created_at > $2 AND created_at <= $3)
    OR (reset_at > $2 AND reset_at <= $3)
    OR (expires_at > $2 AND expires_at <= $3))
`

type CountNewsAdjustmentOverrideChangesParams struct {
	LeagueKey string             `json:"league_key"`
	Since     pgtype.Timestamptz `json:"since"`
	Now       pgtype.Timestamptz `json:"now"`
}

// Counts overrides of a league (or of every league) created, reset or
// expired after since and by now: a snapshot built at since does not
// reflect them.
func (q *Queries) CountNewsAdjustmentOverrideChanges(ctx context.Context, arg CountNewsAdjustmentOverrideChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsAdjustmentOverrideChanges, arg.LeagueKey, arg.Since, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDraftRankingPlayer = `-- name: CreateDraftRankingPlayer :exec
INSERT INTO draft_ranking_players (snapshot_id, player_key, baseline_rank, player)
VALUES ($1, $2, $3, $4)
`

type CreateDraftRankingPlayerParams struct {
	SnapshotID   pgtype.UUID `json:"snapshot_id"`
	PlayerKey    string      `json:"player_key"`
	BaselineRank int32       `json:"baseline_rank"`
	Player       []byte      `json:"player"`
}

func (q *Queries) CreateDraftRankingPlayer(ctx context.Context, arg CreateDraftRankingPlayerParams) error {
	_, err := q.db.Exec(ctx, createDraftRankingPlayer,
		arg.SnapshotID,
		arg.PlayerKey,
		arg.BaselineRank,
		arg.Player,
	)
	return err
}

const createDraftRankingSnapshot = `-- name: CreateDraftRankingSnapshot :one

INSERT INTO draft_ranking_snapshots (
    season, league_id, league_key, identity, rules_hash, projection_snapshot_id,
    adjustment_run_id, as_of, meta
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateDraftRankingSnapshotParams struct {
	Season               int32              `json:"season"`
	LeagueID             int32              `json:"league_id"`
	LeagueKey            string             `json:"league_key"`
	Identity             string             `json:"identity"`
	RulesHash            string             `json:"rules_hash"`
	ProjectionSnapshotID pgtype.UUID        `json:"projection_snapshot_id"`
	AdjustmentRunID      pgtype.UUID        `json:"adjustment_run_id"`
	AsOf                 pgtype.Timestamptz `json:"as_of"`
	Meta                 []byte             `json:"meta"`
}

// Draft ranking snapshots, their players and refresh attempts (migration
// 000010). Snapshots are immutable: readers serve the latest by as_of.
func (q *Queries) CreateDraftRankingSnapshot(ctx context.Context, arg CreateDraftRankingSnapshotParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDraftRankingSnapshot,
		arg.Season,
		arg.LeagueID,
		arg.LeagueKey,
		arg.Identity,
		arg.RulesHash,
		arg.ProjectionSnapshotID,
		arg.AdjustmentRunID,
		arg.AsOf,
		arg.Meta,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findYahooLeagueRuleSnapshotByKey = `-- name: FindYahooLeagueRuleSnapshotByKey :one
SELECT season, league_id FROM yahoo_league_rule_snapshots
WHERE league_key = $1
ORDER BY last_seen_at DESC, id DESC
LIMIT 1
`

type FindYahooLeagueRuleSnapshotByKeyRow struct {
	Season   int32 `json:"season"`
	LeagueID int32 `json:"league_id"`
}

// Resolves a league key to its season and numeric league ID.
func (q *Queries) FindYahooLeagueRuleSnapshotByKey(ctx context.Context, leagueKey string) (FindYahooLeagueRuleSnapshotByKeyRow, error) {
	row := q.db.QueryRow(ctx, findYahooLeagueRuleSnapshotByKey, leagueKey)
	var i FindYahooLeagueRuleSnapshotByKeyRow
	err := row.Scan(&i.Season, &i.LeagueID)
	return i, err
}

const finishDraftRankingRefresh = `-- name: FinishDraftRankingRefresh :exec
UPDATE draft_ranking_refreshes
SET status = $2, state = $3, error = $4, snapshot_id = $5, league_key = $6, finished_at = $7
WHERE id = $1
`

type FinishDraftRankingRefreshParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	State      string             `json:"state"`
	Error      string             `json:"error"`
	SnapshotID pgtype.UUID        `json:"snapshot_id"`
	LeagueKey  string             `json:"league_key"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FinishDraftRankingRefresh(ctx context.Context, arg FinishDraftRankingRefreshParams) error {
	_, err := q.db.Exec(ctx, finishDraftRankingRefresh,
		arg.ID,
		arg.Status,
		arg.State,
		arg.Error,
		arg.SnapshotID,
		arg.LeagueKey,
		arg.FinishedAt,
	)
	return err
}

const getDraftRankingSnapshot = `-- name: GetDraftRankingSnapshot :one
SELECT id, season, league_id, league_key, identity, rules_hash, projection_snapshot_id, adjustment_run_id, as_of, created_at, meta FROM draft_ranking_snapshots WHERE id = $1
`

func (q *Queries) GetDraftRankingSnapshot(ctx context.Context, id pgtype.UUID) (DraftRankingSnapshot, error) {
	row := q.db.QueryRow(ctx, getDraftRankingSnapshot, id)
	var i DraftRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.Season,
		&i.LeagueID,
		&i.LeagueKey,
		&i.Identity,
		&i.RulesHash,
		&i.ProjectionSnapshotID,
		&i.AdjustmentRunID,
		&i.AsOf,
		&i.CreatedAt,
		&i.Meta,
	)
	return i, err
}

const getLatestDraftRankingRefresh = `-- name: GetLatestDraftRankingRefresh :one
SELECT id, run_id, season, league_id, league_key, status, state, error, snapshot_id, started_at, finished_at FROM draft_ranking_refreshes
WHERE season = $1 AND league_id = $2
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type GetLatestDraftRankingRefreshParams struct {
	Season   int32 `json:"season"`
	LeagueID int32 `json:"league_id"`
}

func (q *Queries) GetLatestDraftRankingRefresh(ctx context.Context, arg GetLatestDraftRankingRefreshParams) (DraftRankingRefresh, error) {
	row := q.db.QueryRow(ctx, getLatestDraftRankingRefresh, arg.Season, arg.LeagueID)
	var i DraftRankingRefresh
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Season,
		&i.LeagueID,
		&i.LeagueKey,
		&i.Status,
		&i.State,
		&i.Error,
		&i.SnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestDraftRankingSnapshot = `-- name: GetLatestDraftRankingSnapshot :one
SELECT id, season, league_id, league_key, identity, rules_hash, projection_snapshot_id, adjustment_run_id, as_of, created_at, meta FROM draft_ranking_snapshots
WHERE season = $1 AND league_id = $2
ORDER BY as_of DESC, created_at DESC, id DESC
LIMIT 1
`

type GetLatestDraftRankingSnapshotParams struct {
	Season   int32 `json:"season"`
	LeagueID int32 `json:"league_id"`
}

func (q *Queries) GetLatestDraftRankingSnapshot(ctx context.Context, arg GetLatestDraftRankingSnapshotParams) (DraftRankingSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestDraftRankingSnapshot, arg.Season, arg.LeagueID)
	var i DraftRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.Season,
		&i.LeagueID,
		&i.LeagueKey,
		&i.Identity,
		&i.RulesHash,
		&i.ProjectionSnapshotID,
		&i.AdjustmentRunID,
		&i.AsOf,
		&i.CreatedAt,
		&i.Meta,
	)
	return i, err
}

const listDraftRankingPlayers = `-- name: ListDraftRankingPlayers :many
SELECT player_key, baseline_rank, player FROM draft_ranking_players
WHERE snapshot_id = $1
ORDER BY baseline_rank, player_key
`

type ListDraftRankingPlayersRow struct {
	PlayerKey    string `json:"player_key"`
	BaselineRank int32  `json:"baseline_rank"`
	Player       []byte `json:"player"`
}

func (q *Queries) ListDraftRankingPlayers(ctx context.Context, snapshotID pgtype.UUID) ([]ListDraftRankingPlayersRow, error) {
	rows, err := q.db.Query(ctx, listDraftRankingPlayers, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftRankingPlayersRow{}
	for rows.Next() {
		var i ListDraftRankingPlayersRow
		if err := rows.Scan(&i.PlayerKey, &i.BaselineRank, &i.Player); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestYahooLeagueRuleSnapshots = `-- name: ListLatestYahooLeagueRuleSnapshots :many
SELECT DISTINCT ON (league_id) id, season, league_id, league_key, game_key, source, source_season, source_league_key, fetched_at, rules_hash, rules, first_seen_at, last_seen_at FROM yahoo_league_rule_snapshots
WHERE season = $1
ORDER BY league_id, last_seen_at DESC, id DESC
`

// The latest rules of every league of a season.
func (q *Queries) ListLatestYahooLeagueRuleSnapshots(ctx context.Context, season int32) ([]YahooLeagueRuleSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestYahooLeagueRuleSnapshots, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YahooLeagueRuleSnapshot{}
	for rows.Next() {
		var i YahooLeagueRuleSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.LeagueID,
			&i.LeagueKey,
			&i.GameKey,
			&i.Source,
			&i.SourceSeason,
			&i.SourceLeagueKey,
			&i.FetchedAt,
			&i.RulesHash,
			&i.Rules,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftRankingLeague = `-- name: LockDraftRankingLeague :exec
SELECT pg_advisory_xact_lock(hashtext('draft-ranking:' || $1::integer || ':' || $2::integer))
`

type LockDraftRankingLeagueParams struct {
	Season   int32 `json:"season"`
	LeagueID int32 `json:"league_id"`
}

// Serializes snapshot writes of one league within a transaction.
func (q *Queries) LockDraftRankingLeague(ctx context.Context, arg LockDraftRankingLeagueParams) error {
	_, err := q.db.Exec(ctx, lockDraftRankingLeague, arg.Season, arg.LeagueID)
	return err
}

const pruneDraftRankingSnapshots = `-- name: PruneDraftRankingSnapshots :execrows
DELETE FROM draft_ranking_snapshots s
WHERE s.season = $1 AND s.league_id = $2
  AND s.id NOT IN (
    SELECT k.id FROM draft_ranking_snapshots k
    WHERE k.season = $1 AND k.league_id = $2
    ORDER BY k.as_of DESC, k.created_at DESC, k.id DESC
    LIMIT $3::integer
  )
`

type PruneDraftRankingSnapshotsParams struct {
	Season   int32 `json:"season"`
	LeagueID int32 `json:"league_id"`
	Keep     int32 `json:"keep"`
}

// Deletes all but the newest keep snapshots of a league.
func (q *Queries) PruneDraftRankingSnapshots(ctx context.Context, arg PruneDraftRankingSnapshotsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneDraftRankingSnapshots, arg.Season, arg.LeagueID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startDraftRankingRefresh = `-- name: StartDraftRankingRefresh :one
INSERT INTO draft_ranking_refreshes (run_id, season, league_id, status, started_at)
VALUES ($1, $2, $3, 'running', $4)
ON CONFLICT (run_id, season, league_id) DO UPDATE
SET status = 'running', state = '', error = '', snapshot_id = NULL,
    started_at = EXCLUDED.started_at, finished_at = NULL
RETURNING id
`

type StartDraftRankingRefreshParams struct {
	RunID     string             `json:"run_id"`
	Season    int32              `json:"season"`
	LeagueID  int32              `json:"league_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) StartDraftRankingRefresh(ctx context.Context, arg StartDraftRankingRefreshParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, startDraftRankingRefresh,
		arg.RunID,
		arg.Season,
		arg.LeagueID,
		arg.StartedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
