// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_season_totals.sql

package sqlcdb

import (
	"context"
)

const countPlayerSeasonTotals = `-- name: CountPlayerSeasonTotals :one
SELECT COUNT(*) FROM player_season_totals
`

func (q *Queries) CountPlayerSeasonTotals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerSeasonTotals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlayerNHLSeasonTotals = `-- name: GetPlayerNHLSeasonTotals :many
SELECT player_id, season, game_type, league_abbrev, team_name, team_id, sequence, games_played, goals, assists, points, plus_minus, pim, created_at, updated_at FROM player_season_totals
WHERE player_id = $1 AND league_abbrev = 'NHL'
ORDER BY season DESC, game_type, sequence
`

func (q *Queries) GetPlayerNHLSeasonTotals(ctx context.Context, playerID int64) ([]PlayerSeasonTotal, error) {
	rows, err := q.db.Query(ctx, getPlayerNHLSeasonTotals, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerSeasonTotal{}
	for rows.Next() {
		var i PlayerSeasonTotal
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.GameType,
			&i.LeagueAbbrev,
			&i.TeamName,
			&i.TeamID,
			&i.Sequence,
			&i.GamesPlayed,
			&i.Goals,
			&i.Assists,
			&i.Points,
			&i.PlusMinus,
			&i.PIM,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerSeasonTotals = `-- name: GetPlayerSeasonTotals :many
SELECT player_id, season, game_type, league_abbrev, team_name, team_id, sequence, games_played, goals, assists, points, plus_minus, pim, created_at, updated_at FROM player_season_totals
WHERE player_id = $1
ORDER BY season DESC, game_type, league_abbrev, sequence
`

func (q *Queries) GetPlayerSeasonTotals(ctx context.Context, playerID int64) ([]PlayerSeasonTotal, error) {
	rows, err := q.db.Query(ctx, getPlayerSeasonTotals, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerSeasonTotal{}
	for rows.Next() {
		var i PlayerSeasonTotal
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.GameType,
			&i.LeagueAbbrev,
			&i.TeamName,
			&i.TeamID,
			&i.Sequence,
			&i.GamesPlayed,
			&i.Goals,
			&i.Assists,
			&i.Points,
			&i.PlusMinus,
			&i.PIM,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerSeasonTotalsByLeague = `-- name: GetPlayerSeasonTotalsByLeague :many
SELECT player_id, season, game_type, league_abbrev, team_name, team_id, sequence, games_played, goals, assists, points, plus_minus, pim, created_at, updated_at FROM player_season_totals
WHERE player_id = $1 AND league_abbrev = $2
ORDER BY season DESC, game_type, sequence
`

type GetPlayerSeasonTotalsByLeagueParams struct {
	PlayerID     int64  `json:"player_id"`
	LeagueAbbrev string `json:"league_abbrev"`
}

func (q *Queries) GetPlayerSeasonTotalsByLeague(ctx context.Context, arg GetPlayerSeasonTotalsByLeagueParams) ([]PlayerSeasonTotal, error) {
	rows, err := q.db.Query(ctx, getPlayerSeasonTotalsByLeague, arg.PlayerID, arg.LeagueAbbrev)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerSeasonTotal{}
	for rows.Next() {
		var i PlayerSeasonTotal
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.GameType,
			&i.LeagueAbbrev,
			&i.TeamName,
			&i.TeamID,
			&i.Sequence,
			&i.GamesPlayed,
			&i.Goals,
			&i.Assists,
			&i.Points,
			&i.PlusMinus,
			&i.PIM,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
