// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_awards.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayerAwards = `-- name: CountPlayerAwards :one
SELECT COUNT(*) FROM player_awards
`

func (q *Queries) CountPlayerAwards(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerAwards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAwardsBySeason = `-- name: GetAwardsBySeason :many
SELECT pa.player_id, pa.trophy_name, pa.season, pa.created_at, p.first_name, p.last_name
FROM player_awards pa
JOIN players p ON pa.player_id = p.id
WHERE pa.season = $1
ORDER BY pa.trophy_name, p.last_name
`

type GetAwardsBySeasonRow struct {
	PlayerID   int64              `json:"player_id"`
	TrophyName string             `json:"trophy_name"`
	Season     int32              `json:"season"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
}

func (q *Queries) GetAwardsBySeason(ctx context.Context, season int32) ([]GetAwardsBySeasonRow, error) {
	rows, err := q.db.Query(ctx, getAwardsBySeason, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAwardsBySeasonRow{}
	for rows.Next() {
		var i GetAwardsBySeasonRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.TrophyName,
			&i.Season,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAwardsByTrophy = `-- name: GetAwardsByTrophy :many
SELECT pa.player_id, pa.trophy_name, pa.season, pa.created_at, p.first_name, p.last_name
FROM player_awards pa
JOIN players p ON pa.player_id = p.id
WHERE pa.trophy_name = $1
ORDER BY pa.season DESC
`

type GetAwardsByTrophyRow struct {
	PlayerID   int64              `json:"player_id"`
	TrophyName string             `json:"trophy_name"`
	Season     int32              `json:"season"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
}

func (q *Queries) GetAwardsByTrophy(ctx context.Context, trophyName string) ([]GetAwardsByTrophyRow, error) {
	rows, err := q.db.Query(ctx, getAwardsByTrophy, trophyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAwardsByTrophyRow{}
	for rows.Next() {
		var i GetAwardsByTrophyRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.TrophyName,
			&i.Season,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerAwards = `-- name: GetPlayerAwards :many
SELECT pa.player_id, pa.trophy_name, pa.season, pa.created_at, p.first_name, p.last_name
FROM player_awards pa
JOIN players p ON pa.player_id = p.id
WHERE pa.player_id = $1
ORDER BY pa.season DESC, pa.trophy_name
`

type GetPlayerAwardsRow struct {
	PlayerID   int64              `json:"player_id"`
	TrophyName string             `json:"trophy_name"`
	Season     int32              `json:"season"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
}

func (q *Queries) GetPlayerAwards(ctx context.Context, playerID int64) ([]GetPlayerAwardsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerAwards, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerAwardsRow{}
	for rows.Next() {
		var i GetPlayerAwardsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.TrophyName,
			&i.Season,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
