// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projections.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectionEvaluation = `-- name: CreateProjectionEvaluation :one
INSERT INTO projection_evaluations (
    model_version, config_hash, source_data_hash, target_season, as_of,
    observed_at, player_kind, comparison_model
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (
    model_version, config_hash, source_data_hash, target_season,
    as_of, observed_at, player_kind, comparison_model
) DO UPDATE SET observed_at = EXCLUDED.observed_at
RETURNING id, model_version, config_hash, source_data_hash, target_season, as_of, observed_at, player_kind, comparison_model, created_at
`

type CreateProjectionEvaluationParams struct {
	ModelVersion    string             `json:"model_version"`
	ConfigHash      string             `json:"config_hash"`
	SourceDataHash  string             `json:"source_data_hash"`
	TargetSeason    int32              `json:"target_season"`
	AsOf            pgtype.Timestamptz `json:"as_of"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	PlayerKind      string             `json:"player_kind"`
	ComparisonModel string             `json:"comparison_model"`
}

func (q *Queries) CreateProjectionEvaluation(ctx context.Context, arg CreateProjectionEvaluationParams) (ProjectionEvaluation, error) {
	row := q.db.QueryRow(ctx, createProjectionEvaluation,
		arg.ModelVersion,
		arg.ConfigHash,
		arg.SourceDataHash,
		arg.TargetSeason,
		arg.AsOf,
		arg.ObservedAt,
		arg.PlayerKind,
		arg.ComparisonModel,
	)
	var i ProjectionEvaluation
	err := row.Scan(
		&i.ID,
		&i.ModelVersion,
		&i.ConfigHash,
		&i.SourceDataHash,
		&i.TargetSeason,
		&i.AsOf,
		&i.ObservedAt,
		&i.PlayerKind,
		&i.ComparisonModel,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectionEvaluationMetric = `-- name: CreateProjectionEvaluationMetric :exec
INSERT INTO projection_evaluation_metrics (
    evaluation_id, stat, sample_size, model_mae, model_rmse,
    comparison_mae, comparison_rmse
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (evaluation_id, stat) DO UPDATE SET
    sample_size = EXCLUDED.sample_size,
    model_mae = EXCLUDED.model_mae,
    model_rmse = EXCLUDED.model_rmse,
    comparison_mae = EXCLUDED.comparison_mae,
    comparison_rmse = EXCLUDED.comparison_rmse
`

type CreateProjectionEvaluationMetricParams struct {
	EvaluationID   pgtype.UUID `json:"evaluation_id"`
	Stat           string      `json:"stat"`
	SampleSize     int32       `json:"sample_size"`
	ModelMae       float64     `json:"model_mae"`
	ModelRmse      float64     `json:"model_rmse"`
	ComparisonMae  float64     `json:"comparison_mae"`
	ComparisonRmse float64     `json:"comparison_rmse"`
}

func (q *Queries) CreateProjectionEvaluationMetric(ctx context.Context, arg CreateProjectionEvaluationMetricParams) error {
	_, err := q.db.Exec(ctx, createProjectionEvaluationMetric,
		arg.EvaluationID,
		arg.Stat,
		arg.SampleSize,
		arg.ModelMae,
		arg.ModelRmse,
		arg.ComparisonMae,
		arg.ComparisonRmse,
	)
	return err
}

const createProjectionPlayer = `-- name: CreateProjectionPlayer :exec
INSERT INTO projection_players (
    snapshot_id, player_key, player_id, team_id, player_kind, position, source,
    provider, provider_version, source_as_of, incorporates_news_through,
    history_seasons, history_games, sample_exposure, uncertainty, insufficient_history,
    missing_stats, linemate_observed_points_per_60, linemate_average_points_per_60,
    linemate_shared_toi_seconds, linemate_adjustment_factor, team_environment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21,
    $22
)
`

type CreateProjectionPlayerParams struct {
	SnapshotID                  pgtype.UUID        `json:"snapshot_id"`
	PlayerKey                   string             `json:"player_key"`
	PlayerID                    pgtype.Int8        `json:"player_id"`
	TeamID                      pgtype.Int8        `json:"team_id"`
	PlayerKind                  string             `json:"player_kind"`
	Position                    string             `json:"position"`
	Source                      string             `json:"source"`
	Provider                    string             `json:"provider"`
	ProviderVersion             string             `json:"provider_version"`
	SourceAsOf                  pgtype.Timestamptz `json:"source_as_of"`
	IncorporatesNewsThrough     pgtype.Timestamptz `json:"incorporates_news_through"`
	HistorySeasons              int32              `json:"history_seasons"`
	HistoryGames                int32              `json:"history_games"`
	SampleExposure              float64            `json:"sample_exposure"`
	Uncertainty                 float64            `json:"uncertainty"`
	InsufficientHistory         bool               `json:"insufficient_history"`
	MissingStats                []string           `json:"missing_stats"`
	LinemateObservedPointsPer60 pgtype.Float8      `json:"linemate_observed_points_per_60"`
	LinemateAveragePointsPer60  pgtype.Float8      `json:"linemate_average_points_per_60"`
	LinemateSharedToiSeconds    pgtype.Float8      `json:"linemate_shared_toi_seconds"`
	LinemateAdjustmentFactor    pgtype.Float8      `json:"linemate_adjustment_factor"`
	TeamEnvironment             []byte             `json:"team_environment"`
}

func (q *Queries) CreateProjectionPlayer(ctx context.Context, arg CreateProjectionPlayerParams) error {
	_, err := q.db.Exec(ctx, createProjectionPlayer,
		arg.SnapshotID,
		arg.PlayerKey,
		arg.PlayerID,
		arg.TeamID,
		arg.PlayerKind,
		arg.Position,
		arg.Source,
		arg.Provider,
		arg.ProviderVersion,
		arg.SourceAsOf,
		arg.IncorporatesNewsThrough,
		arg.HistorySeasons,
		arg.HistoryGames,
		arg.SampleExposure,
		arg.Uncertainty,
		arg.InsufficientHistory,
		arg.MissingStats,
		arg.LinemateObservedPointsPer60,
		arg.LinemateAveragePointsPer60,
		arg.LinemateSharedToiSeconds,
		arg.LinemateAdjustmentFactor,
		arg.TeamEnvironment,
	)
	return err
}

const createProjectionSnapshot = `-- name: CreateProjectionSnapshot :one
INSERT INTO projection_snapshots (
    target_season, as_of, source_max_game_date, model_version, config_hash, source_data_hash,
    lookback_seasons, season_decay, skater_prior_toi_seconds,
    goalie_prior_shots, goalie_shutout_min_toi, max_games, interval_z, minimum_uncertainty,
    maximum_uncertainty, minimum_history_games, linemate_regression_strength, aging_curve,
    team_environment_prior_games, team_environment_max_change,
    goalie_share_window_games, goalie_share_half_life_games, goalie_playoff_weight, goalie_share_blend
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20,
    $21, $22, $23, $24
)
ON CONFLICT (target_season, as_of, model_version, config_hash, source_data_hash) DO UPDATE SET
    source_max_game_date = EXCLUDED.source_max_game_date
RETURNING id, target_season, as_of, source_max_game_date, model_version, config_hash, source_data_hash, lookback_seasons, season_decay, skater_prior_toi_seconds, goalie_prior_shots, goalie_shutout_min_toi, max_games, interval_z, minimum_uncertainty, maximum_uncertainty, minimum_history_games, created_at, linemate_regression_strength, aging_curve, team_environment_prior_games, team_environment_max_change, goalie_share_window_games, goalie_share_half_life_games, goalie_playoff_weight, goalie_share_blend
`

type CreateProjectionSnapshotParams struct {
	TargetSeason               int32              `json:"target_season"`
	AsOf                       pgtype.Timestamptz `json:"as_of"`
	SourceMaxGameDate          pgtype.Date        `json:"source_max_game_date"`
	ModelVersion               string             `json:"model_version"`
	ConfigHash                 string             `json:"config_hash"`
	SourceDataHash             string             `json:"source_data_hash"`
	LookbackSeasons            int32              `json:"lookback_seasons"`
	SeasonDecay                float64            `json:"season_decay"`
	SkaterPriorToiSeconds      float64            `json:"skater_prior_toi_seconds"`
	GoaliePriorShots           float64            `json:"goalie_prior_shots"`
	GoalieShutoutMinToi        int32              `json:"goalie_shutout_min_toi"`
	MaxGames                   float64            `json:"max_games"`
	IntervalZ                  float64            `json:"interval_z"`
	MinimumUncertainty         float64            `json:"minimum_uncertainty"`
	MaximumUncertainty         float64            `json:"maximum_uncertainty"`
	MinimumHistoryGames        int32              `json:"minimum_history_games"`
	LinemateRegressionStrength float64            `json:"linemate_regression_strength"`
	AgingCurve                 []byte             `json:"aging_curve"`
	TeamEnvironmentPriorGames  float64            `json:"team_environment_prior_games"`
	TeamEnvironmentMaxChange   float64            `json:"team_environment_max_change"`
	GoalieShareWindowGames     int32              `json:"goalie_share_window_games"`
	GoalieShareHalfLifeGames   float64            `json:"goalie_share_half_life_games"`
	GoaliePlayoffWeight        float64            `json:"goalie_playoff_weight"`
	GoalieShareBlend           float64            `json:"goalie_share_blend"`
}

func (q *Queries) CreateProjectionSnapshot(ctx context.Context, arg CreateProjectionSnapshotParams) (ProjectionSnapshot, error) {
	row := q.db.QueryRow(ctx, createProjectionSnapshot,
		arg.TargetSeason,
		arg.AsOf,
		arg.SourceMaxGameDate,
		arg.ModelVersion,
		arg.ConfigHash,
		arg.SourceDataHash,
		arg.LookbackSeasons,
		arg.SeasonDecay,
		arg.SkaterPriorToiSeconds,
		arg.GoaliePriorShots,
		arg.GoalieShutoutMinToi,
		arg.MaxGames,
		arg.IntervalZ,
		arg.MinimumUncertainty,
		arg.MaximumUncertainty,
		arg.MinimumHistoryGames,
		arg.LinemateRegressionStrength,
		arg.AgingCurve,
		arg.TeamEnvironmentPriorGames,
		arg.TeamEnvironmentMaxChange,
		arg.GoalieShareWindowGames,
		arg.GoalieShareHalfLifeGames,
		arg.GoaliePlayoffWeight,
		arg.GoalieShareBlend,
	)
	var i ProjectionSnapshot
	err := row.Scan(
		&i.ID,
		&i.TargetSeason,
		&i.AsOf,
		&i.SourceMaxGameDate,
		&i.ModelVersion,
		&i.ConfigHash,
		&i.SourceDataHash,
		&i.LookbackSeasons,
		&i.SeasonDecay,
		&i.SkaterPriorToiSeconds,
		&i.GoaliePriorShots,
		&i.GoalieShutoutMinToi,
		&i.MaxGames,
		&i.IntervalZ,
		&i.MinimumUncertainty,
		&i.MaximumUncertainty,
		&i.MinimumHistoryGames,
		&i.CreatedAt,
		&i.LinemateRegressionStrength,
		&i.AgingCurve,
		&i.TeamEnvironmentPriorGames,
		&i.TeamEnvironmentMaxChange,
		&i.GoalieShareWindowGames,
		&i.GoalieShareHalfLifeGames,
		&i.GoaliePlayoffWeight,
		&i.GoalieShareBlend,
	)
	return i, err
}

const createProjectionValue = `-- name: CreateProjectionValue :exec
INSERT INTO projection_values (
    snapshot_id, player_key, stat, mean, low, high
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateProjectionValueParams struct {
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	PlayerKey  string      `json:"player_key"`
	Stat       string      `json:"stat"`
	Mean       float64     `json:"mean"`
	Low        float64     `json:"low"`
	High       float64     `json:"high"`
}

func (q *Queries) CreateProjectionValue(ctx context.Context, arg CreateProjectionValueParams) error {
	_, err := q.db.Exec(ctx, createProjectionValue,
		arg.SnapshotID,
		arg.PlayerKey,
		arg.Stat,
		arg.Mean,
		arg.Low,
		arg.High,
	)
	return err
}

const deleteProjectionEvaluationMetrics = `-- name: DeleteProjectionEvaluationMetrics :exec
DELETE FROM projection_evaluation_metrics WHERE evaluation_id = $1
`

func (q *Queries) DeleteProjectionEvaluationMetrics(ctx context.Context, evaluationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectionEvaluationMetrics, evaluationID)
	return err
}

const deleteProjectionPlayersBySnapshot = `-- name: DeleteProjectionPlayersBySnapshot :exec
DELETE FROM projection_players WHERE snapshot_id = $1
`

func (q *Queries) DeleteProjectionPlayersBySnapshot(ctx context.Context, snapshotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectionPlayersBySnapshot, snapshotID)
	return err
}

const getProjectionSnapshot = `-- name: GetProjectionSnapshot :one
SELECT id, target_season, as_of, source_max_game_date, model_version, config_hash, source_data_hash, lookback_seasons, season_decay, skater_prior_toi_seconds, goalie_prior_shots, goalie_shutout_min_toi, max_games, interval_z, minimum_uncertainty, maximum_uncertainty, minimum_history_games, created_at, linemate_regression_strength, aging_curve, team_environment_prior_games, team_environment_max_change, goalie_share_window_games, goalie_share_half_life_games, goalie_playoff_weight, goalie_share_blend FROM projection_snapshots WHERE id = $1
`

func (q *Queries) GetProjectionSnapshot(ctx context.Context, id pgtype.UUID) (ProjectionSnapshot, error) {
	row := q.db.QueryRow(ctx, getProjectionSnapshot, id)
	var i ProjectionSnapshot
	err := row.Scan(
		&i.ID,
		&i.TargetSeason,
		&i.AsOf,
		&i.SourceMaxGameDate,
		&i.ModelVersion,
		&i.ConfigHash,
		&i.SourceDataHash,
		&i.LookbackSeasons,
		&i.SeasonDecay,
		&i.SkaterPriorToiSeconds,
		&i.GoaliePriorShots,
		&i.GoalieShutoutMinToi,
		&i.MaxGames,
		&i.IntervalZ,
		&i.MinimumUncertainty,
		&i.MaximumUncertainty,
		&i.MinimumHistoryGames,
		&i.CreatedAt,
		&i.LinemateRegressionStrength,
		&i.AgingCurve,
		&i.TeamEnvironmentPriorGames,
		&i.TeamEnvironmentMaxChange,
		&i.GoalieShareWindowGames,
		&i.GoalieShareHalfLifeGames,
		&i.GoaliePlayoffWeight,
		&i.GoalieShareBlend,
	)
	return i, err
}

const getProjectionSourceMaxGameDate = `-- name: GetProjectionSourceMaxGameDate :one
SELECT MAX(game_date)::date
FROM games
WHERE game_type = 'regular_season'
  AND game_state IN ('FINAL', 'OFF')
  AND season < $1
  AND season >= $2
  AND game_date <= $3
`

type GetProjectionSourceMaxGameDateParams struct {
	Season   int32       `json:"season"`
	Season_2 int32       `json:"season_2"`
	GameDate pgtype.Date `json:"game_date"`
}

func (q *Queries) GetProjectionSourceMaxGameDate(ctx context.Context, arg GetProjectionSourceMaxGameDateParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getProjectionSourceMaxGameDate, arg.Season, arg.Season_2, arg.GameDate)
	var column_1 pgtype.Date
	err := row.Scan(&column_1)
	return column_1, err
}

const listProjectionEvaluationGoalieTargetTeams = `-- name: ListProjectionEvaluationGoalieTargetTeams :many
SELECT DISTINCT ON (s.player_id) s.player_id, s.team_id
FROM game_goalie_stats s
JOIN games g ON g.id = s.game_id
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season = $1
  AND s.toi_seconds > 0
ORDER BY s.player_id, g.game_date, s.game_id
`

type ListProjectionEvaluationGoalieTargetTeamsRow struct {
	PlayerID int64 `json:"player_id"`
	TeamID   int64 `json:"team_id"`
}

// Each goalie's first club of a held-out season, counting only games he
// played in (positive time on ice) so a dressed backup who never entered is
// not mapped to a club he never played for. nhl-baseline-v7 reads it for its
// goalie start share; earlier versions never load it, which keeps their
// evaluation-data hashes unchanged.
func (q *Queries) ListProjectionEvaluationGoalieTargetTeams(ctx context.Context, season int32) ([]ListProjectionEvaluationGoalieTargetTeamsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionEvaluationGoalieTargetTeams, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionEvaluationGoalieTargetTeamsRow{}
	for rows.Next() {
		var i ListProjectionEvaluationGoalieTargetTeamsRow
		if err := rows.Scan(&i.PlayerID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionEvaluationTargetTeams = `-- name: ListProjectionEvaluationTargetTeams :many
SELECT DISTINCT ON (s.player_id) s.player_id, s.team_id
FROM game_skater_stats s
JOIN games g ON g.id = s.game_id
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season = $1
ORDER BY s.player_id, g.game_date, s.game_id
`

type ListProjectionEvaluationTargetTeamsRow struct {
	PlayerID int64 `json:"player_id"`
	TeamID   int64 `json:"team_id"`
}

// Each skater's first club of a held-out season: the club a preseason
// roster would have shown, for EvaluateTeamChanges.
func (q *Queries) ListProjectionEvaluationTargetTeams(ctx context.Context, season int32) ([]ListProjectionEvaluationTargetTeamsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionEvaluationTargetTeams, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionEvaluationTargetTeamsRow{}
	for rows.Next() {
		var i ListProjectionEvaluationTargetTeamsRow
		if err := rows.Scan(&i.PlayerID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionGoalieEvaluationData = `-- name: ListProjectionGoalieEvaluationData :many
WITH projection_constants AS (
    SELECT $3::integer AS minimum_shutout_toi_seconds
)
SELECT
    s.player_id,
    p.birth_date,
    g.season,
    (ARRAY_AGG(s.team_id ORDER BY g.game_date DESC, s.game_id DESC))[1]::bigint AS team_id,
    COUNT(DISTINCT s.game_id)::int AS games_played,
    -- games_played counts every boxscore row, including games dressed as
    -- the backup with no time on ice; games_appeared counts the games played
    -- (nhl-baseline-v6 reads it, earlier versions keep games_played).
    COUNT(DISTINCT s.game_id) FILTER (WHERE s.toi_seconds > 0)::int AS games_appeared,
    COUNT(*) FILTER (WHERE s.starter = TRUE)::int AS games_started,
    SUM(s.toi_seconds)::bigint AS toi_seconds,
    COUNT(*) FILTER (WHERE s.decision = 'W')::int AS wins,
    COUNT(*) FILTER (
        WHERE s.starter = TRUE AND s.goals_against = 0
          AND s.toi_seconds >= projection_constants.minimum_shutout_toi_seconds
    )::int AS shutouts,
    SUM(s.shots_against)::bigint AS shots_against,
    SUM(s.saves)::bigint AS saves,
    SUM(s.goals_against)::bigint AS goals_against
FROM game_goalie_stats s
JOIN games g ON g.id = s.game_id
JOIN players p ON p.id = s.player_id
CROSS JOIN projection_constants
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season <= $1
  AND g.season >= $2
GROUP BY s.player_id, p.birth_date, g.season
ORDER BY s.player_id, g.season
`

type ListProjectionGoalieEvaluationDataParams struct {
	Season                   int32 `json:"season"`
	Season_2                 int32 `json:"season_2"`
	MinimumShutoutToiSeconds int32 `json:"minimum_shutout_toi_seconds"`
}

type ListProjectionGoalieEvaluationDataRow struct {
	PlayerID      int64       `json:"player_id"`
	BirthDate     pgtype.Date `json:"birth_date"`
	Season        int32       `json:"season"`
	TeamID        int64       `json:"team_id"`
	GamesPlayed   int32       `json:"games_played"`
	GamesAppeared int32       `json:"games_appeared"`
	GamesStarted  int32       `json:"games_started"`
	TOISeconds    int64       `json:"toi_seconds"`
	Wins          int32       `json:"wins"`
	Shutouts      int32       `json:"shutouts"`
	ShotsAgainst  int64       `json:"shots_against"`
	Saves         int64       `json:"saves"`
	GoalsAgainst  int64       `json:"goals_against"`
}

func (q *Queries) ListProjectionGoalieEvaluationData(ctx context.Context, arg ListProjectionGoalieEvaluationDataParams) ([]ListProjectionGoalieEvaluationDataRow, error) {
	rows, err := q.db.Query(ctx, listProjectionGoalieEvaluationData, arg.Season, arg.Season_2, arg.MinimumShutoutToiSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionGoalieEvaluationDataRow{}
	for rows.Next() {
		var i ListProjectionGoalieEvaluationDataRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.BirthDate,
			&i.Season,
			&i.TeamID,
			&i.GamesPlayed,
			&i.GamesAppeared,
			&i.GamesStarted,
			&i.TOISeconds,
			&i.Wins,
			&i.Shutouts,
			&i.ShotsAgainst,
			&i.Saves,
			&i.GoalsAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionGoalieHistory = `-- name: ListProjectionGoalieHistory :many
WITH projection_constants AS (
    SELECT $4::integer AS minimum_shutout_toi_seconds
)
SELECT
    s.player_id,
    p.birth_date,
    g.season,
    (ARRAY_AGG(s.team_id ORDER BY g.game_date DESC, s.game_id DESC))[1]::bigint AS team_id,
    COUNT(DISTINCT s.game_id)::int AS games_played,
    -- games_played counts every boxscore row, including games dressed as
    -- the backup with no time on ice; games_appeared counts the games played
    -- (nhl-baseline-v6 reads it, earlier versions keep games_played).
    COUNT(DISTINCT s.game_id) FILTER (WHERE s.toi_seconds > 0)::int AS games_appeared,
    COUNT(*) FILTER (WHERE s.starter = TRUE)::int AS games_started,
    SUM(s.toi_seconds)::bigint AS toi_seconds,
    COUNT(*) FILTER (WHERE s.decision = 'W')::int AS wins,
    COUNT(*) FILTER (
        WHERE s.starter = TRUE AND s.goals_against = 0
          AND s.toi_seconds >= projection_constants.minimum_shutout_toi_seconds
    )::int AS shutouts,
    SUM(s.shots_against)::bigint AS shots_against,
    SUM(s.saves)::bigint AS saves,
    SUM(s.goals_against)::bigint AS goals_against
FROM game_goalie_stats s
JOIN games g ON g.id = s.game_id
JOIN players p ON p.id = s.player_id
CROSS JOIN projection_constants
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season < $1
  AND g.season >= $2
  AND g.game_date <= $3
GROUP BY s.player_id, p.birth_date, g.season
ORDER BY s.player_id, g.season
`

type ListProjectionGoalieHistoryParams struct {
	Season                   int32       `json:"season"`
	Season_2                 int32       `json:"season_2"`
	GameDate                 pgtype.Date `json:"game_date"`
	MinimumShutoutToiSeconds int32       `json:"minimum_shutout_toi_seconds"`
}

type ListProjectionGoalieHistoryRow struct {
	PlayerID      int64       `json:"player_id"`
	BirthDate     pgtype.Date `json:"birth_date"`
	Season        int32       `json:"season"`
	TeamID        int64       `json:"team_id"`
	GamesPlayed   int32       `json:"games_played"`
	GamesAppeared int32       `json:"games_appeared"`
	GamesStarted  int32       `json:"games_started"`
	TOISeconds    int64       `json:"toi_seconds"`
	Wins          int32       `json:"wins"`
	Shutouts      int32       `json:"shutouts"`
	ShotsAgainst  int64       `json:"shots_against"`
	Saves         int64       `json:"saves"`
	GoalsAgainst  int64       `json:"goals_against"`
}

func (q *Queries) ListProjectionGoalieHistory(ctx context.Context, arg ListProjectionGoalieHistoryParams) ([]ListProjectionGoalieHistoryRow, error) {
	rows, err := q.db.Query(ctx, listProjectionGoalieHistory,
		arg.Season,
		arg.Season_2,
		arg.GameDate,
		arg.MinimumShutoutToiSeconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionGoalieHistoryRow{}
	for rows.Next() {
		var i ListProjectionGoalieHistoryRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.BirthDate,
			&i.Season,
			&i.TeamID,
			&i.GamesPlayed,
			&i.GamesAppeared,
			&i.GamesStarted,
			&i.TOISeconds,
			&i.Wins,
			&i.Shutouts,
			&i.ShotsAgainst,
			&i.Saves,
			&i.GoalsAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionGoalieRecentStarts = `-- name: ListProjectionGoalieRecentStarts :many
WITH starts AS (
    SELECT
        s.team_id,
        s.player_id,
        g.id AS game_id,
        g.season,
        g.game_date,
        g.game_type,
        DENSE_RANK() OVER (
            PARTITION BY s.team_id ORDER BY g.game_date DESC, g.id DESC
        ) AS recency_rank,
        DENSE_RANK() OVER (
            PARTITION BY s.team_id, g.game_type ORDER BY g.game_date DESC, g.id DESC
        ) AS type_rank
    FROM game_goalie_stats s
    JOIN games g ON g.id = s.game_id
    WHERE g.game_type IN ('regular_season', 'playoffs')
      AND g.game_state IN ('FINAL', 'OFF')
      AND g.season < $2
      AND g.season >= $3
      AND g.game_date <= $4
      AND s.starter = TRUE
)
SELECT
    team_id,
    player_id,
    game_id,
    season,
    game_date,
    game_type,
    recency_rank::int AS recency_rank,
    (CASE WHEN game_type = 'regular_season' THEN type_rank ELSE 0 END)::int AS regular_season_rank
FROM starts
WHERE recency_rank <= $1::int
   OR (game_type = 'regular_season' AND type_rank <= $1::int)
ORDER BY team_id, recency_rank, player_id
`

type ListProjectionGoalieRecentStartsParams struct {
	WindowGames  int32       `json:"window_games"`
	TargetSeason int32       `json:"target_season"`
	MinSeason    int32       `json:"min_season"`
	Cutoff       pgtype.Date `json:"cutoff"`
}

type ListProjectionGoalieRecentStartsRow struct {
	TeamID            int64       `json:"team_id"`
	PlayerID          int64       `json:"player_id"`
	GameID            int64       `json:"game_id"`
	Season            int32       `json:"season"`
	GameDate          pgtype.Date `json:"game_date"`
	GameType          GameType    `json:"game_type"`
	RecencyRank       int32       `json:"recency_rank"`
	RegularSeasonRank int32       `json:"regular_season_rank"`
}

// Each club's most recent started games on or before the cutoff, across the
// regular season and playoffs of the history window, one row per flagged
// starter (nhl-baseline-v7's goalie start share). starter is TRUE or NULL,
// never FALSE; a team-game whose boxscore flags no starter (some 2025-26
// games) contributes no row, so it neither fills a window slot nor dilutes
// the shares. recency_rank numbers a club's started games newest first over
// both game types; regular_season_rank numbers its regular-season games
// alone, so a model that ignores playoffs still gets a full window. Both are
// DENSE_RANK so a game with two flagged starters takes one slot.
func (q *Queries) ListProjectionGoalieRecentStarts(ctx context.Context, arg ListProjectionGoalieRecentStartsParams) ([]ListProjectionGoalieRecentStartsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionGoalieRecentStarts,
		arg.WindowGames,
		arg.TargetSeason,
		arg.MinSeason,
		arg.Cutoff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionGoalieRecentStartsRow{}
	for rows.Next() {
		var i ListProjectionGoalieRecentStartsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.GameID,
			&i.Season,
			&i.GameDate,
			&i.GameType,
			&i.RecencyRank,
			&i.RegularSeasonRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionPlayers = `-- name: ListProjectionPlayers :many
SELECT snapshot_id, player_key, player_id, team_id, player_kind, position, source, provider, provider_version, source_as_of, incorporates_news_through, history_seasons, history_games, sample_exposure, uncertainty, insufficient_history, missing_stats, linemate_observed_points_per_60, linemate_average_points_per_60, linemate_shared_toi_seconds, linemate_adjustment_factor, team_environment FROM projection_players
WHERE snapshot_id = $1
ORDER BY player_key
`

func (q *Queries) ListProjectionPlayers(ctx context.Context, snapshotID pgtype.UUID) ([]ProjectionPlayer, error) {
	rows, err := q.db.Query(ctx, listProjectionPlayers, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionPlayer{}
	for rows.Next() {
		var i ProjectionPlayer
		if err := rows.Scan(
			&i.SnapshotID,
			&i.PlayerKey,
			&i.PlayerID,
			&i.TeamID,
			&i.PlayerKind,
			&i.Position,
			&i.Source,
			&i.Provider,
			&i.ProviderVersion,
			&i.SourceAsOf,
			&i.IncorporatesNewsThrough,
			&i.HistorySeasons,
			&i.HistoryGames,
			&i.SampleExposure,
			&i.Uncertainty,
			&i.InsufficientHistory,
			&i.MissingStats,
			&i.LinemateObservedPointsPer60,
			&i.LinemateAveragePointsPer60,
			&i.LinemateSharedToiSeconds,
			&i.LinemateAdjustmentFactor,
			&i.TeamEnvironment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionSkaterClubGames = `-- name: ListProjectionSkaterClubGames :many
WITH club_games AS (
    SELECT
        s.player_id,
        g.season,
        s.team_id,
        COUNT(DISTINCT s.game_id)::int AS games_played,
        COUNT(*) OVER (PARTITION BY s.player_id, g.season) AS clubs
    FROM game_skater_stats s
    JOIN games g ON g.id = s.game_id
    WHERE g.game_type = 'regular_season'
      AND g.game_state IN ('FINAL', 'OFF')
      AND g.season < $1
      AND g.season >= $2
      AND g.game_date <= $3
    GROUP BY s.player_id, g.season, s.team_id
)
SELECT player_id, season, team_id, games_played
FROM club_games
WHERE clubs > 1
ORDER BY player_id, season, team_id
`

type ListProjectionSkaterClubGamesParams struct {
	Season   int32       `json:"season"`
	Season_2 int32       `json:"season_2"`
	GameDate pgtype.Date `json:"game_date"`
}

type ListProjectionSkaterClubGamesRow struct {
	PlayerID    int64 `json:"player_id"`
	Season      int32 `json:"season"`
	TeamID      int64 `json:"team_id"`
	GamesPlayed int32 `json:"games_played"`
}

// Per-club games of the skater seasons that were split between clubs (a
// trade), over the same games and window as ListProjectionSkaterHistory,
// whose single row per season names only the last club. The
// team-environment adjustment weighs a player's history by the clubs the
// games were actually played for; a season with one club needs no row here.
func (q *Queries) ListProjectionSkaterClubGames(ctx context.Context, arg ListProjectionSkaterClubGamesParams) ([]ListProjectionSkaterClubGamesRow, error) {
	rows, err := q.db.Query(ctx, listProjectionSkaterClubGames, arg.Season, arg.Season_2, arg.GameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionSkaterClubGamesRow{}
	for rows.Next() {
		var i ListProjectionSkaterClubGamesRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.TeamID,
			&i.GamesPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionSkaterEvaluationData = `-- name: ListProjectionSkaterEvaluationData :many
WITH faceoff_totals AS (
    -- One row per (game, player): counts wins and losses from play_events
    -- so the LEFT JOIN below cannot multiply game_skater_stats rows.
    SELECT
        game_id,
        player_id,
        SUM(faceoffs_won)::bigint AS faceoffs_won,
        SUM(faceoffs_lost)::bigint AS faceoffs_lost
    FROM (
        SELECT game_id, winning_player_id AS player_id, 1 AS faceoffs_won, 0 AS faceoffs_lost
        FROM play_events
        WHERE type_desc_key = 'faceoff'
        UNION ALL
        SELECT game_id, losing_player_id AS player_id, 0 AS faceoffs_won, 1 AS faceoffs_lost
        FROM play_events
        WHERE type_desc_key = 'faceoff'
    ) per_faceoff
    GROUP BY game_id, player_id
)
SELECT
    s.player_id,
    p.birth_date,
    g.season,
    (ARRAY_AGG(s.team_id ORDER BY g.game_date DESC, s.game_id DESC))[1]::bigint AS team_id,
    (ARRAY_AGG(s.position ORDER BY g.game_date DESC, s.game_id DESC))[1]::text AS position,
    COUNT(DISTINCT s.game_id)::int AS games_played,
    SUM(s.toi_seconds)::bigint AS toi_seconds,
    SUM(s.goals)::bigint AS goals,
    SUM(s.assists)::bigint AS assists,
    SUM(s.plus_minus)::bigint AS plus_minus,
    SUM(s.penalty_minutes)::bigint AS penalty_minutes,
    SUM(s.power_play_points)::bigint AS power_play_points,
    SUM(s.shots_on_goal)::bigint AS shots_on_goal,
    SUM(s.hits)::bigint AS hits,
    SUM(s.blocked_shots)::bigint AS blocked_shots,
    COALESCE(SUM(fo.faceoffs_won), 0)::bigint AS faceoffs_won,
    COALESCE(SUM(fo.faceoffs_lost), 0)::bigint AS faceoffs_lost
FROM game_skater_stats s
JOIN games g ON g.id = s.game_id
JOIN players p ON p.id = s.player_id
LEFT JOIN faceoff_totals fo ON fo.game_id = s.game_id AND fo.player_id = s.player_id
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season <= $1
  AND g.season >= $2
GROUP BY s.player_id, p.birth_date, g.season
ORDER BY s.player_id, g.season
`

type ListProjectionSkaterEvaluationDataParams struct {
	Season   int32 `json:"season"`
	Season_2 int32 `json:"season_2"`
}

type ListProjectionSkaterEvaluationDataRow struct {
	PlayerID        int64       `json:"player_id"`
	BirthDate       pgtype.Date `json:"birth_date"`
	Season          int32       `json:"season"`
	TeamID          int64       `json:"team_id"`
	Position        string      `json:"position"`
	GamesPlayed     int32       `json:"games_played"`
	TOISeconds      int64       `json:"toi_seconds"`
	Goals           int64       `json:"goals"`
	Assists         int64       `json:"assists"`
	PlusMinus       int64       `json:"plus_minus"`
	PenaltyMinutes  int64       `json:"penalty_minutes"`
	PowerPlayPoints int64       `json:"power_play_points"`
	ShotsOnGoal     int64       `json:"shots_on_goal"`
	Hits            int64       `json:"hits"`
	BlockedShots    int64       `json:"blocked_shots"`
	FaceoffsWon     int64       `json:"faceoffs_won"`
	FaceoffsLost    int64       `json:"faceoffs_lost"`
}

func (q *Queries) ListProjectionSkaterEvaluationData(ctx context.Context, arg ListProjectionSkaterEvaluationDataParams) ([]ListProjectionSkaterEvaluationDataRow, error) {
	rows, err := q.db.Query(ctx, listProjectionSkaterEvaluationData, arg.Season, arg.Season_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionSkaterEvaluationDataRow{}
	for rows.Next() {
		var i ListProjectionSkaterEvaluationDataRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.BirthDate,
			&i.Season,
			&i.TeamID,
			&i.Position,
			&i.GamesPlayed,
			&i.TOISeconds,
			&i.Goals,
			&i.Assists,
			&i.PlusMinus,
			&i.PenaltyMinutes,
			&i.PowerPlayPoints,
			&i.ShotsOnGoal,
			&i.Hits,
			&i.BlockedShots,
			&i.FaceoffsWon,
			&i.FaceoffsLost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionSkaterHistory = `-- name: ListProjectionSkaterHistory :many
WITH faceoff_totals AS (
    -- One row per (game, player): counts wins and losses from play_events
    -- so the LEFT JOIN below cannot multiply game_skater_stats rows.
    SELECT
        game_id,
        player_id,
        SUM(faceoffs_won)::bigint AS faceoffs_won,
        SUM(faceoffs_lost)::bigint AS faceoffs_lost
    FROM (
        SELECT game_id, winning_player_id AS player_id, 1 AS faceoffs_won, 0 AS faceoffs_lost
        FROM play_events
        WHERE type_desc_key = 'faceoff'
        UNION ALL
        SELECT game_id, losing_player_id AS player_id, 0 AS faceoffs_won, 1 AS faceoffs_lost
        FROM play_events
        WHERE type_desc_key = 'faceoff'
    ) per_faceoff
    GROUP BY game_id, player_id
)
SELECT
    s.player_id,
    p.birth_date,
    g.season,
    (ARRAY_AGG(s.team_id ORDER BY g.game_date DESC, s.game_id DESC))[1]::bigint AS team_id,
    (ARRAY_AGG(s.position ORDER BY g.game_date DESC, s.game_id DESC))[1]::text AS position,
    COUNT(DISTINCT s.game_id)::int AS games_played,
    SUM(s.toi_seconds)::bigint AS toi_seconds,
    SUM(s.goals)::bigint AS goals,
    SUM(s.assists)::bigint AS assists,
    SUM(s.plus_minus)::bigint AS plus_minus,
    SUM(s.penalty_minutes)::bigint AS penalty_minutes,
    SUM(s.power_play_points)::bigint AS power_play_points,
    SUM(s.shots_on_goal)::bigint AS shots_on_goal,
    SUM(s.hits)::bigint AS hits,
    SUM(s.blocked_shots)::bigint AS blocked_shots,
    COALESCE(SUM(fo.faceoffs_won), 0)::bigint AS faceoffs_won,
    COALESCE(SUM(fo.faceoffs_lost), 0)::bigint AS faceoffs_lost
FROM game_skater_stats s
JOIN games g ON g.id = s.game_id
JOIN players p ON p.id = s.player_id
LEFT JOIN faceoff_totals fo ON fo.game_id = s.game_id AND fo.player_id = s.player_id
WHERE g.game_type = 'regular_season'
  AND g.game_state IN ('FINAL', 'OFF')
  AND g.season < $1
  AND g.season >= $2
  AND g.game_date <= $3
GROUP BY s.player_id, p.birth_date, g.season
ORDER BY s.player_id, g.season
`

type ListProjectionSkaterHistoryParams struct {
	Season   int32       `json:"season"`
	Season_2 int32       `json:"season_2"`
	GameDate pgtype.Date `json:"game_date"`
}

type ListProjectionSkaterHistoryRow struct {
	PlayerID        int64       `json:"player_id"`
	BirthDate       pgtype.Date `json:"birth_date"`
	Season          int32       `json:"season"`
	TeamID          int64       `json:"team_id"`
	Position        string      `json:"position"`
	GamesPlayed     int32       `json:"games_played"`
	TOISeconds      int64       `json:"toi_seconds"`
	Goals           int64       `json:"goals"`
	Assists         int64       `json:"assists"`
	PlusMinus       int64       `json:"plus_minus"`
	PenaltyMinutes  int64       `json:"penalty_minutes"`
	PowerPlayPoints int64       `json:"power_play_points"`
	ShotsOnGoal     int64       `json:"shots_on_goal"`
	Hits            int64       `json:"hits"`
	BlockedShots    int64       `json:"blocked_shots"`
	FaceoffsWon     int64       `json:"faceoffs_won"`
	FaceoffsLost    int64       `json:"faceoffs_lost"`
}

func (q *Queries) ListProjectionSkaterHistory(ctx context.Context, arg ListProjectionSkaterHistoryParams) ([]ListProjectionSkaterHistoryRow, error) {
	rows, err := q.db.Query(ctx, listProjectionSkaterHistory, arg.Season, arg.Season_2, arg.GameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionSkaterHistoryRow{}
	for rows.Next() {
		var i ListProjectionSkaterHistoryRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.BirthDate,
			&i.Season,
			&i.TeamID,
			&i.Position,
			&i.GamesPlayed,
			&i.TOISeconds,
			&i.Goals,
			&i.Assists,
			&i.PlusMinus,
			&i.PenaltyMinutes,
			&i.PowerPlayPoints,
			&i.ShotsOnGoal,
			&i.Hits,
			&i.BlockedShots,
			&i.FaceoffsWon,
			&i.FaceoffsLost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionSkaterLinemateContext = `-- name: ListProjectionSkaterLinemateContext :many
WITH eligible_games AS NOT MATERIALIZED (
    SELECT id, season
    FROM games
    WHERE game_type = 'regular_season'
      AND game_state IN ('FINAL', 'OFF')
      AND season >= $1
      AND season <= $2
      AND game_date <= $3
),
pair_overlap AS (
    SELECT
        game.season,
        pair.player_id,
        pair.teammate_id,
        sum(pair.shared_toi_seconds)::bigint AS shared_toi_seconds
    FROM eligible_games game
    JOIN even_strength_pair_toi pair ON pair.game_id = game.id
    GROUP BY game.season, pair.player_id, pair.teammate_id
),
teammate_rates AS (
    SELECT
        game.season,
        skater.player_id,
        sum(skater.points)::bigint AS even_strength_points,
        sum(skater.toi_seconds)::bigint AS even_strength_toi_seconds
    FROM eligible_games game
    JOIN even_strength_skater_games skater ON skater.game_id = game.id
    GROUP BY game.season, skater.player_id
)
SELECT
    pair.player_id,
    pair.season,
    pair.teammate_id,
    pair.shared_toi_seconds,
    teammate_toi.even_strength_points AS teammate_even_strength_points,
    teammate_toi.even_strength_toi_seconds AS teammate_even_strength_toi_seconds
FROM pair_overlap pair
JOIN teammate_rates teammate_toi
  ON teammate_toi.season = pair.season
 AND teammate_toi.player_id = pair.teammate_id
ORDER BY pair.player_id, pair.season, pair.teammate_id
`

type ListProjectionSkaterLinemateContextParams struct {
	MinSeason int32       `json:"min_season"`
	MaxSeason int32       `json:"max_season"`
	GameDate  pgtype.Date `json:"game_date"`
}

type ListProjectionSkaterLinemateContextRow struct {
	PlayerID                       int64 `json:"player_id"`
	Season                         int32 `json:"season"`
	TeammateID                     int64 `json:"teammate_id"`
	SharedToiSeconds               int64 `json:"shared_toi_seconds"`
	TeammateEvenStrengthPoints     int64 `json:"teammate_even_strength_points"`
	TeammateEvenStrengthToiSeconds int64 `json:"teammate_even_strength_toi_seconds"`
}

// Return exact integer teammate overlap with even-strength production from
// the same eligible games. even_strength_pair_toi and
// even_strength_skater_games hold each game's precomputed even-strength
// totals (both direction pairs, and per-skater TOI/points), built at shift
// chart import (see InsertEvenStrengthPairTOIForGame and
// InsertEvenStrengthSkaterGamesForGame in even_strength_totals.sql); this
// query only filters eligible games and aggregates them. Go accumulates
// rates in this stable order so floating-point sums cannot perturb hashes.
func (q *Queries) ListProjectionSkaterLinemateContext(ctx context.Context, arg ListProjectionSkaterLinemateContextParams) ([]ListProjectionSkaterLinemateContextRow, error) {
	rows, err := q.db.Query(ctx, listProjectionSkaterLinemateContext, arg.MinSeason, arg.MaxSeason, arg.GameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionSkaterLinemateContextRow{}
	for rows.Next() {
		var i ListProjectionSkaterLinemateContextRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Season,
			&i.TeammateID,
			&i.SharedToiSeconds,
			&i.TeammateEvenStrengthPoints,
			&i.TeammateEvenStrengthToiSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionTargetTeams = `-- name: ListProjectionTargetTeams :many
SELECT DISTINCT ON (r.player_id) r.player_id, r.team_id
FROM season_rosters r
JOIN season_teams st ON st.season = r.season AND st.team_id = r.team_id
WHERE r.season = $1 AND st.team_kind = 'nhl'
ORDER BY r.player_id, r.updated_at DESC, r.team_id
`

type ListProjectionTargetTeamsRow struct {
	PlayerID int64 `json:"player_id"`
	TeamID   int64 `json:"team_id"`
}

// Each player's NHL club for the target season, from its imported rosters:
// the most recently updated roster row wins when a player appears on more
// than one club (the same rule as the stand-in draft pool). Empty until the
// season's rosters are imported, which leaves the team-environment
// adjustment off.
func (q *Queries) ListProjectionTargetTeams(ctx context.Context, season int32) ([]ListProjectionTargetTeamsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionTargetTeams, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionTargetTeamsRow{}
	for rows.Next() {
		var i ListProjectionTargetTeamsRow
		if err := rows.Scan(&i.PlayerID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionTeamSeasons = `-- name: ListProjectionTeamSeasons :many
WITH club_games AS (
    SELECT g.id AS game_id, g.season, g.home_team_id AS team_id, g.away_team_id AS opponent_id,
           g.home_team_score - CASE
               WHEN g.period_type = 'SO' AND g.home_team_score > g.away_team_score THEN 1 ELSE 0
           END AS goals_for,
           g.home_team_sog AS shots_for
    FROM games g
    WHERE g.game_type = 'regular_season'
      AND g.game_state IN ('FINAL', 'OFF')
      AND g.season < $1
      AND g.season >= $2
      AND g.game_date <= $3
    UNION ALL
    SELECT g.id, g.season, g.away_team_id, g.home_team_id,
           g.away_team_score - CASE
               WHEN g.period_type = 'SO' AND g.away_team_score > g.home_team_score THEN 1 ELSE 0
           END,
           g.away_team_sog
    FROM games g
    WHERE g.game_type = 'regular_season'
      AND g.game_state IN ('FINAL', 'OFF')
      AND g.season < $1
      AND g.season >= $2
      AND g.game_date <= $3
),
club_power_play AS (
    SELECT cg.game_id, cg.team_id,
           EXISTS (SELECT 1 FROM play_events pe WHERE pe.game_id = cg.game_id) AS has_play_by_play,
           (SELECT COUNT(*) FROM play_events pe
            WHERE pe.game_id = cg.game_id
              AND pe.event_owner_team_id = cg.opponent_id
              AND pe.type_desc_key = 'penalty'
              AND pe.penalty_type_code IN ('MIN', 'BEN')) AS opportunities
    FROM club_games cg
)
SELECT
    cg.team_id,
    cg.season,
    COALESCE(MAX(st.abbrev), '')::text AS abbrev,
    COUNT(*)::int AS games_played,
    SUM(cg.goals_for)::bigint AS goals_for,
    SUM(cg.shots_for)::bigint AS shots_for,
    COUNT(*) FILTER (WHERE pp.has_play_by_play)::int AS power_play_games,
    COALESCE(SUM(pp.opportunities) FILTER (WHERE pp.has_play_by_play), 0)::bigint AS power_play_opportunities
FROM club_games cg
JOIN club_power_play pp ON pp.game_id = cg.game_id AND pp.team_id = cg.team_id
LEFT JOIN season_teams st ON st.season = cg.season AND st.team_id = cg.team_id
GROUP BY cg.team_id, cg.season
ORDER BY cg.team_id, cg.season
`

type ListProjectionTeamSeasonsParams struct {
	Season   int32       `json:"season"`
	Season_2 int32       `json:"season_2"`
	GameDate pgtype.Date `json:"game_date"`
}

type ListProjectionTeamSeasonsRow struct {
	TeamID                 int64  `json:"team_id"`
	Season                 int32  `json:"season"`
	Abbrev                 string `json:"abbrev"`
	GamesPlayed            int32  `json:"games_played"`
	GoalsFor               int64  `json:"goals_for"`
	ShotsFor               int64  `json:"shots_for"`
	PowerPlayGames         int32  `json:"power_play_games"`
	PowerPlayOpportunities int64  `json:"power_play_opportunities"`
}

// Each NHL club's regular-season environment per season, for the
// team-environment adjustment (internal/projection/teamenv.go), over the
// same games and window as ListProjectionSkaterHistory (season_2 <= season
// < season, completed games through game_date). goals_for drops the
// shootout winner's extra goal; shots_for is the club's shots on goal.
// Power-play opportunities are the minor and bench-minor penalties charged
// to the opponent (coincidental minors over-count slightly), counted only
// in games that have play-by-play (power_play_games) so a game whose
// events were never imported does not read as zero opportunities.
func (q *Queries) ListProjectionTeamSeasons(ctx context.Context, arg ListProjectionTeamSeasonsParams) ([]ListProjectionTeamSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listProjectionTeamSeasons, arg.Season, arg.Season_2, arg.GameDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectionTeamSeasonsRow{}
	for rows.Next() {
		var i ListProjectionTeamSeasonsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.Season,
			&i.Abbrev,
			&i.GamesPlayed,
			&i.GoalsFor,
			&i.ShotsFor,
			&i.PowerPlayGames,
			&i.PowerPlayOpportunities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionValues = `-- name: ListProjectionValues :many
SELECT snapshot_id, player_key, stat, mean, low, high FROM projection_values
WHERE snapshot_id = $1
ORDER BY player_key, stat
`

func (q *Queries) ListProjectionValues(ctx context.Context, snapshotID pgtype.UUID) ([]ProjectionValue, error) {
	rows, err := q.db.Query(ctx, listProjectionValues, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionValue{}
	for rows.Next() {
		var i ProjectionValue
		if err := rows.Scan(
			&i.SnapshotID,
			&i.PlayerKey,
			&i.Stat,
			&i.Mean,
			&i.Low,
			&i.High,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
