// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const carryForwardSeasonTeam = `-- name: CarryForwardSeasonTeam :execrows
INSERT INTO season_teams (
    season, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev, team_kind
)
SELECT $1::integer, $2::bigint, franchise_id, full_name, abbrev, logo_url,
       division_name, division_abbrev, conference_name, conference_abbrev, team_kind
FROM season_teams
WHERE season = $3::integer AND team_id = $4::bigint AND team_kind = 'nhl'
ON CONFLICT (season, team_id) DO NOTHING
`

type CarryForwardSeasonTeamParams struct {
	ToSeason   int32 `json:"to_season"`
	ToTeamID   int64 `json:"to_team_id"`
	FromSeason int32 `json:"from_season"`
	FromTeamID int64 `json:"from_team_id"`
}

// Copies one of a season's NHL clubs to the next season, under the team ID
// the caller resolved for that season (the NHL has reissued IDs under the
// same abbreviation: Utah 59 -> 68), before the NHL publishes the season's
// standings (the only source of season_teams otherwise), so its camp
// rosters can be imported ahead of puck drop. A club already present for
// the new season is left as is; standings replace the copied rows once the
// season has them.
func (q *Queries) CarryForwardSeasonTeam(ctx context.Context, arg CarryForwardSeasonTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, carryForwardSeasonTeam,
		arg.ToSeason,
		arg.ToTeamID,
		arg.FromSeason,
		arg.FromTeamID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSeasonTeams = `-- name: CountSeasonTeams :one
SELECT COUNT(*) FROM season_teams
`

func (q *Queries) CountSeasonTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasonTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSeasonTeamsForSeason = `-- name: CountSeasonTeamsForSeason :one
SELECT COUNT(*) FROM season_teams WHERE season = $1
`

func (q *Queries) CountSeasonTeamsForSeason(ctx context.Context, season int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasonTeamsForSeason, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSeasons = `-- name: CountSeasons :one
SELECT COUNT(*) FROM seasons
`

func (q *Queries) CountSeasons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamLogos = `-- name: CountTeamLogos :one
SELECT COUNT(DISTINCT team_id) FROM season_teams
WHERE logo_url IS NOT NULL AND logo_url <> ''
`

// Distinct teams that have at least one season with a non-empty logo URL.
// Matches the cardinality of ListTeamLogos so the parent's progress bar Total
// aligns with the rows the loader produces.
func (q *Queries) CountTeamLogos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamLogos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllSeasons = `-- name: GetAllSeasons :many
SELECT id, standings_start, standings_end
FROM seasons
ORDER BY id DESC
`

func (q *Queries) GetAllSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, getAllSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(&i.ID, &i.StandingsStart, &i.StandingsEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDivisions = `-- name: GetDistinctDivisions :many
SELECT DISTINCT division_name, division_abbrev, conference_name, conference_abbrev
FROM season_teams
WHERE season = $1 AND team_kind = 'nhl'
ORDER BY conference_name, division_name
`

type GetDistinctDivisionsRow struct {
	DivisionName     pgtype.Text `json:"division_name"`
	DivisionAbbrev   pgtype.Text `json:"division_abbrev"`
	ConferenceName   pgtype.Text `json:"conference_name"`
	ConferenceAbbrev pgtype.Text `json:"conference_abbrev"`
}

func (q *Queries) GetDistinctDivisions(ctx context.Context, season int32) ([]GetDistinctDivisionsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctDivisions, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctDivisionsRow{}
	for rows.Next() {
		var i GetDistinctDivisionsRow
		if err := rows.Scan(
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeason = `-- name: GetSeason :one
SELECT id, standings_start, standings_end
FROM seasons
WHERE id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id int32) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(&i.ID, &i.StandingsStart, &i.StandingsEnd)
	return i, err
}

const getSeasonTeam = `-- name: GetSeasonTeam :one
SELECT season, team_id, franchise_id, full_name, abbrev, logo_url, division_name, division_abbrev, conference_name, conference_abbrev, team_kind FROM season_teams
WHERE season = $1 AND team_id = $2 AND team_kind = 'nhl'
`

type GetSeasonTeamParams struct {
	Season int32 `json:"season"`
	TeamID int64 `json:"team_id"`
}

func (q *Queries) GetSeasonTeam(ctx context.Context, arg GetSeasonTeamParams) (SeasonTeam, error) {
	row := q.db.QueryRow(ctx, getSeasonTeam, arg.Season, arg.TeamID)
	var i SeasonTeam
	err := row.Scan(
		&i.Season,
		&i.TeamID,
		&i.FranchiseID,
		&i.FullName,
		&i.Abbrev,
		&i.LogoUrl,
		&i.DivisionName,
		&i.DivisionAbbrev,
		&i.ConferenceName,
		&i.ConferenceAbbrev,
		&i.TeamKind,
	)
	return i, err
}

const getSeasonTeams = `-- name: GetSeasonTeams :many
SELECT season, team_id, franchise_id, full_name, abbrev, logo_url, division_name, division_abbrev, conference_name, conference_abbrev, team_kind FROM season_teams
WHERE season = $1 AND team_kind = 'nhl'
ORDER BY division_name, full_name
`

func (q *Queries) GetSeasonTeams(ctx context.Context, season int32) ([]SeasonTeam, error) {
	rows, err := q.db.Query(ctx, getSeasonTeams, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonTeam{}
	for rows.Next() {
		var i SeasonTeam
		if err := rows.Scan(
			&i.Season,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
			&i.TeamKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonTeamsByDivision = `-- name: GetSeasonTeamsByDivision :many
SELECT season, team_id, franchise_id, full_name, abbrev, logo_url, division_name, division_abbrev, conference_name, conference_abbrev, team_kind FROM season_teams
WHERE season = $1 AND division_name = $2 AND team_kind = 'nhl'
ORDER BY full_name
`

type GetSeasonTeamsByDivisionParams struct {
	Season       int32       `json:"season"`
	DivisionName pgtype.Text `json:"division_name"`
}

func (q *Queries) GetSeasonTeamsByDivision(ctx context.Context, arg GetSeasonTeamsByDivisionParams) ([]SeasonTeam, error) {
	rows, err := q.db.Query(ctx, getSeasonTeamsByDivision, arg.Season, arg.DivisionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonTeam{}
	for rows.Next() {
		var i SeasonTeam
		if err := rows.Scan(
			&i.Season,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
			&i.TeamKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamHistory = `-- name: GetTeamHistory :many
SELECT season, team_id, franchise_id, full_name, abbrev, logo_url, division_name, division_abbrev, conference_name, conference_abbrev, team_kind FROM season_teams
WHERE franchise_id = $1 AND team_kind = 'nhl'
ORDER BY season DESC
`

func (q *Queries) GetTeamHistory(ctx context.Context, franchiseID pgtype.Int8) ([]SeasonTeam, error) {
	rows, err := q.db.Query(ctx, getTeamHistory, franchiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeasonTeam{}
	for rows.Next() {
		var i SeasonTeam
		if err := rows.Scan(
			&i.Season,
			&i.TeamID,
			&i.FranchiseID,
			&i.FullName,
			&i.Abbrev,
			&i.LogoUrl,
			&i.DivisionName,
			&i.DivisionAbbrev,
			&i.ConferenceName,
			&i.ConferenceAbbrev,
			&i.TeamKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamLogos = `-- name: ListTeamLogos :many
SELECT DISTINCT ON (team_id) team_id, logo_url
FROM season_teams
WHERE logo_url IS NOT NULL AND logo_url <> ''
ORDER BY team_id, season DESC
`

type ListTeamLogosRow struct {
	TeamID  int64       `json:"team_id"`
	LogoUrl pgtype.Text `json:"logo_url"`
}

// DISTINCT ON (team_id) with ORDER BY team_id, season DESC picks the latest-season
// URL per team. Path layout is assets/teams/logos/<team_id>.<ext> (no per-season
// nesting), so we want the newest URL to write.
func (q *Queries) ListTeamLogos(ctx context.Context) ([]ListTeamLogosRow, error) {
	rows, err := q.db.Query(ctx, listTeamLogos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamLogosRow{}
	for rows.Next() {
		var i ListTeamLogosRow
		if err := rows.Scan(&i.TeamID, &i.LogoUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInternationalSeasonTeam = `-- name: UpsertInternationalSeasonTeam :exec
INSERT INTO season_teams (
    season, team_id, full_name, abbrev, team_kind
)
VALUES ($1, $2, $3, $4, 'international')
ON CONFLICT (season, team_id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    abbrev = EXCLUDED.abbrev
WHERE season_teams.team_kind = 'international'
  AND (season_teams.full_name, season_teams.abbrev)
      IS DISTINCT FROM (EXCLUDED.full_name, EXCLUDED.abbrev)
`

type UpsertInternationalSeasonTeamParams struct {
	Season   int32  `json:"season"`
	TeamID   int64  `json:"team_id"`
	FullName string `json:"full_name"`
	Abbrev   string `json:"abbrev"`
}

// Upsert an international/national-team season row (Canada, USA,
// Sweden, etc. at NHL API team IDs 60–67) referenced by
// player_season_totals for WJC/Olympic/WC entries. franchise_id and
// division/conference fields are NULL for these.
func (q *Queries) UpsertInternationalSeasonTeam(ctx context.Context, arg UpsertInternationalSeasonTeamParams) error {
	_, err := q.db.Exec(ctx, upsertInternationalSeasonTeam,
		arg.Season,
		arg.TeamID,
		arg.FullName,
		arg.Abbrev,
	)
	return err
}

const upsertSeason = `-- name: UpsertSeason :exec
INSERT INTO seasons (id, standings_start, standings_end)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    standings_start = EXCLUDED.standings_start,
    standings_end = EXCLUDED.standings_end
WHERE (seasons.standings_start, seasons.standings_end)
      IS DISTINCT FROM
      (EXCLUDED.standings_start, EXCLUDED.standings_end)
`

type UpsertSeasonParams struct {
	ID             int32       `json:"id"`
	StandingsStart pgtype.Date `json:"standings_start"`
	StandingsEnd   pgtype.Date `json:"standings_end"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) error {
	_, err := q.db.Exec(ctx, upsertSeason, arg.ID, arg.StandingsStart, arg.StandingsEnd)
	return err
}

const upsertSeasonTeam = `-- name: UpsertSeasonTeam :exec
INSERT INTO season_teams (
    season, team_id, franchise_id, full_name, abbrev, logo_url,
    division_name, division_abbrev, conference_name, conference_abbrev
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (season, team_id) DO UPDATE SET
    franchise_id = EXCLUDED.franchise_id,
    full_name = EXCLUDED.full_name,
    abbrev = EXCLUDED.abbrev,
    logo_url = EXCLUDED.logo_url,
    division_name = EXCLUDED.division_name,
    division_abbrev = EXCLUDED.division_abbrev,
    conference_name = EXCLUDED.conference_name,
    conference_abbrev = EXCLUDED.conference_abbrev
WHERE (season_teams.franchise_id, season_teams.full_name,
       season_teams.abbrev, season_teams.logo_url,
       season_teams.division_name, season_teams.division_abbrev,
       season_teams.conference_name, season_teams.conference_abbrev)
      IS DISTINCT FROM
      (EXCLUDED.franchise_id, EXCLUDED.full_name,
       EXCLUDED.abbrev, EXCLUDED.logo_url,
       EXCLUDED.division_name, EXCLUDED.division_abbrev,
       EXCLUDED.conference_name, EXCLUDED.conference_abbrev)
`

type UpsertSeasonTeamParams struct {
	Season           int32       `json:"season"`
	TeamID           int64       `json:"team_id"`
	FranchiseID      pgtype.Int8 `json:"franchise_id"`
	FullName         string      `json:"full_name"`
	Abbrev           string      `json:"abbrev"`
	LogoUrl          pgtype.Text `json:"logo_url"`
	DivisionName     pgtype.Text `json:"division_name"`
	DivisionAbbrev   pgtype.Text `json:"division_abbrev"`
	ConferenceName   pgtype.Text `json:"conference_name"`
	ConferenceAbbrev pgtype.Text `json:"conference_abbrev"`
}

// Upsert an NHL season-team row. team_kind is implicitly 'nhl' (column
// default); international teams use UpsertInternationalSeasonTeam.
func (q *Queries) UpsertSeasonTeam(ctx context.Context, arg UpsertSeasonTeamParams) error {
	_, err := q.db.Exec(ctx, upsertSeasonTeam,
		arg.Season,
		arg.TeamID,
		arg.FranchiseID,
		arg.FullName,
		arg.Abbrev,
		arg.LogoUrl,
		arg.DivisionName,
		arg.DivisionAbbrev,
		arg.ConferenceName,
		arg.ConferenceAbbrev,
	)
	return err
}
