// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: yahoo_league_players.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleYahooLeaguePlayers = `-- name: DeleteStaleYahooLeaguePlayers :execrows
DELETE FROM yahoo_league_players
WHERE league_key = $1 AND fetched_at < $2
`

type DeleteStaleYahooLeaguePlayersParams struct {
	LeagueKey string             `json:"league_key"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

// Removes players a newer complete pool snapshot no longer lists.
func (q *Queries) DeleteStaleYahooLeaguePlayers(ctx context.Context, arg DeleteStaleYahooLeaguePlayersParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleYahooLeaguePlayers, arg.LeagueKey, arg.FetchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listYahooLeaguePlayersWithNHL = `-- name: ListYahooLeaguePlayersWithNHL :many
SELECT lp.league_key, lp.season, lp.league_id, lp.game_key, lp.player_id, lp.player_key, lp.full_name, lp.editorial_team_abbr, lp.display_position, lp.primary_position, lp.position_type, lp.eligible_positions, lp.status, lp.status_full, lp.injury_note, lp.on_disabled_list, lp.fetched_at, lp.imported_at, p.id AS nhl_player_id
FROM yahoo_league_players lp
LEFT JOIN players p ON p.yahoo_id = lp.player_id
WHERE lp.league_key = $1
ORDER BY lp.player_id
`

type ListYahooLeaguePlayersWithNHLRow struct {
	LeagueKey         string             `json:"league_key"`
	Season            int32              `json:"season"`
	LeagueID          int32              `json:"league_id"`
	GameKey           int32              `json:"game_key"`
	PlayerID          int32              `json:"player_id"`
	PlayerKey         string             `json:"player_key"`
	FullName          string             `json:"full_name"`
	EditorialTeamAbbr string             `json:"editorial_team_abbr"`
	DisplayPosition   string             `json:"display_position"`
	PrimaryPosition   string             `json:"primary_position"`
	PositionType      string             `json:"position_type"`
	EligiblePositions []string           `json:"eligible_positions"`
	Status            string             `json:"status"`
	StatusFull        string             `json:"status_full"`
	InjuryNote        string             `json:"injury_note"`
	OnDisabledList    bool               `json:"on_disabled_list"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
	ImportedAt        pgtype.Timestamptz `json:"imported_at"`
	NhlPlayerID       pgtype.Int8        `json:"nhl_player_id"`
}

// The league's pool with the NHL player each Yahoo ID maps to (NULL when
// unmatched, e.g. a rookie without NHL history).
func (q *Queries) ListYahooLeaguePlayersWithNHL(ctx context.Context, leagueKey string) ([]ListYahooLeaguePlayersWithNHLRow, error) {
	rows, err := q.db.Query(ctx, listYahooLeaguePlayersWithNHL, leagueKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListYahooLeaguePlayersWithNHLRow{}
	for rows.Next() {
		var i ListYahooLeaguePlayersWithNHLRow
		if err := rows.Scan(
			&i.LeagueKey,
			&i.Season,
			&i.LeagueID,
			&i.GameKey,
			&i.PlayerID,
			&i.PlayerKey,
			&i.FullName,
			&i.EditorialTeamAbbr,
			&i.DisplayPosition,
			&i.PrimaryPosition,
			&i.PositionType,
			&i.EligiblePositions,
			&i.Status,
			&i.StatusFull,
			&i.InjuryNote,
			&i.OnDisabledList,
			&i.FetchedAt,
			&i.ImportedAt,
			&i.NhlPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
