name: build

#https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts

on:
  push:
    branches: [main, dev-actions]
jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the image
        run: |
          docker buildx build --push \
          --build-arg GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }} \
          --build-arg GITHUB_RUN_NUMBER=${{github.run_number}} \
          --tag ericsperano/puckdb:latest \
          --tag ericsperano/puckdb:${{github.sha}} \
          --tag ericsperano/puckdb:build-${{github.run_number}} \
          --platform linux/amd64,linux/arm64 .
